### ISSUE TITLE
Allow to configure the users folder externally from TE_BASE

### ISSUE THREAD

**Issue by bermud** [opengeospatial/teamengine#100]
At OGC and probably other deployment systems, the 'users' folder might not live in TE_BASE. Maybe a symlink exist. This makes it hard to automatically deploy. Make changes in the configuration so 'users' can be anywhere.

**Comment by upendra-sachan** [comment]
Yes sure Luis,


I will look into this issue.

Thanks.


------
Upendra Sachan
Mindstix Software Labs
http://www.mindstix.com

*Email:* upendra.sachan@mindstix.com <blah@mindstix.com>
*Phone:* +91 8446253174
*Skype:* upendra.sachan1

**Comment by bermud** [comment]
Commit was removed from main branch. Solution was hard to implement.
