### ISSUE TITLE
Exception thrown when accessing main page (status code 500)

### ISSUE THREAD

**Issue by rjmartell** [opengeospatial/teamengine#107]
<table>
<tr><th>Version(s) affected</th><td>4.1.0, 4.2-SNAPSHOT</td></tr>
<tr><th>Web container</th><td>Tomcat 7.0.5x</td></tr>
<tr><th>JDK</th><td>Oracle JDK 7</td></tr>
<tr><th>OS</th><td>Windows, Linux</td></tr>
</table>

When attempting to access the main page, an exception is thrown:
 
`org.apache.jasper.JasperException: /index.jsp (line: 13, column: 7) /header.jsp (line: 10, column: 17) File "site/title.html" not found`

![te-41-startup](https://cloud.githubusercontent.com/assets/1653506/8288908/fec9fb00-18cd-11e5-991d-56088c454d38.png)

**Comment by bermud** [comment]
Need to add a file:  title.html to the default site folder. Simple text, for example:
https://github.com/opengeospatial/teamengine-builder/blob/master/site/title.html

**Comment by bermud** [comment]
@upendra-sachan, can you do a fast check on this issue, building manually. The title.html page already exists in the webapp/site folder.

**Comment by upendra-sachan** [comment]
@bermud code worked fine, it takes title.html page from webapp/site folder. I built teamengine maually then tested it.

**Comment by bermud** [comment]
The default build creates a TE_BASE that is used by teamengine-war. TE_BASE is created by teamengine-console. title html should be added to src/main/resources
