### ISSUE TITLE
Run TE via console in headless manner

### ISSUE THREAD

**Issue by bermud** [opengeospatial/teamengine#110]
Provide a file to pass parameters to TEAM Engine instead of interacting with the user interface

From Andrea at [CITE forum](http://lists.opengeospatial.org/pipermail/cite-forum/2015-June/001505.html)

This approach has been used for several years in GeoServer nightly CITE
tests and it's based on a patch by Justin Deolivera, made in times when
contributing to the teamengine and cite tests was ... uh... significantly
harder than today:
https://github.com/jdeolive/teamengine-old/compare/headless

Since the development is now more open, I'd prefer to have these improvements
merged into the official repo, instead of forking it.

The idea of the headless operation is simple, we have a HeadlessForm reading pre-recorded
responses from a xml file. The headless mode and the location
where the form files are provided as system variables, the files look
as follows:
https://github.com/geoserver/geoserver-cite-tools/blob/master/forms/wms-1.3.0.xml
and the system variables in the invocation look as:
-Dcite.headless=true -Dcite.headless.formroot=/path/to/folder/contaning/forms

I could create a pull request as is of course, but I believe it would
be a bit more in line with how te_console works with a small variant over the existing code:
* Pass the full path to the form file, just like the paths to the ctl files are passed as command
  line parameter, and use a "-form" extra command line parameter instead, pointing at the
  form file
* In case of extra forms need to be used, one can add multiple -form parameters, which 
  will be used in order.

**Comment by bermud** [comment]
This will work to pass the initial parameters. How those it works for a test like WMS that requires the user feedback?

**Comment by aaime** [comment]
Those are subsequent forms, we will be able to pass more than one. Right now we are just answering "yes" to those questions, it's hard to make a image comparator that would work cross server, and in some of the requests, it's not even a image comparison, it requires a human, so those checks are simply going to be skipped by the headless build.

The objective of the headless build is not to pass certification, but to ensure that all tests that can be run automatically, are checked with high frequency (daily in the GeoServer case).

**Comment by bermud** [comment]
I understand the purpose. 
Each form will have its own file. How do we tell TEAM Engine which file to use every time there is a need to pass values in the middle of the test?

**Comment by aaime** [comment]
I am targeting the console, so we know which test will be run in advance, thus we can give a list of form files, to be used in sequence: ``-form=file1 -form file2 -form file3``

The web version is meant to be interactive and serve several different users, so I would not worry about it, the headless case is not a match for what the webapp does.

**Comment by bermud** [comment]
Ok,  so the order of the files given as arguments should match the appearance of the forms in the UI. 

Anybody knows of a clean way to get which form is being invoked? IT would be nice to include this information in the form xml (e.g. the [wms 1.3](https://github.com/geoserver/geoserver-cite-tools/blob/master/forms/wms-1.3.0.xml)), and not depend on the order. If not, writing the question (e.g. "Does the image above depict a map of the Blue Lake vicinity with a surrounding neat line?" in the form xml can help users to create the forms.

**Comment by bermud** [comment]
@rjmartell, @segoerke  and @upendra-sachan any thoughts about this proposal?

**Comment by aaime** [comment]
Any progress? Shall I move on as originally suggested?

**Comment by bermud** [comment]
Yes. Please do. Thank you.

**Comment by aaime** [comment]
Pull request here: https://github.com/opengeospatial/teamengine/pull/114
