### ISSUE TITLE
invoking external CTLs for profiles and extensions

### ISSUE THREAD

**Issue by bermud** [opengeospatial/teamengine#111]
Profiles and extensions sometimes require to invoke other tests.

WMTS provides several profiles, but all in the same test  (see example [CTL](https://github.com/opengeospatial/ets-wmts10/blob/master/src/main/scripts/ctl/WMTS_ETS.xml>.))

```
<ctl:suite name="wmts:server.suite.base">
   <ctl:title>WMTS 1.0 Server Compliance Test Suite Base</ctl:title>
   <ctl:starting-test>wmts:main</ctl:starting-test>
 </ctl:suite>

<ctl:profile name="wmts:server.profile.kvp.get">
   <ctl:title>WMTS 1.0 Server Compliance Test Profile for KVP GET
binding</ctl:title>
   <ctl:description>Verifies that a WMTS 1.0 server implementation complies
with conformance classes for KVP GET binding.</ctl:description>
   <ctl:base>wmts:server.suite.base</ctl:base>
   <ctl:starting-test>wmts:server.profile.kvp.get.main</ctl:starting-test>
 </ctl:profile>

<ctl:profile name="wmts:server.profile.kvp.post">
   <ctl:title>WMTS 1.0 Server Compliance Test Profile for KVP POST
binding</ctl:title>
   <ctl:description>Verifies that a WMTS 1.0 server implementation complies
with conformance classes for KVP POST binding.</ctl:description>
   <ctl:base>wmts:server.suite.base</ctl:base>

<ctl:starting-test>wmts:server.profile.kvp.post.main</ctl:starting-test>
 </ctl:profile>


```

We should be able to call other tests from a test in another test folder.

**Comment by bermud** [comment]
Questions that need to be answered.
- Will the profile CTL invoke the test in an another folder or do we
need to put all CTLs in the same folder?
- Can a test be loaded via a url. In this way, tests will be able to share test functions and avoid duplicating functionality of CTL files.

**Comment by pebau** [comment]
Re Q1: putting test files of 10+ WCS extensions into one folder will likely become quite unwieldy.

In order to release the ~5 pending WCS extension tests let me suggest that we currently ignore cross-spec testing (Jin called this a "stub") and add this feature later once available.

**Comment by lgoltz** [comment]
External tests suites can be included by the REST API.
