### ISSUE TITLE
replace export-ctl with setup-tebase in tutorial

### ISSUE THREAD

**Issue by geszter** [opengeospatial/teamengine#122]
In the TEAM Engine Tutorial (https://github.com/opengeospatial/teamengine/blob/master/doc/en/index.rst), in point 10 there is this command:
c:\> te-install\bin\windows\export-ctl.bat  c:\path-to-the-file\ctl-scripts-release.csv
and in fact it should be something like this:
c:\path-to-the-folder\bin\windows\setup-tebase.bat c:\path-to-the-file\ctl-scripts-release.csv

**Comment by bermud** [comment]
There is not setup-tebase.bat. The instructions were updated here
https://github.com/opengeospatial/teamengine/blob/master/doc/en/index.rst
