### ISSUE TITLE
Prepare release 4.3

### ISSUE THREAD

**Issue by bermud** [opengeospatial/teamengine#128]
- [x] check release notes and issues closed @bermud
- [x] run integration testing scripts @aashishlodha 
- [x] tag release @rjmartell 
- [x] update version in poms @rjmartell

**Comment by rjmartell** [comment]
What are the target platforms for the integration tests? The [teamengine-integration-testing README](https://github.com/opengeospatial/teamengine-integration-testing) doesn't say.

We have encountered platform-specific issues before, so the teamengine app should be deployed in both Windows and Linux environments.
