### ISSUE TITLE
WMS 1.3 hangs in TE 4.3

### ISSUE THREAD

**Issue by bermud** [opengeospatial/teamengine#129]
Examples:
- http://vpn.k2geospatial.com:9999/wmsTest2/wms?ReQuEsT=GetCapabilities&VeRsIoN=1.3.0&SeRvIcE=WMS
-  http://cite.demo.opengeo.org:8080/geoserver_wms13/wms?service=wms&request=getcapabilities&version=1.3.0

**Comment by bermud** [comment]
Also, please  check WMS 1.3 revision 1.13 and revision 1.12.

**Comment by rjmartell** [comment]
The test suite runs successfully when executed in a command shell, so it appears that only the web app that is affected.

**Comment by bermud** [comment]
Logs examples: http://cite.opengeospatial.org/pub/cite/files/k2geospatial-wms13-20151008.zip

**Comment by aashishlodha** [comment]
Hi Luis,

We are still not clear about the exception, what is failing. The logs
folder you have shared doesn't contain any 'error_log' folder. If the test
case fails, it generates 'error_log' folder in TE_BASE/Users/{sessionId}.

Can you provide error_log folder? Or can you record a little screencast for
it? I think 'Jing' tool will be good for the recording. It have 5 minute
limit and .swf format, we can play it in browser.

Thanks and Regards,
---
Aashish Lodha
Mindstix Software Labs
http://www.mindstix.com

Email: aashish.lodha@mindstix.com
Phone: +91 8149484418
Skype: lodhaaashish

**Comment by bermud** [comment]
Here is the excerpt of the Catalina.log

```
k2geospatial/s0013/log.xml
			See the detail error Report /srv/local/teamengine-te2/TE_BASE/users/k2geospatial/s0013/error_log/log.txt
Fatal Error: A sequence of more than one item is not allowed as the first argument of string() (<Name/>, <Name/>) ; SystemID: file:/srv/local/teamengine-te2/TE_BASE/work/srv_local_teamengine-te2_TE_BASE_scripts_wms_1.3.0_ctl_/getmap/getmap$bbox-direct.test; Line#: 31; Column#: -1
Fatal Error: A sequence of more than one item is not allowed as the first argument of string() (<CRS/>, <CRS/>) ; SystemID: file:/srv/local/teamengine-te2/TE_BASE/work/srv_local_teamengine-te2_TE_BASE_scripts_wms_1.3.0_ctl_/getmap/getmap$crs-direct.test; Line#: 31; Column#: -1
Fatal Error: A sequence of more than one item is not allowed as the first argument of string() (<Name/>, <Name/>) ; SystemID: file:/srv/local/teamengine-te2/TE_BASE/work/srv_local_teamengine-te2_TE_BASE_scripts_wms_1.3.0_ctl_/getmap/getmap$invalid-crs.test; Line#: 35; Column#: -1
Fatal Error: Error in call to extension function {public synchronized void com.occamlab.te.TECore.callTest(net.sf.saxon.expr.XPathContext,java.lang.String,java.lang.String,net.sf.saxon.om.NodeInfo,java.lang.String) throws java.lang.Exception}: Exception in extension function java.util.NoSuchElementException; SystemID: file:/srv/local/teamengine-te2/TE_BASE/work/srv_local_teamengine-te2_TE_BASE_scripts_wms_1.3.0_ctl_/main/main$main.test; Line#: 267; Column#: -1
			See the detail test Report /srv/local/teamengine-te2/TE_BASE/users/k2geospatial/s0014/log.xml
			See the detail error Report /srv/local/teamengine-te2/TE_BASE/users/k2geospatial/s0014/error_log/log.txt
Fatal Error: A sequence of more than one item is not allowed as the first argument of string() (<Name/>, <Name/>) ; SystemID: file:/srv/local/teamengine-te2/TE_BASE/work/srv_local_teamengine-te2_TE_BASE_scripts_wms_1.3.0_ctl_/getmap/getmap$bbox-direct.test; Line#: 31; Column#: -1
Fatal Error: A sequence of more than one item is not allowed as the first argument of string() (<CRS/>, <CRS/>) ; SystemID: file:/srv/local/teamengine-te2/TE_BASE/work/srv_local_teamengine-te2_TE_BASE_scripts_wms_1.3.0_ctl_/getmap/getmap$crs-direct.test; Line#: 31; Column#: -1
Fatal Error: A sequence of more than one item is not allowed as the first argument of string() (<Name/>, <Name/>) ; SystemID: file:/srv/local/teamengine-te2/TE_BASE/work/srv_local_teamengine-te2_TE_BASE_scripts_wms_1.3.0_ctl_/getmap/getmap$invalid-crs.test; Line#: 35; Column#: -1
Fatal Error: Error in call to extension function {public synchronized void com.occamlab.te.TECore.callTest(net.sf.saxon.expr.XPathContext,java.lang.String,java.lang.String,net.sf.saxon.om.NodeInfo,java.lang.String) throws java.lang.Exception}: Exception in extension function java.util.NoSuchElementException; SystemID: file:/srv/local/teamengine-te2/TE_BASE/work/srv_local_teamengine-te2_TE_BASE_scripts_wms_1.3.0_ctl_/main/main$main.test; Line#: 267; Column#: -1
			See the detail test Report /srv/local/teamengine-te2/TE_BASE/users/k2geospatial/s0015/log.xml

```

**Comment by bermud** [comment]
Maybe is related to this issue/fix?
https://github.com/opengeospatial/ets-wms13/issues/15

**Comment by rjmartell** [comment]
As I noted above, the test suite (1.13) ran to completion from the command line (against the geoserver WMS endpoint) so the test suite itself is probably fine. It looks like a class loading issue in the web app to me. 

I attached the error log produced after terminating the test run. Does it look familiar to anyone?

[error-log.txt](https://github.com/opengeospatial/teamengine/files/10195/error-log.txt)

**Comment by bermud** [comment]
I also tested geoserver against the beta server (4.3) and it finished successfully.

**Comment by rjmartell** [comment]
Ack! Just ran it on a Linux box and it's fine (no errors). So perhaps it's a Windows-specific issue? Can you confirm Aashish?

**Comment by aashishlodha** [comment]
Sure, Richard. We will test this on Windows Machine tomorrow.

Thanks and Regards,
---
Aashish Lodha
Mindstix Software Labs
http://www.mindstix.com

Email: aashish.lodha@mindstix.com
Phone: +91 8149484418
Skype: lodhaaashish

**Comment by keshav-nangare** [comment]
Hi Luis,

We have tried WMS1.3 on windows environment. Also we tried with the
different WMS1.3 revision 1.13 and 1.12 and teamengine 4.3 version. It
works fine on Windows, it is not producing any error.

I have attached the logs with this email, which works fine without any
exception.

I will continue my work on .bat file.

Thanks and Regards,

Keshav Nangare
Mindstix Software Labs
http://www.mindstix.com

Email: keshav.nangare@mindstix.com
Phone: +91 8888176417
Skype: nangare.keshav

**Comment by bermud** [comment]
Let's add these to the integration testing scripts. 

Richard reported  that when running in Windows this  IUT: <http://cite.demo.opengeo.org:8080/geoserver_wms13/wms?service=wms&request=getcapabilities&version=1.3.0>
 
The interactive tests ran ok and then the test suite seemed to hang. I terminated the test run after 10 min, with the following results:
 
Passed: 59
 
Failed: 3
  * getcapabilities:style-legendurls (Exception in extension function java.lang.NullPointerException)
  * getcapabilities:metadataurls (Exception in extension function java.lang.NullPointerException)
  * getcapabilities:validate-using-schemaLocation (Exception in extension function java.lang.NullPointerException)
 
The session error log contains the stack traces. In all cases the root cause seems to be a NullPointerException that occurs when trying to load a classpath resource (the resource name is not logged).
 
```
Caused by: java.lang.NullPointerException
    at org.apache.catalina.loader.WebappClassLoader.getResourceAsStream(WebappClassLoader.java:1540)
    …
 ```
A TECore method appears not far down the call stack, but it’s not always the same one.

**Comment by rjmartell** [comment]
On a Windows Server 2012 R2 host I ran the test suite to completion against the geoserver implementation (with no failures). So my initial report can be disregarded--there is something amiss in my local workstation environment.

However, the report for the k2geospatial service could not be displayed due to a parse exception. The test run did appear to finish with an overall result = 5 (Inherited failure).

The response for the `getmap:invalid-crs` test contained a PNG image, not the expected service exception (the request set CrS="UndefinedCRS"). This test could be improved by first checking the content type header in the response for an acceptable XML media type.

**Comment by rjmartell** [comment]
I reported a new WMS issue: https://github.com/opengeospatial/ets-wms13/issues/20

**Comment by keshav-nangare** [comment]
We have tested the temengine 4.3 and WMS1.3 on following environment:- 
 
-Ubuntu:
 
Teamengine version:- 4.3 
WMS1.3 : revision-1.13 and revision-1.12 
OS Name: Ubuntu 12.04.1 LTS 
Tomcat version: Apache Tomcat/8.0.24
Java : - java version "1.7.0_55"
 -Java(TM) SE Runtime Environment (build 1.7.0_55-b13)
 -Java HotSpot(TM) 64-Bit Server VM (build 24.55-b03, mixed mode)

-Mac:

Teamengine version:- 4.3 
WMS1.3 :- revision-1.13 and revision-1.12 
OS Name:- "mac os x", version: "10.10.5"
Tomcat version:- Apache Tomcat/7.0.64
Java : - java version "1.7.0_79"

The above mentioned environment these version works fine without any exception.

**Comment by bermud** [comment]
@rjmartell, Thank you for making the improvement on the WMS 1.3 test, that might have caused this issue.
@keshav-nangare,  Thank you for verifying that TE 4.3 is OK. 
 We will close this issue now.
