### ISSUE TITLE
TE v4.2 installation fails on Windows Server 2012

### ISSUE THREAD

**Issue by sMorrone** [opengeospatial/teamengine#130]
please find below a screenshot of what I get when I try to install TE v4.2 on Windows Server 2012 environment - jdk1.8.0_60. Any idea of why it happens?

![image](https://cloud.githubusercontent.com/assets/13329248/10341465/2864201c-6d15-11e5-9d2f-24d9491bd5c1.png)

**Comment by rjmartell** [comment]
There was a known issue affecting that unit test (integration test, really) when building in a Windows environment. As a workaround, you can skip the unit tests by adding the `-DskipTests` option.

Also, JDK 8 is not yet officially supported.

**Comment by bermud** [comment]
It was fixed on 4.3. The original issue was reported #124.
