### ISSUE TITLE
Add REST API method to handle multipart POST request

### ISSUE THREAD

**Issue by bermud** [opengeospatial/teamengine#131]
Add a REST API handler (in teamengine-spi) for a POST Request where:
- content type = MULTIPART
- IUT = XML file to be tested
- SCH = Schematron

The XML and schematron can be passed as files in the POST body.

**Comment by bermud** [comment]
Related to this pull request https://github.com/opengeospatial/teamengine/pull/78. Changes should be provided as another pull request, only containing the related changes to this issue, and sync with master.

**Comment by rjmartell** [comment]
The actual media type is "multipart/form-data". See [RFC 7578](http://tools.ietf.org/html/rfc7578).
