### ISSUE TITLE
run integration testing for branch of fix/138-xsd11

### ISSUE THREAD

**Issue by bermud** [opengeospatial/teamengine#140]
Run integration testing for branch of fix/138-xsd11
https://github.com/opengeospatial/teamengine/tree/fix/138-xsd11
to verify that fix  #138 is not breaking any test.

**Comment by keshav-nangare** [comment]
I have executed the integration testing script for the branch  fix/138-xsd11 and its working fine,

Integration testing script contains the following test suites:
    1. CSW 2.0.2 (1.15-SNAPSHOT)
    2. WMS 1.3 (1.16-SNAPSHOT)
    3. WFS 2.0 (1.21-SNAPSHOT)
    4. GML 32 (1.23-SNAPSHOT)
    5.SOS1.0.0 (r1.14-SNAPSHOT)
Above test suites are working fine on this branch " fix/138-xsd11 "

Also I have executed the KML 2.2 (12-SNAPSHOT) test suite it is also working fine 
Capability URL: https://developers.google.com/kml/documentation/KML_Samples.kml
It is failing as expected, 3 test are failing .
