### ISSUE TITLE
Simplify the user interface when creating a new session

### ISSUE THREAD

**Issue by bermud** [opengeospatial/teamengine#142]
Related to createSession.jsp
- **Organization** should not appear. - provide in a configuration file the default, for example *OGC*
-  **Revision** should not appear. We are always using one. Can we hide this field?
- **Specification** should appear in alphabetical order
- **Select Profile(s):** should only appear when there are profiles
- **Select a test suite:** Shuld be capitalize, as the other titles

**Comment by keshav-nangare** [comment]
I have question regarding 2nd feature i.e. "Revision should not appear".

Should we hide it or show it (disabled state with default latest value) or you want to show a simple text which have the revision number?

**Comment by bermud** [comment]
Regarding second point. We should show the revision, but not allow the user to select it. Maybe as part of the specification string: WMS 1.3 (r 1.13)

**Comment by bermud** [comment]
Idea:
![pic 2016-01-13 at 9 17 28 am](https://cloud.githubusercontent.com/assets/3738898/12296565/81816bce-b9d6-11e5-865c-147e91ee5c52.jpg)

**Comment by keshav-nangare** [comment]
I have implemented the above idea the first drop-down contains the default Organization and second drop-down contains the standards, version and revision.

These changes is present in this branch "feature-issue-142"

**Comment by bermud** [comment]
I like these changes. Great!

**Comment by bermud** [comment]
@keshav-nangare, please test how hard will be to change the jmeter test script.

**Comment by bermud** [comment]
Maybe check in the main config for the first organization and used it as the default value in the form.

**Comment by keshav-nangare** [comment]
I have updated the Jmeter script as per our new implementation. I have updated the jmeter form page where the form values are submitted and removed the other form parameter that are not used.
This is fixed with this commit   69f015ce771e011e4307833fa66405d6fc8281b5

**Comment by bermud** [comment]
@keshav-nangare, great !

**Comment by bermud** [comment]
Please update the form, so it looks like this:

<img width="484" alt="select-session" src="https://cloud.githubusercontent.com/assets/3738898/13142694/cab372ea-d60c-11e5-9314-97c2faa9c670.png">

**Comment by bermud** [comment]
Fixed with 90c71a7d0c9db94acaa2224b61e01f0bf61dd0a9
