### ISSUE TITLE
 Failed to create coordinate transformer

### ISSUE THREAD

**Issue by sMorrone** [opengeospatial/teamengine#143]
I installed GML Test Suite rel 1.22 in TEAM engine v 4.4 - Windows Server 2012 R2 environment.
I get different test results if I test the same GML file :

•	at  http://cite.opengeospatial.org/teamengine/  (test result = 'passed')
•	at my server installation via command line (test result= 'passed')
•	at my server installation via web application (test result= 'failed' with message :”Test method        validSurfaceOrientation: Failed to create coordinate transformer”).
 As far as I can understand from tomcat console (see attached screenshots) maybe issue is due to the fact that EPSG_VERSIONHISTORY table/view does not exist?
I built the teamengine.war file running the modified maven profile as suggested in the tutorial and also extracted contents of 'teamengine-common-libs.zip' into c:\CATALINA_BASE\lib.
![image](https://cloud.githubusercontent.com/assets/13329248/12172616/50d6de42-b552-11e5-8211-1c2397b25b53.png)

**Comment by bermud** [comment]
The derby database contains the EPSG codes.

For the web application you need to specify the directory of the derby database
## for example catalina options in unix:
export CATALINA_OPTS='-server -Xmx1024m -XX:MaxPermSize=128m -DTE_BASE=$TE_BASE -Dderby.system.home=$catalina_base/derby_data'

And in catalina_base you should have the derby-10.10.2.0.jar

**Comment by sMorrone** [comment]
I already have the following line in my setenv.bat
"
set CATALINA_OPTS=-server -Xmx1024m -XX:MaxPermSize=128m -DTE_BASE=C:\TE_BASE -Dderby.system.home=C:\CATALINA_BASE\derby_data".
Here follows the derby.log file I get when I run my test:
"Booting Derby version The Apache Software Foundation - Apache Derby - 10.10.2.0 - (1582446): instance a816c00e-0152-1cbe-c2a1-00003c4a14ad 
on database directory C:\CATALINA_BASE\derby_data\EPSG\7.09 with class loader org.apache.catalina.loader.StandardClassLoader@6de0e650 
Loaded from file:/C:/CATALINA_BASE/lib/derby-10.10.2.0.jar
java.vendor=Oracle Corporation
java.runtime.version=1.7.0_67-b01
user.dir=C:\apache-tomcat-7.0.52\bin
os.name=Windows Server 2012 R2
os.arch=amd64
os.version=6.3
derby.system.home=C:\CATALINA_BASE\derby_data
Database Class Loader started - derby.database.classpath=''
"
Maybe I need to set also the derby.database.classpath?  in this case which would be the correct value?

**Comment by bermud** [comment]
@rjmartell, please provide further guidance.

**Comment by rjmartell** [comment]
It looks like the EPSG database exists (in derby_data\EPSG\7.09) but is empty. Is this a new installation? Can the Tomcat user write to `derby.system.home`?

If it worked from the command-line, there should be another instance of the derby database in your user profile at %APPDATA%\Geotoolkit.org. As a workaround you can try copying this to `derby.system.home`.

**Comment by sMorrone** [comment]
Workaround works !
Anyway, just for mention, the database in derby_data\EPSG\7.09 is not empty and Tomcat user can write to derby.system.home. Only difference I noticed between the two instances of the derby database is the number of  elements  in the seg0  folder (73 in derby_data / 170 in Geotoolkit.org).

**Comment by rjmartell** [comment]
See opengeospatial/ets-gml32/issues/18
