### ISSUE TITLE
Update instructions explaining how the default organization gets updated in the form

### ISSUE THREAD

**Issue by bermud** [opengeospatial/teamengine#146]
related to #142

**Comment by keshav-nangare** [comment]
If we have select any default organization in the drop-down list then following changes are required:
-  1 We have to add the elements in config.xml file "&lt;default&gt;true&lt;/default&gt;" after the <name> element.
         <br />    e.g. add this element into csw/config.xml or any other test suite config file instead of the main config.xml (TE_BASE/config.xml), because this main config.xml file will change if any other config.xml file are changed(csw/config.xml)  or if we restart or tomcat then it will update the main config file.

-  2 If default organization attribute is not provided then by default "OGC" organization option will appear in the drop-down list.

**Comment by bermud** [comment]
Hi Keshav. I don't like this solution. Let's make it simpler. Just pick the first organization  that is available on the main config file. We don't need to add anything anywhere.

**Comment by bermud** [comment]
Have you updated the solution? I would like to test locally before we release at the end of the month. Thakn you!

**Comment by keshav-nangare** [comment]
I will update this solution tomorrow.
I have question regarding this, by default the first organization is the "Example.net" present in the main config file then it will be the default organization in the drop-down list.

**Comment by bermud** [comment]
Yes. This is correct.

**Comment by keshav-nangare** [comment]
As per the suggestion I have updated solution.

This changes are present in the "feature-issue-142" branch.
