### ISSUE TITLE
dates in sessions

### ISSUE THREAD

**Issue by bermud** [opengeospatial/teamengine#148]
Session dates are important to understand better user activity.

- Currently, the date that we associate to a session is the date of the file of the session.xml of folder session
- The date when a session was run must be logged. 
- Only some  sessions have the session.xml with a  date. The date is not written in ISO format. 
- Other sessions don't have a date.

See for example:
```
<session id="s0150" sourcesId="OGC_Web Map Service (WMS)_1.1.1_1.12" date="2016/02/24  04:36:44"  >
<suite>{http://www.opengis.net/wms}main_wms</suite>
<description>Test WMS 1.1</description>
</session>

```

Need to: 
- find why some sessions.xml don't have a date
- improve TE so the date gets logged in ISO 8601 format. For example; 2016-02-23T22:49:05Z
- create a script to update the dates in the session.xml

**Comment by keshav-nangare** [comment]
Updated the session with this commit 756fc6a5434f33d37240e80c02e6cf1a6404a099

**Comment by bermud** [comment]
Can you generate a script to fix the  previous sessions?
- finds an old date then fix it
- not have date - add the date of the creation of the file

**Comment by keshav-nangare** [comment]
I have created the script to fix the previous session.

This script is present in the repository "teamengine-statistics/feature-issue3".

**Comment by bermud** [comment]
I see now the project is in maven. Great! 

How do I run the script?

Please use this package: 
org.opengis.te.stats

Change the file name to:
StatisticsCrreator.java

Thank you!


Luis Bermudez, Ph.D.
Executive Director Compliance and E-Learning
Open Geospatial Consortium (OGC)
Skype: bermudez_luis
Twitter: @berdez
Tel: +1 301 760 7323
https://www.linkedin.com/in/bermudez

The OGC: Making Location Count

**Comment by keshav-nangare** [comment]
We can execute this script in two way:
- By using Eclipse:
 - In Eclipse we have to add the command line argument into "Run Configuration" and just Run the script. It will show the result in console.

- By using Command-line:
 - e.g. mvn exec:java -Dexec.mainClass="org.opengis.te.stats.AdminLogCreator" -Dexec.args="/home/admin/TE_BASE/users/"
