### ISSUE TITLE
List in form is not appearing in alphabetical order

### ISSUE THREAD

**Issue by bermud** [opengeospatial/teamengine#149]
List in the form is not appeargin in alphabetical orer please - fix
See example:

<img width="301" alt="dropdown" src="https://cloud.githubusercontent.com/assets/3738898/13604140/5eea11ba-e50f-11e5-809b-1d0c92564f2e.png">

**Comment by keshav-nangare** [comment]
I have fixed this issue, now the list will appear in alphabetical order.

Fixed with this commit 445605abdb50f5abdce6118a33cac292f52c818c
