### ISSUE TITLE
Change storing of password mechanism

### ISSUE THREAD

**Issue by bermud** [opengeospatial/teamengine#150]
Currently the passwords are stored in a file under the user's folder main xml. Provide an additional mechanism to deal with authentication or encrypting of the passwords

**Comment by rjmartell** [comment]
User passwords are typically hashed using a suitable algorithm (e.g. SHA-1). Doing something as straightforward as this may suffice, even if it is in principle susceptible to dictionary and/or brute-force attacks.

Hashing with a variable cryptographic salt that is unique per-user and per-password offers a stronger solution, but it may not be warranted in this case (i.e. relative risk of disclosing test run results).

**Comment by bermud** [comment]
We decided that using hashed passwords stored in the current file system was the way to move forward.

**Comment by rjmartell** [comment]
Here's a simple open-source, peer-reviewed library that uses the PBKDF2 algorithm to protect passwords: <https://github.com/defuse/password-hashing>.

The license is derived form the [BSD 2-Clause License](https://opensource.org/licenses/BSD-2-Clause).

**Comment by rjmartell** [comment]
Add a custom `ServletContextListener` to automatically replace existing clear text passwords with hash values when the Servlet container is (re)started. Just check the first few users to determine if this was already done.
