### ISSUE TITLE
Upgrade to JAX-RS 2.0

### ISSUE THREAD

**Issue by rjmartell** [opengeospatial/teamengine#151]
The `spi` module uses Jersey 1.19, which is the reference implementation of JAX-RS 1.1. This was superseded by JAX-RS 2.0 (Jersey 2.x) in 2013, which was also incorporated within the JEE 7 technology stack.

New API capabilities warrant the upgrade: Client API, async, filters and handlers, etc. This will also facilitate the realization of a separate [test execution service](/opengeospatial/teamengine/wiki/Architectural-enhancements-%28teamengine-v5%29#tes).

**Comment by keshav-nangare** [comment]
@dstenger 

Following are the changes to upgrade JAX-RS:

1. JAX-RS has the latest version 2.1.5
2. Jersey has the latest version 2.28
3. Updated the web.xml accordingly
4. Updated the pom dependencies.
5. Updated the assembly descriptor & packaging should be done according to new changes.
6. The above changes are working with the Tomcat 7.0.92

I have updated the teamengine with JAX-RS and Jersey implementation to the latest version. The test suite is failed to execute with the latest changes. Also, we need to update the test suite which is having Jersey dependencies.

I have tested the teamengine changes with test suite ets-gml32 and got the error ClassDefinationNotFound. I have updated the test suite and it worked fine with teamengine latest changes.

**Comment by keshav-nangare** [comment]
Fixed with this PR #389

**Comment by dstenger** [comment]
Caution: All test suites must be updated. Otherwise, they won't run on TEAM Engine.

**Comment by lgoltz** [comment]
> Caution: All test suites must be updated. Otherwise, they won't run on TEAM Engine.

@keshav-nangare: Can you check if or which test suites are affected?

**Comment by lgoltz** [comment]
> > Caution: All test suites must be updated. Otherwise, they won't run on TEAM Engine.
> 
> @keshav-nangare: Can you check if or which test suites are affected?

The following grep show as all affected test suites (at least the one I've checked out):

```
lyn@cryptus:~/checkouts/opengeospatial$ grep -r com.sun.jersey | grep pom
ets-gpkg10/pom.xml:      <groupId>com.sun.jersey</groupId>
ets-common/pom.xml:        <groupId>com.sun.jersey</groupId>
ets-owc10/pom.xml:      <groupId>com.sun.jersey</groupId>
ets-cat30/pom.xml:      <groupId>com.sun.jersey</groupId>
ets-gml32/pom.xml:      <groupId>com.sun.jersey</groupId>
ets-kml22/pom.xml:      <groupId>com.sun.jersey</groupId>
ets-om20/pom.xml:      <groupId>com.sun.jersey</groupId>
ets-dgiwg-core/pom.xml:        <groupId>com.sun.jersey</groupId>
ets-cat20-dgiwg10/pom.xml:      <groupId>com.sun.jersey</groupId>
ets-sensorml20/pom.xml:      <groupId>com.sun.jersey</groupId>
ets-19139/pom.xml:            <groupId>com.sun.jersey</groupId>
ets-archetype-testng/src/main/resources/archetype-resources/pom.xml:      <groupId>com.sun.jersey</groupId>
ets-wfs20-nsg/pom.xml:      <groupId>com.sun.jersey</groupId>
ets-wms13-nsg/pom.xml:      <groupId>com.sun.jersey</groupId>
ets-wfs30/pom.xml:      <groupId>com.sun.jersey</groupId>
ets-kml2/pom.xml:      <groupId>com.sun.jersey</groupId>
ets-gpkg12/pom.xml:      <groupId>com.sun.jersey</groupId>
ets-security-client10/pom.xml:      <groupId>com.sun.jersey</groupId>
ets-gmljpx20/pom.xml:			<groupId>com.sun.jersey</groupId>
ets-swecommon20/pom.xml:      <groupId>com.sun.jersey</groupId>
ets-wmts10-nsg/pom.xml:      <groupId>com.sun.jersey</groupId>
```

**Comment by keshav-nangare** [comment]
@lgoltz 

I have tested these changes with ets-gml32 and added a fix for ets as well.
Here is the issue: https://github.com/opengeospatial/ets-gml32/issues/38

**Comment by dstenger** [comment]
TEAM Engine was updated to JAX-RS 3.1 in https://github.com/opengeospatial/teamengine/issues/556.
Thus, this issue is invalid.
