### ISSUE TITLE
remove branches that are not needed any more

### ISSUE THREAD

**Issue by bermud** [opengeospatial/teamengine#157]
We have these branches. Please advise which ones we should keep.
 
  remotes/origin/HEAD -> origin/master
  remotes/origin/beta-3.0-fix
  remotes/origin/feature-CTL-console-reporting
  remotes/origin/feature-POST-API
  remotes/origin/feature-WMSClientIssue14
  remotes/origin/feature-advanceTestNg
  remotes/origin/feature-client-test-enhancement
  remotes/origin/feature-configxml-issue
  remotes/origin/feature-issue-141
  remotes/origin/feature-issue-142
  remotes/origin/feature-issue-148
  remotes/origin/feature-issue-149
  remotes/origin/feature-issue100
  remotes/origin/feature-issue102
  remotes/origin/feature-issue17-WMSClient
  remotes/origin/feature-issue38
  remotes/origin/feature-issue42
  remotes/origin/feature-issue92
  remotes/origin/feature-issue95
  remotes/origin/feature-issue98
  remotes/origin/feature-junitForCtl
  remotes/origin/feature-openedFileIssue
  remotes/origin/feature-testreport
  remotes/origin/feature-wms-client
  remotes/origin/gh-pages
  remotes/origin/master
  remotes/origin/new-te
  remotes/origin/ogc_ctl_scripts
  remotes/origin/ows4
  remotes/origin/ows9
  remotes/origin/r3.0p
  remotes/origin/sos
  remotes/origin/team2
  remotes/origin/telb4
  remotes/origin/upgrade/32-saxon-he
  remotes/origin/wmts_pd

**Comment by keshav-nangare** [comment]
Deleted the branches that are no longer needed.
