### ISSUE TITLE
Unprotected transport of user credentials

### ISSUE THREAD

**Issue by rjmartell** [opengeospatial/teamengine#159]
User credentials are unprotected when logging into the web application. The deployment descriptor specifies form-based authentication but there is no user data constraint.

A secure connection (i.e. TLS) should be used. See also #150.

**Comment by rjmartell** [comment]
We may want to document two options for configuring TLS in the user guide:

1. Stand-alone Tomcat container: https://tomcat.apache.org/tomcat-8.0-doc/ssl-howto.html
2. Access via proxy server (e.g. [Apache HTTPD](https://httpd.apache.org/)) for enhanced security, load balancing

**Comment by ghobona** [comment]
@dstenger This issue was addressed by moving to HTTPS/TLS.

The issue can be closed.
