### ISSUE TITLE
Received error executing mvn install

### ISSUE THREAD

**Issue by CLEAOSBORNE** [opengeospatial/teamengine#160]
[clea.txt](https://github.com/opengeospatial/teamengine/files/197575/clea.txt)
Test execution report
csw:Main

Overall result: Failed
Executed tests
test: csw:Main
session: 328aba32-9fd8-493e-aedc-0864c40c4c7f

Assertion: The implementation under test minimally conforms to the CSW part (Clause 10) of Catalogue 2.0.2 (OGC 07-006r1).

Test result: Failed

Submitted request:

Method=
        GETURL=
        file://C:\repo\teamengine\teamengine-web\src\main\scripts\server\csw.xmlParameters: 
        NONE.

Request body: empty.

**Comment by CLEAOSBORNE** [comment]
Deleted repo directory, re-cloned and re-executed mvn install successfully.  Issue resolved, thanks!

**Comment by bermud** [comment]
@CLEAOSBORNE, I'm glad you solved the issue.
