### ISSUE TITLE
Unique session numbers

### ISSUE THREAD

**Issue by bermud** [opengeospatial/teamengine#168]
Consider changing the session numbering. The session numbers should be unique for the whole installation, not per user. A REST API can then be created to easily extract the results of the tests.

**Comment by rjmartell** [comment]
TestNG test runs are identified by UUID. In fact, all current implementations of TestRunExecutor (TestNGExecutor, CtlExecutor) do this.

**Comment by dstenger** [comment]
@bermud Can you please clarify the aim of this issue?

**Comment by dstenger** [comment]
@bermud Specification of REST interface is created in #238. Is this issue obsolete then?

**Comment by cmheazel** [comment]
For issue 292 we will replace the snnnn formatted session ids with UUID session ids.  We will also include enforcement of this convention.  The primary purpose of this change is to prevent folks from using session ids to create subversive file paths (we have to have some convention to validate against).  An additional advantage of UUIDs is that they are globally unique.

**Comment by ghobona** [comment]
This issue has been overtaken by events.
