### ISSUE TITLE
What is the recommended approach to upgrading a TeamEngine build?

### ISSUE THREAD

**Issue by CLEAOSBORNE** [opengeospatial/teamengine#169]
What is the best approach to upgrading TeamEngine to the latest build?  I have an older build from 3 months ago and would like to upgrade to the latest software build.  Should I start a new fresh build or what is the best way to upgrade?

**Comment by bermud** [comment]
I always do a fresh build.

The instructions are here: http://opengeospatial.github.io/teamengine/installation.html
I use this script to quickly build TEAM Engine:
https://github.com/opengeospatial/teamengine-builder/blob/master/build_te.sh

And to install a tests I run this script from the test directory:
https://github.com/opengeospatial/teamengine-builder/blob/master/build_test.sh

**Comment by CLEAOSBORNE** [comment]
@bermud   I ended up building a new instance.  Thanks for the links, I will try them on the next release.
