### ISSUE TITLE
EARL report does not contain the Test information.

### ISSUE THREAD

**Issue by keshav-nangare** [opengeospatial/teamengine#172]
Following Test information is require in HTML report:

1. Test Name:
2. Time: 
3. Test Artifact:
4.Over all Result: 

We have to add this information in the EARL report.

**Comment by rjmartell** [comment]
The latest release (4.7.1) now adds a cite:TestRun resource to the EARL results that provides summary information about the test run. For example:

```xml
<cite:TestRun>
    <dct:extent rdf:datatype="http://www.w3.org/2001/XMLSchema#duration">PT2M26.453S</dct:extent>
    <cite:testsSkipped rdf:datatype="http://www.w3.org/2001/XMLSchema#int">7</cite:testsSkipped>
    <cite:testsFailed rdf:datatype="http://www.w3.org/2001/XMLSchema#int">19</cite:testsFailed>
    <cite:testsPassed rdf:datatype="http://www.w3.org/2001/XMLSchema#int">171</cite:testsPassed>
    <dct:identifier>f9409eb2-457e-4e39-9624-05be82aa3f63</dct:identifier>
    <dct:created>2016-07-12T22:38:43.378Z</dct:created>
    <dct:title>wfs20-1.23-SNAPSHOT</dct:title>
  </cite:TestRun>
```

**Comment by keshav-nangare** [comment]
One element is missing in above information i.e. "Test Artifact:".

The "Test Artifact:" is the input URL to Test.

E.G. `Test Artifact:**INPUT: http://localhost:8080/teamengine/test-input.xml`

**Comment by bermud** [comment]
@keshav-nangare, thank you for looking into it. Please @rjmartell make changes to include the artifact that was tested.

**Comment by rjmartell** [comment]
The test run arguments could be added in a container such as rdf:Bag (order doesn't matter). Another extension property (`cite:arguments`) would be needed, since EARL doesn't offer anything like this,

**Comment by rjmartell** [comment]
We end up with this in the EARL report:

```
<cite:TestRun>
  <cite:inputs>
    <rdf:Bag>
      <rdf:li rdf:parseType="Resource">
        <dct:description>http://ogctestbed12.lat-lon.de/deegree/services/wfs?service=WFS&amp;request=GetCapabilities</dct:description>
        <dct:title>wfs</dct:title>
      </rdf:li>
      <rdf:li rdf:parseType="Resource">
        <dct:description>http://ogctestbed12.lat-lon.de/deegree/services/wfs?service=WFS&amp;version=2.0.0&amp;request=DescribeFeatureType</dct:description>
        <dct:title>xsd</dct:title>
      </rdf:li>
    </rdf:Bag>
  </cite:inputs>
  ...
```
