### ISSUE TITLE
How to upload and test terabytes of data in the case of Compliance test for OGC CDB Candidate Standard?

### ISSUE THREAD

**Issue by sarasaeedi** [opengeospatial/teamengine#180]
In the compliance test for OGC CDB Candidate Standard, we need to check the folder hierarchy and schema of a file-based DB. For this purpose, we require accessing the name and folder hierarchy of a CDB which can be done through one of the three methods:
1. The user needs to upload and sync the CDB directory to an FTP server (or other servers) and provides authentication information to the web application so that the web application directly accesses the CDB directories
2. Write a lightweight executable file (CDBCapture) that can be downloaded from the website. Run the file before the test & creates a small manifest file (which has all the folder names and hierarchy) that can be easily accessed by the web application.
3. Write an executable test (CDBChecker) that can be downloaded from the website. This file needs to be run and creates a test log file on the local machine that can be easily uploaded to the OGC website.

The first method is not applicable because of the volume of the data and privacy of the data. However, I was wondering which of the second and third method is better for our case, or if there is any other method which can be used. @bermud

**Comment by bermud** [comment]
@sarasaeedi, thank you for providing this issue. 

I think FTP will be the simplest, but we can think of providing other solutions via APIs that will allow you to get programmatically the list of files form a directory (e.g. dropbox or google drive).

I'm not sure about your comment:

> The first method is not applicable because of the volume of the data and privacy of the data

Maybe:
- Make a public FTP to put your files
- Make the parent directory readable (so you can list the files under the directory), 
- Make non readable the files you want to protect, so they cannot be downloaded.

Making scripts that the testers can run on their machines to help save the current permission and then set these permission will be good as well.

@keshav-nangare, I think we had an idea before about a similar functionality, where we wanted to test all the metadata instances in a folder. Do you have any suggestions?

@rjmartell, what would you recommend?

**Comment by bermud** [comment]
@sarasaeedi,

Let's say we have all the data in Amazon S3, what are we testing on the data or the structure of the directory? I'm not very familiar with the current status of CDB.

If you have a list of files under a directory, what would you do with that list?

**Comment by sarasaeedi** [comment]
@bermud 

We are exploring a directory and all its subdirectories to check if certain files and directories exist.  The dataset is big (TBs of copyrighted satellite imageries) and we can't ask the user to upload it. 

Our suggestion was to write a light-weight desktop application that goes though the directory and saves the structure into a file and ask the user to upload that file. This application will be made available to the user on the website.

**Comment by rjmartell** [comment]
I assume the relevant conformance requirements are those in Annex A of OGC 15-113. Is there a particular subset of immediate interest here? For example, the platform requirements. Given that it doesn't seem practicable to submit an entire CDB data store over a network connection, local validation is preferable; that is, the input argument is a 'file://' URI that refers to the root CDB directory. This would require executing the test suite either as a command-line app or from a local teamengine installation.

Perhaps in some cases it might make sense to enable HTTP access to a file system such that a data store can be inspected over the course of a test run--retrieval then occurs in a more selective, piecemeal fashion rather than all at once. Or use a remote file system protocol like SFTP instead of HTTP.

**Comment by liangsteve** [comment]
@rjmartell  If we go with the local teamengine installation or a command-line app, what does OGC know it pass the test as the test session status (start/end) is in the local teamengine?  Is the local teamengine going to send the result to the official teamengine?

**Comment by ghobona** [comment]
The infrastructure does not support upload and testing of terabytes of data. If the purpose is for certification, then we recommend testing a smaller CDB archive.
