### ISSUE TITLE
[Non-Exprience]How to understand the Test Result from TeamEngine?

### ISSUE THREAD

**Issue by bangph** [opengeospatial/teamengine#194]
Hello,
We have a WMS service and want to test to make sure it followed OGC compliance. However, I don't understand the test results from TeamEngine, I have few questions as I have no experience, please help:
+ Do I need to understand the CTL and test cases from test suite to know what it want to test (i.e: the query to our web service endpoint) ?
+ Do I need to import sample data to our server before running test OGC online ?
+ I think OGC TeamEngine use some XML validator to validate the output and the expected output to determine which test is pass or fail. But it is quite hard to understand why it was failed. It would be better if I could find some information about solving this problem (if any).

Thanks,

**Comment by bermud** [comment]
Dear Bangh, If you have questions regarding the results please send the results and questions to the CITE forum. Experts will be able to assist you. http://cite.opengeospatial.org/forum. 

You do not need to know CTL.

Here are the requirements for WMS 1.3
http://cite.opengeospatial.org/teamengine/about/wms/1.3.0/site/
You need test data.

Here is the GitHub page for the test: https://github.com/opengeospatial/ets-wms13, where you can look at any previous issue discussions.
