### ISSUE TITLE
Error when deploy Team-Engine on Tomcat

### ISSUE THREAD

**Issue by bangph** [opengeospatial/teamengine#196]
Hello,

I want to build a local TeamEngine and test it with our local service (e.g: localhost:8080/service instead of public service with domain). I built TeamEngine by using this tutorial http://opengeospatial.github.io/teamengine/installation.html and it can generate a WAR file (teamengine/teamengine-web/target/teamengine.war). And when I deploy it to Tomcat, it has this error (although I already set the TE_BASE environment variable in the Centos globally 
```
echo "export TE_BASE=/home/user/teamengine/" >> ~/.bashrc
source ~/.bashrc
```

and reset Tomcat).

```
java.lang.IllegalArgumentException: The alias location '${TE_BASE}/resources/docs' does not exist
	at org.apache.naming.resources.BaseDirContext.setAliases(BaseDirContext.java:268)
	at org.apache.catalina.core.StandardContext.setResources(StandardContext.java:2660)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5409)
```

Checking the TE_BASE directory, I also did not see the resources folder? Please help with this.

Thanks,

**Comment by bangph** [comment]
Sorry, looks like I missed this step from the tutorial link:

Create the TE_BASE directory (e.g. /srv/teamengine) and unpack the contents of the teamengine-console-\${project.version}-base archive into this location; make sure that users (including the Tomcat user) have write access. The structure of the TE_BASE directory is shown below.

I will do this step and see it can work.

**Comment by bangph** [comment]
I have to modify teamengine-web/src/main/webapp/META-INF/context.xml and replaced all {TE_BASE} with the absolute path.

And build teamengine-web with

`mvn package -P ogc.cite -Dets-resources-version=16.02.23`

and add the jar from teamengine-realm to teamengine.war (/WEB-INF/lib/) manually.

So after all of these steps, I could see a login and register page "Enter your username and password:". I can register account and it can create authentication file in $TE_BASE/users/. But when I try to login with the registered account, it just said: 

"The username and/or password did not match. Please try again."

I tried with many users and correct password but it does not allow to login. It is really frustrating.

**Comment by bangph** [comment]
so I can pass some errors by adding the jar in /WEB-INF/lib, but there is one error from teamengine-realm that now I had (I tried to add this jar from teamengine-realm to /WEB-INF/lib, but it does not work).
org.xml.sax.SAXParseException; systemId: jar:file:/home/user/Tomcat/webapps/teamengine.war! !/META-INF/context.xml; lineNumber: 15; columnNumber: 112; Error at (15, 112) : com.occamlab.te.realm.PBKDF2Realm
	at org.apache.tomcat.util.digester.Digester.createSAXException(Digester.java:2705)
	at org.apache.tomcat.util.digester.Digester.createSAXException(Digester.java:2737)
	at org.apache.tomcat.util.digester.Digester.startElement(Digester.java:1285)
`	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: com.occamlab.te.realm.PBKDF2Realm
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)`

**Comment by bermud** [comment]
I recommend using this easier tutorial. There is a link from the page you were looking at
https://github.com/opengeospatial/teamengine-builder. 

It takes care of creating TE_BASE, setting up the jars, etc.

We will check in detail the issues you are reporting and will get back to you soon. Thank you for reporting.

**Comment by bangph** [comment]
Thanks Luis for your reply. It seems work now (although I've opened some small issues on this repository).

I have other question as you marked this thread as "question", when I test a public domain with OGC TeamEngine via: http://cite.opengeospatial.org/te2 the speed is very fast (under 1' for WCS 2.0.1 CORE) but in my localhost:8080/teamengine, it took like 20 minute and still running).

Do I have to increase something in local Tomcat to speed it up? 

Thanks.

**Comment by bermud** [comment]
Great that you have been able to install it. At the public OGC Server we use -Xmx1536m. I agree 20 minutes is too much.

**Comment by bangph** [comment]
thanks for your help,  please continue with other issues.

**Comment by Abouzeid** [comment]
@bangph  I am encountering the same problem of 

"The username and/or password did not match. Please try again."
I tried with many users and correct password but it does not allow to login.

Could you please tell us how did you solve it?

**Comment by bangph** [comment]
@Abouzeid 
Please follow Luiz's suggestion to use https://github.com/opengeospatial/teamengine-builder
I don't recall this problem in detail as it was ~ 2 years ago.

**Comment by Abouzeid** [comment]
Got it. 
Thank you for your consideration.
