### ISSUE TITLE
TeamEngine  finished WCS2.0 test suite  and have error in XML when creating report

### ISSUE THREAD

**Issue by bangph** [opengeospatial/teamengine#197]
I used TeamEngine Builder (4.10) and run test suite WCS 2.0.1, it finished and when it tried to create the report log, it has these error: 

HTTP Status 500 - javax.servlet.ServletException: net.sf.saxon.trans.XPathException: org.xml.sax.SAXParseException; lineNumber: 162; columnNumber: 656; An invalid XML character (Unicode: 0xc) was found in the element content of the document.

type Exception report

message javax.servlet.ServletException: net.sf.saxon.trans.XPathException: org.xml.sax.SAXParseException; lineNumber: 162; columnNumber: 656; An invalid XML character (Unicode: 0xc) was found in the element content of the document.

description The server encountered an internal error that prevented it from fulfilling this request.

exception

org.apache.jasper.JasperException: javax.servlet.ServletException: net.sf.saxon.trans.XPathException: org.xml.sax.SAXParseException; lineNumber: 162; columnNumber: 656; An invalid XML character (Unicode: 0xc) was found in the element content of the document.
	org.apache.jasper.servlet.JspServletWrapper.handleJspException(JspServletWrapper.java:561)
	org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:462)
	org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:395)
	org.apache.jasper.servlet.JspServlet.service(JspServlet.java:339)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)

root cause

javax.servlet.ServletException: net.sf.saxon.trans.XPathException: org.xml.sax.SAXParseException; lineNumber: 162; columnNumber: 656; An invalid XML character (Unicode: 0xc) was found in the element content of the document.
	org.apache.jasper.runtime.PageContextImpl.doHandlePageException(PageContextImpl.java:916)
	org.apache.jasper.runtime.PageContextImpl.handlePageException(PageContextImpl.java:845)
	org.apache.jsp.viewSessionLog_jsp._jspService(viewSessionLog_jsp.java:375)
	org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:439)
	org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:395)
	org.apache.jasper.servlet.JspServlet.service(JspServlet.java:339)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)

root cause

net.sf.saxon.trans.XPathException: org.xml.sax.SAXParseException; lineNumber: 162; columnNumber: 656; An invalid XML character (Unicode: 0xc) was found in the element content of the document.
	net.sf.saxon.event.Sender.sendSAXSource(Sender.java:379)
	net.sf.saxon.event.Sender.send(Sender.java:185)
	net.sf.saxon.IdentityTransformer.transform(IdentityTransformer.java:29)
	com.occamlab.te.util.LogUtils.readLog(LogUtils.java:122)
	com.occamlab.te.util.LogUtils.makeTestListElement(LogUtils.java:213)
	com.occamlab.te.util.LogUtils.makeTestListElement(LogUtils.java:250)
	com.occamlab.te.util.LogUtils.makeTestListElement(LogUtils.java:250)
	com.occamlab.te.util.LogUtils.makeTestListElement(LogUtils.java:250)
	com.occamlab.te.util.LogUtils.makeTestListElement(LogUtils.java:250)
	com.occamlab.te.util.LogUtils.makeTestList(LogUtils.java:310)
	com.occamlab.te.util.LogUtils.makeTestList(LogUtils.java:342)
	com.occamlab.te.ViewLog.view_log(ViewLog.java:113)
	com.occamlab.te.ViewLog.view_log(ViewLog.java:61)
	org.apache.jsp.viewSessionLog_jsp._jspService(viewSessionLog_jsp.java:270)
	org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:439)
	org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:395)
	org.apache.jasper.servlet.JspServlet.service(JspServlet.java:339)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)

root cause

org.xml.sax.SAXParseException; lineNumber: 162; columnNumber: 656; An invalid XML character (Unicode: 0xc) was found in the element content of the document.
	com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203)
	com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:177)
	com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:441)
	com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:368)
	com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1436)
	com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2927)
	com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
	com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:117)
	com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
	com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
	com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
	com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:649)
	net.sf.saxon.event.Sender.sendSAXSource(Sender.java:371)
	net.sf.saxon.event.Sender.send(Sender.java:185)
	net.sf.saxon.IdentityTransformer.transform(IdentityTransformer.java:29)
	com.occamlab.te.util.LogUtils.readLog(LogUtils.java:122)
	com.occamlab.te.util.LogUtils.makeTestListElement(LogUtils.java:213)
	com.occamlab.te.util.LogUtils.makeTestListElement(LogUtils.java:250)
	com.occamlab.te.util.LogUtils.makeTestListElement(LogUtils.java:250)
	com.occamlab.te.util.LogUtils.makeTestListElement(LogUtils.java:250)
	com.occamlab.te.util.LogUtils.makeTestListElement(LogUtils.java:250)
	com.occamlab.te.util.LogUtils.makeTestList(LogUtils.java:310)
	com.occamlab.te.util.LogUtils.makeTestList(LogUtils.java:342)
	com.occamlab.te.ViewLog.view_log(ViewLog.java:113)
	com.occamlab.te.ViewLog.view_log(ViewLog.java:61)
	org.apache.jsp.viewSessionLog_jsp._jspService(viewSessionLog_jsp.java:270)
	org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:439)
	org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:395)
	org.apache.jasper.servlet.JspServlet.service(JspServlet.java:339)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)

**Comment by bangph** [comment]
this problem happens on cite test as well

`HTTP Status 500 - javax.servlet.ServletException: net.sf.saxon.trans.XPathException: org.xml.sax.SAXParseException; lineNumber: 161; columnNumber: 754; An invalid XML character (Unicode: 0xc) was found in the element content of the document.

type Exception report

message javax.servlet.ServletException: net.sf.saxon.trans.XPathException: org.xml.sax.SAXParseException; lineNumber: 161; columnNumber: 754; An invalid XML character (Unicode: 0xc) was found in the element content of the document.`

**Comment by bangph** [comment]
I  have to test few test cases each time from the test suite and find the error is due (I don't think it is from our server as other tests can pass and don't generate error, the offending test case is this test case: Test wcs2:get-kvp-core-req28 ).

**Comment by bangph** [comment]
the problem is due to when GetCapabilities, out server will return 

<wcs:formatSupported>image/jp2</wcs:formatSupported> as the first element and that lead to test case 28 will request &format=image/jp2 which return binary characters and TeamEngine cannot parse it.

**Comment by bermud** [comment]
@keshav-nangare, please check that we have captured and fixed this issue in the proper tracker https://github.com/opengeospatial/ets-wcs20
