### ISSUE TITLE
OGC Cite TeamEngine error in version 4.9  ( Exception in extension function java.lang.reflect.InvocationTargetException)

### ISSUE THREAD

**Issue by bangph** [opengeospatial/teamengine#198]
I have some strange errors when test with OGC Cite version 4.9, meanwhile I used TeamEngine local version 4.10 and don't have this error.

Test wcs2:soap-core-req1-9 type Mandatory default result Passed (s0061/d1e112_1/d1e235_1/d4464e64_1/d1231e42_1)

Assertion: req1-9:For all coverages offered by the server under test, test coverage structure, service parameters, and service metatada via SOAP GetCapabilities, DescribeCoverage and GetCoverage operations. Verify the responses contain the required information.

Message d1231e859_1:
   [MESSAGE] Test coverage test_mean_summer_airtemp

Message d1231e859_2:
   [MESSAGE] Test coverage test_mean_summer_airtemp_repeat

Message d1231e1017_1:
   [MESSAGE] Test operation GetCapabilities

Error in call to extension function {public org.w3c.dom.NodeList com.occamlab.te.TECore.soap_request(org.w3c.dom.Document,java.lang.String) throws java.lang.Throwable}: Exception in extension function java.lang.reflect.InvocationTargetException
Result: Failed

**Comment by keshav-nangare** [comment]
@bangph  Thank you for reporting this issue.

Can please provide the Capability URL that you have tested, so I can reproduce it.

**Comment by bangph** [comment]
sorry this problem happens few times then I stop TeamEngine from Tomcat and it does not happens anymore.

here is our Endpoint for OGC conformance test (http://kahlua.eecs.jacobs-university.de/conformance)

**Comment by keshav-nangare** [comment]
We used the following Capability URL:
http://kahlua.eecs.jacobs-university.de/conformance

If you observed the following result, the test **wcs2:soap-core-req1-9** is executed successfully. 

```
Test wcs2:soap-core-req1-9 type Mandatory default result Passed (s0017/d9714e112_1/d9714e235_1/d1e64_1/d148e42_1)

Assertion: req1-9:For all coverages offered by the server under test, test coverage structure, service parameters, and service metatada via SOAP GetCapabilities, DescribeCoverage and GetCoverage operations. Verify the responses contain the required information.

Message d148e859_1:
   [MESSAGE] Test coverage test_irr_cube_2

Message d148e859_2:
   [MESSAGE] Test coverage test_mean_summer_airtemp

Message d148e859_3:
   [MESSAGE] Test coverage test_mr

Message d148e1017_1:
   [MESSAGE] Test operation GetCapabilities

Message d148e1017_2:
   [MESSAGE] Test operation DescribeCoverage

Message d148e1017_3:
   [MESSAGE] Test operation GetCoverage

Result: Passed
```

The issue is not reproduced.

Can please reinstall the wcs2 test and try again. If you still get the issue let us know.

**Comment by bangph** [comment]
yes, that is why I said it does not happens anymore, so just close it here.
