### ISSUE TITLE
Compilation failure on branch feature-issue190

### ISSUE THREAD

**Issue by rjmartell** [opengeospatial/teamengine#200]
A compilation failure occurs when building branch [feature-issue190](/opengeospatial/teamengine/tree/feature-issue190).

```
[ERROR] teamengine-spi/src/main/java/com/occamlab/te/spi/executors/testng/EarlReporter.java:[325,58] cannot find symbol
[ERROR] symbol:   variable Untested
[ERROR] location: class com.occamlab.te.spi.vocabulary.EARL
```

**Comment by rjmartell** [comment]
Several CITE-related resources were added to the EARL vocabulary (e.g. Inherited_Failure). These don't belong here since they are not defined in the [EARL schema](https://www.w3.org/TR/EARL10-Schema/); they should be added to the custom CITE vocabulary (com.occamlab.te.spi.vocabulary.CITE).

**Comment by bermud** [comment]
@rjmartell, please let us know if this fix the issue.

**Comment by keshav-nangare** [comment]
@rjmartell 

As per the comment I have not moved the resource from EARL to CITE vocabulary yet. 

Should I move that resources to CITE vocabulary?

We have to keep standard earl resource into EARL vocabulary. Right?
