### ISSUE TITLE
TeamEngine can only run the first choosen Test subset of test suite

### ISSUE THREAD

**Issue by bangph** [opengeospatial/teamengine#202]
For example WCS 2.0.1 has these subset test suites from the conformance test

WCS Core | WCS POST | Processing | ScalingInterpolation | Range Subsetting | CRS | EOWCS

They are checkboxes and If I check all the check boxes, it will only run the WCS_Core test. It should change to "radio box" to avoid misunderstanding.

**Comment by bermud** [comment]
I think WCS Core should always run.  We need to check that the logic behind the form for the selection of the subsets is working as expected.

**Comment by keshav-nangare** [comment]
This issue is with the WCS test, so moved here: [#29](https://github.com/opengeospatial/ets-wcs20/issues/29)

**Comment by keshav-nangare** [comment]
Fixed with this commit: https://github.com/opengeospatial/ets-wcs20/commit/05864938252b961231442f835ffb4083eab3deff
