### ISSUE TITLE
Error in calling extensions in WCS2 .0.1 (EOWCS) with Null Exception

### ISSUE THREAD

**Issue by bangph** [opengeospatial/teamengine#204]
TeamEngine returns an exception when running test WCS 2.0.1 (EOWCS)

`Error in call to extension function {public synchronized void com.occamlab.te.TECore.callTest(net.sf.saxon.expr.XPathContext,java.lang.String,java.lang.String,net.sf.saxon.om.NodeInfo,java.lang.String) throws java.lang.Exception}: Exception in extension function java.lang.NullPointerException
Result: Failed`

it fails right after the test suite started, then no other log can be seen.

**Comment by bangph** [comment]
@rjmartell  @bermud  please have a look.

**Comment by keshav-nangare** [comment]
@bangph 

We have investigated this issue, the Namespace is not defined for the prefix "**wcseo**" in test `<ctl:call-test name="wcseo:main">` that's why it is failing with the null pointer exception.

**Comment by bangph** [comment]
good work, so maybe add some message for this exception as it will help later if other test suites can have this problem.

**Comment by keshav-nangare** [comment]
Fixed with this commit: [d511ebffbdc3e08618fc2561701a99386aa9a989]( https://github.com/opengeospatial/ets-wcs20/commit/d511ebffbdc3e08618fc2561701a99386aa9a989)

**Comment by keshav-nangare** [comment]
This issue is with the wcs20 test, so I have maved here [#26](https://github.com/opengeospatial/ets-wcs20/issues/26)
