### ISSUE TITLE
Cannot run CTL scripts from JAR file

### ISSUE THREAD

**Issue by rjmartell** [opengeospatial/teamengine#205]
It is not possible to run CTL scripts that are packaged into a JAR file on the class path. A runtime exception is thrown: 

    java.lang.IllegalArgumentException: URI is not hierarchical

It would seem that a CTL script must be a File resource (see com.occamlab.te.SetupOptions::addSource(File source).

**Comment by rjmartell** [comment]
If this were possible then one could package and distribute a CTL-based suite in a single JAR file and not need to read them from some specified file system location (TE_BASE). Application configuration would be simpler as a result.

**Comment by dstenger** [comment]
TODO: Create concept for workflow and discuss it again.

**Comment by keshav-nangare** [comment]
Current workflow of teamengine as follows:
     1.  All the scripts are present in the TE_BASE/script directory.

**Comment by keshav-nangare** [comment]
Current workflow of teamengine as follows:
1. All the scripts are present in the TE_BASE/script directory.
2. Each script has its own config.xml file and the teamengine will create the only on config.xml from all ETS config file in TE_BASE directory, then this file is used for further operations.
3. When we start the tomcat the teamengine app is transforming all the CTL script to an executable form of XSLT which are referred by the teamengine app for the test execution.

Similarly, we have to achieve these steps when we are packaging CTL based project to JAR.

**Comment by keshav-nangare** [comment]
An existing scenario of the TestNG test execution as follows:
1. Test execution via webapp:
      - Each TestNG test has its own CTL script with HTML form to accept user inputs.
      - After accepting the user inputs the CTL script itself calls the TestNGController's doTestRun() method for further test execution.
      - This execution is performed from the corresponding test-suite JAR.
2. Test execution via REST interface:
     - TestRunResource class scans all the JAR from the classpath and find the appropriate controller object and will call doTestRun() method for further execution.

Similarly, can we try the same approach for CTL test execution:

1. Test execution via webapp:
      - Currently, CTL based tests referring the script from TE_BASE/script directory for execution.
      - Can we try to implement the same approach as TestNG test does?
      - If it is possible to update the CTL test execution, it should execute it from JAR with the help of CtlRunner by invoking the doTestRun() method.

2. Test execution via REST interface: We already have this approach with CTL test.

**Comment by dstenger** [comment]
Please also see https://github.com/opengeospatial/teamengine/wiki/Architectural-enhancements-(teamengine-v5).

**Comment by ghobona** [comment]
Overtaken By Events.
