### ISSUE TITLE
View Session delete icons are not align

### ISSUE THREAD

**Issue by bangph** [opengeospatial/teamengine#209]
The "trash" icons are not align the same row with the session then one can easily delete wrong session. It is simple HTML to fix it and avoid wrong delete.

http://cite.opengeospatial.org/teamengine/viewSessions.jsp

![align_delete_icon](https://cloud.githubusercontent.com/assets/6914451/23065001/90ad0a26-f513-11e6-99c3-8c9f1c44a80d.png)

**Comment by bermud** [comment]
@bangph, thank you for the feedback.  Will fix on the next revisions.

**Comment by keshav-nangare** [comment]
The trash icons are aligned in same row with session. 

Now it looks like as below:

![test sessions](https://user-images.githubusercontent.com/14732650/32367119-117c2fba-c0a7-11e7-9e76-56689f320387.png)

**Comment by keshav-nangare** [comment]
Fixed with this commit: a41a1823864ad1079990ea5dd8cba6461ae1dd3c
