### ISSUE TITLE
Cannot write more than one result document to the same URI.

### ISSUE THREAD

**Issue by keshav-nangare** [opengeospatial/teamengine#212]
XSLT failed to write the result document due to the same file name present in the same location.

XTDE1490: Cannot write more than one result document to the same URI, or write to a URI
 that has been read: file:/C:/TE_BASE/users/ogctest/s0005/result/describeAllFeatureTypes.html

**Comment by keshav-nangare** [comment]
Actually this issue is found in the wfs20 tests.

The "Simple WFS" conformance class has the two tests with the same name. Refer below screenshot and testng-result file.

The repeated test name is `name="describeAllFeatureTypes"`.

![repeated_tests_name_wfs20](https://cloud.githubusercontent.com/assets/14732650/25852243/5608b920-34e6-11e7-8bcc-0769829bc5cf.jpg)

**Comment by bermud** [comment]
@rjmartell, please follow up with Keshav on this issue.

**Comment by bermud** [comment]
@rjmartell, we need your input on this issue. It is the only test that has this problem. Please advise and fix.

**Comment by keshav-nangare** [comment]
@rjmartell 

It would be great if you provide some suggestion on this issue, so we can move forward.

Thanks in advance!!!

**Comment by dstenger** [comment]
Identifier could be added to the HTML files.
E.g.
```
testName.html
testName2.html
testName3.html
```

**Comment by dstenger** [comment]
Fixed with pull request: #247

**Comment by dstenger** [comment]
**Test with ets-wfs20 and Web Browser Interface**

Test run with reference implementation [1].
All HTML files exist and can be opened from index.html page (tested samples).

[1] http://cite.deegree.org/deegree-webservices-3.4-RC3/services/wfs200?service=WFS&request=GetCapabilities

**Comment by dstenger** [comment]
**Test with ets-wfs20 and REST Interface**

Test run (+ HTTP header: Accept: application/zip): http://localhost:8081/teamengine/rest/suites/wfs20/1.26/run?wfs=http://cite.deegree.org/deegree-webservices-3.4-RC3/services/wfs200?service=WFS%26request=GetCapabilities
All HTML files exist and can be opened from index.html page (tested samples).

**Comment by dstenger** [comment]
**Test with ets-wfs20 and REST Interface**

Test run (+ HTTP header: Accept: application/zip): http://localhost:8081/teamengine/rest/suites/wfs20/1.26/run?wfs=http://cite.deegree.org/deegree-webservices-3.4-RC3/services/wfs200?service=WFS%26request=GetCapabilities
All HTML files exist and can be opened from index.html page (tested samples).

**Comment by dstenger** [comment]
**Test with ets-wfs20 and REST Interface**

Test run (+ HTTP header: Accept: application/zip): http://localhost:8081/teamengine/rest/suites/wfs20/1.26/run?wfs=http://cite.deegree.org/deegree-webservices-3.4-RC3/services/wfs200?service=WFS%26request=GetCapabilities
All HTML files exist and can be opened from index.html page (tested samples).
