### ISSUE TITLE
Validate the service endpoint URL before running test

### ISSUE THREAD

**Issue by bangph** [opengeospatial/teamengine#214]
The problem is simple but it is not convenient when copying the service endpoint from Webbrowser, the http:// is ignored (e.g:  kahlua.eecs.jacobs-university.de/conformance?SERVICE=WCS&VERSION=2.0.1&REQUEST=GetCapabilities)

And when starting the test, Team Engine will have error
 URL: kahlua.eecs.jacobs-university.de/conformance?SERVICE=WCS&VERSION=2.0.1&REQUEST=GetCapabilities
Error in call to extension function {public org.w3c.dom.NodeList com.occamlab.te.TECore.request(org.w3c.dom.Document,java.lang.String) throws java.lang.Throwable}: Exception in extension function java.net.MalformedURLException: no protocol: kahlua.eecs.jacobs-university.de/conformance?SERVICE=WCS&VERSION=2.0.1&REQUEST=GetCapabilities
Result: Failed

The validation could be done in the web browser to validate with the HTTP pattern first (http://xxx/..xxx)

**Comment by dstenger** [comment]
Tasks:
1. Define expected behaviour (main question: Should TEAM Engine be capable to handle other protocols than HTTP?).
1. Apply expected behaviour to code.

**Comment by rasdaman-doi** [comment]
@dstenger I think it just checks if it misses http:// for the URL then it considers it is http protocol by adding this prefix internally by default. Also, it should support https as well.

**Comment by dstenger** [comment]
I propose to check whether a protocol is given by URI. This means ...:// must exist.

The check should not be too restrict as it must be defined what types of URIs are supported by TEAM Engine first. E.g. is a file URI allowed (file://...)?

**Comment by dstenger** [comment]
I propose to validate following pattern: ```[ANY_STRING]://[ANY_STRING]```

**Comment by dstenger** [comment]
If validation is failing, error message appears saying: ```The URI of the tested resource is not valid (e.g. protocol is missing). Please recheck the URI of the passed resource.```

**Comment by keshav-nangare** [comment]
@dstenger 

Following is the solution for the URL validation:

We can validate the URL using HTML5 property. Need to update only form with the textbox input type to `url`.

But the HTML5 is supporting only for the latest browsers. 

Following are the changes:

Old:  `<input name="text" size="96" type="url" value="" />`

New:  `<input name="uri" size="96" type="url" value="" required="true" />`

This HTML5 URL validation is working with the pattern that we are looking for. This validationis working with the pattern as mentioned in above comment.

Can we implement this solution?

**Comment by dstenger** [comment]
There is no change in TEAM Engine itself necessary. So, this issue can be closed.

Solution proposed in previous comment will be implemented for WCS 2.0.2 in issue https://github.com/opengeospatial/ets-wcs20/issues/49.
