### ISSUE TITLE
View session is not sorted correctly

### ISSUE THREAD

**Issue by bangph** [opengeospatial/teamengine#215]
![screenshot from 2017-05-22 09-36-09](https://cloud.githubusercontent.com/assets/6914451/26297287/82ab83d6-3ed2-11e7-9e2b-048bbe3c4055.png)

This should be sorted by date if the old session is somehow was overwritten with the new session (?).

**Comment by dstenger** [comment]
We even propose further updates of the layout:

1. List of sessions should be moved below the button "Create a new session".
1. Newest session should be on the top and oldest on the bottom of the list.
1. Sessions are sorted by data instead by session ID (original request of this issue).

@bangph @bermud @keshav-nangare 
What do you think of extending this issue to the three tasks mentioned above?

**Comment by bangph** [comment]
@dstenger I agree with 2 and 3, it will be useful. I don't have a problem with 1 so it is your choice.

**Comment by dstenger** [comment]
When the session list becomes very long you always have to scroll down to start a new session. This is the reason why 1 improves the handling for users (no scrolling to start a new session).

**Comment by bangph** [comment]
@dstenger then you could implement pagination for session list instead, I don't want to scroll down for a long list.

**Comment by keshav-nangare** [comment]
@dstenger 

We can do changes as you suggested in comment i.e. 1,2 & 3.

**Comment by dstenger** [comment]
Yes, I am in favour of doing those changes.

@bangph You are right, but this is more complex and eventually not easy to implement.
@keshav-nangare Can you do a short code review if improvement proposed by bangph can be implemented easily? If this is not the case, I propose to do the three originally described improvements.

**Comment by keshav-nangare** [comment]
I have proposed solution according to your comment i.e(1,2,3). 

Now the test session are sorted by date.


![image](https://user-images.githubusercontent.com/14732650/33074554-9e15de0a-ceec-11e7-8139-9a4d00207fbe.png)

**Comment by keshav-nangare** [comment]
Fixed with this commit: 1d4b6f729d5f7266d4aa6059ad76f081e8f34cf9

**Comment by dstenger** [comment]
@keshav-nangare 

Thank you for fixing this.
It appears that there are merge conflicts with the master branch.
Can you please resolve those?

**Comment by keshav-nangare** [comment]
@dstenger 

I have resolved conflicts of this branch. Now you can merge it into master.

**Comment by dstenger** [comment]
## Test fix

* Start test environment with Docker (https://github.com/opengeospatial/teamengine-docker).
* Execute several test runs.
* All three new behaviours can be observed as expected.
