### ISSUE TITLE
Create REST API for the latest EARL report.

### ISSUE THREAD

**Issue by keshav-nangare** [opengeospatial/teamengine#217]
Create REST API for the EARL report, whenever user request for the EARL and HTML result it should return in response depend on content-type.  

1. The API should return test result in EARL format.
2. The API should return test result in HTML format.

**Comment by keshav-nangare** [comment]
REST api to get result in following formats:


1. Default response is in xml format.

2. Get response in EARL format:  
      - Add parameter into the request header. `accept: application/rdf+xml`

3. Get HTML report [**In progress**]: 
      - Add parameter into the request header. `accept: application/html`
      - This will return the zip file including the all html files.

**Comment by bermud** [comment]
Can you provide example of how you envision the API URL to add this capability? 
format=xyz

And the default should be EARL !

No 1 (Default response is in xml format) is low priority and should be done only for backward compatibility

**Comment by lgoltz** [comment]
As Keshav said before (https://github.com/opengeospatial/teamengine/issues/217#issuecomment-319598810) the _Accept_ header is used to determine the format of the response. 
Technical both ways, _Accept_ header and KVP, are possible. First is more REST like, KVP more OGC like.

We have to decide how to implement and where to document. As it is  not ETS specific [1] maybe on the entry point of all available REST APIs.

[1] http://cite.opengeospatial.org/teamengine/rest/suites

**Comment by dstenger** [comment]
I would even say that the format must be defined by the request header to keep the API RESTful. Otherwise the interface would object a REST principle.
But, as Lyn already said, KVP is more OGC like.

**Comment by keshav-nangare** [comment]
@dstenger and @lgoltz 

As per above suggestion we need to add format parameter in REST URL to get the appropriate result.

It's easy to user to understand the which type result he want in response.

I have updated the REST API with the format parameter. I have tested with the TestNG tests and worked fine.

While testing with the CTL test I got few errors while returning the zip file, so currently working on it.

Once done with above fix will provide you document and example.

Thanks for suggestion.

**Comment by dstenger** [comment]
So, the format can be defined as KVP, now? Is setting it in request header 'Accept' still a valid option?

If REST principles are taken into consideration, the request header 'Accept' is the better way to solve it (as already implemented).

**Comment by keshav-nangare** [comment]
Now the format can be defined as KVP based. I think KVP is good because normal user can get the appropriate result through the browser, just need to pass the KVP parameter into URL.

If we use the request header 'Accept' then every time user need to use the any client interface to hit the request(such as REST_client or Postman) to specify the request header.

**Comment by dstenger** [comment]
All updates of the REST API must be documented (issue #224).

@bermud What are your thoughts about the discussion above?

**Comment by dstenger** [comment]
Dicumentation is present in https://github.com/opengeospatial/teamengine/issues/220#issuecomment-326260245.

**Comment by dstenger** [comment]
**Test with ets-wfs20 and [1]**

* No format parameter: http://localhost:8081/teamengine/rest/suites/wfs20/1.26/run/?wfs=http://cite.deegree.org/deegree-webservices-3.4-RC3/services/wfs200?service=WFS%26request=GetCapabilities
  * EARL result is displayed.
* Format parameter=earl: http://localhost:8081/teamengine/rest/suites/wfs20/1.26/run/?wfs=http://cite.deegree.org/deegree-webservices-3.4-RC3/services/wfs200?service=WFS%26request=GetCapabilities&format=earl
  *  EARL result is displayed.
* Format parameter=xml: http://localhost:8081/teamengine/rest/suites/wfs20/1.26/run/?wfs=http://cite.deegree.org/deegree-webservices-3.4-RC3/services/wfs200?service=WFS%26request=GetCapabilities&format=xml
  * XML (TestNG) result is displayed.
* Format parameter=html: http://localhost:8081/teamengine/rest/suites/wfs20/1.26/run/?wfs=http://cite.deegree.org/deegree-webservices-3.4-RC3/services/wfs200?service=WFS%26request=GetCapabilities&format=html
  * Just white page is shown.
* Add html to endpoint: http://localhost:8081/teamengine/rest/suites/wfs20/1.26/html/run/?wfs=http://cite.deegree.org/deegree-webservices-3.4-RC3/services/wfs200?service=WFS%26request=GetCapabilities
  * Zip-File is returned but zip-file cannot be opened.
* Add html to endpoint and format parameter=html: http://localhost:8081/teamengine/rest/suites/wfs20/1.26/html/run/?wfs=http://cite.deegree.org/deegree-webservices-3.4-RC3/services/wfs200?service=WFS%26request=GetCapabilities&format=html
  * Zip-File with HTML result is returned and zip-file can be opened. HTML pages are present and can be opened from following directory ```/usr/local/tomcat/temp/testng/9e2df02b-6bd8-4376-aecd-f9a6a76f3ffc/result/```.

[1] http://cite.deegree.org/deegree-webservices-3.4-RC3/services/wfs200?service=WFS&request=GetCapabilities

**Comment by dstenger** [comment]
**Test with ets-wms13 and [1]**

* No format parameter: http://localhost:8081/teamengine/rest/suites/wms/1.23/run?capabilities-url=http://cite.deegree.org/deegree-webservices-3.4-RC3/services/wms130?service=WMS%26request=GetCapabilities
  * EARL result is displayed (incomplete as CTL scripts have not been extended, yet).
* Format parameter=earl: http://localhost:8081/teamengine/rest/suites/wms/1.23/run?capabilities-url=http://cite.deegree.org/deegree-webservices-3.4-RC3/services/wms130?service=WMS%26request=GetCapabilities&format=earl
  * EARL result is displayed (incomplete as CTL scripts have not been extended, yet).
* Format parameter=xml: http://localhost:8081/teamengine/rest/suites/wms/1.23/run?capabilities-url=http://cite.deegree.org/deegree-webservices-3.4-RC3/services/wms130?service=WMS%26request=GetCapabilities&format=xml
  * XML (CTL) result is displayed.
* Format parameter=html: http://localhost:8081/teamengine/rest/suites/wms/1.23/run?capabilities-url=http://cite.deegree.org/deegree-webservices-3.4-RC3/services/wms130?service=WMS%26request=GetCapabilities&format=html
  * Just white page is shown.
* Add html to endpoint: http://localhost:8081/teamengine/rest/suites/wms/1.23/html/run?capabilities-url=http://cite.deegree.org/deegree-webservices-3.4-RC3/services/wms130?service=WMS%26request=GetCapabilities
  * Zip-file is returned but zip-file cannot be opened.
* Add html to endpoint and format parameter=html: http://localhost:8081/teamengine/rest/suites/wms/1.23/html/run?capabilities-url=http://cite.deegree.org/deegree-webservices-3.4-RC3/services/wms130?service=WMS%26request=GetCapabilities&format=html
  * Zip-file with HTML result is returned and zip-file can be opened. HTML pages are present and can be opened from following directory ```/usr/local/tomcat/temp/fa54ea3d-fe34-48ce-b7cd-74140fb1afba/result/``` (incomplete as CTL scripts have not been extended, yet).

[1] http://cite.deegree.org/deegree-webservices-3.4-RC3/services/wms130?service=WMS&request=GetCapabilities
