### ISSUE TITLE
Enhance CtlExecutor to return EARL

### ISSUE THREAD

**Issue by lgoltz** [opengeospatial/teamengine#219]
Currently the CtlExecutor returns 'ctl format' regardless of the requested format. Expected is that the  the request with header `Accept: application/rdf+xml` returns the EARL report.

**Comment by keshav-nangare** [comment]
We have updated the CtlExecutor, now it will return the xml and earl report in response according to content-type.

Here is the branch with changes: https://github.com/opengeospatial/teamengine/commits/feature-issue219

Fixed with this commit: 4b3b3707bceb5bbf2d30ed9db2bc4af6e13ea5a3

**Comment by lgoltz** [comment]
Works!

I've created pull request https://github.com/opengeospatial/teamengine/pull/222
