### ISSUE TITLE
Provide documentation and examples of the new report

### ISSUE THREAD

**Issue by bermud** [opengeospatial/teamengine#220]
Please document and provide 2 examples (on the guides) of how the report will look like both in HTML and EARL

**Comment by lgoltz** [comment]
The entry point of the currently available REST APIs is http://cite.opengeospatial.org/teamengine/rest/suites

More information about the REST APIs of specific ETS can be requested by appending the code and version of the ets, e.g:
 * ETS WFS 2.0: http://cite.opengeospatial.org/teamengine/rest/suites/wfs20/1.26/ 
 * CAT 3.0: http://cite.opengeospatial.org/teamengine/rest/suites/cat30/1.0/
   * documentation seems to be incomplete
 * GML 3.2.1: http://cite.opengeospatial.org/teamengine/rest/suites/gml32/1.25/

Currently the teamengine is not able to return different output formats. I've tried with and _Accept_ header as described in https://github.com/opengeospatial/teamengine/issues/217#issuecomment-319598810. Passing `Accept: application/rdf+xml` returns a NullPointer Exception. 
Furthermore https://github.com/opengeospatial/teamengine/issues/217 is not finished yet.  

As already noted in https://github.com/opengeospatial/teamengine/issues/217#issuecomment-322986381 the documentation of the REST API could be part of the entry point for all REST APIs [2].  
@bermud Is it ok for you?

[1] http://cite.opengeospatial.org/teamengine/rest/suites/wfs20/1.26/run?wfs=http://cite.deegree.org/deegree-webservices-3.4-RC3/services/wfs200?service=WFS%26request=GetCapabilities
[2] http://cite.opengeospatial.org/teamengine/rest/suites

**Comment by dstenger** [comment]
Currently, as Lyn already documented, it is not possible to retrieve an EARL report via REST interface on production.

Following request can be used to retrieve an XML report of WFS 2.0 test suite: http://cite.opengeospatial.org/teamengine/rest/suites/wfs20/1.26/run?wfs=http://cite.deegree.org/deegree-webservices-3.4-RC3/services/wfs200?service=WFS%26request=GetCapabilities

**Comment by keshav-nangare** [comment]
Followings are the way to invoke REST API with the different result:

* XML
* EARL
* HTML

   * We can get the test results in three different way, we need to add query parameter **`format`** in URL.

Following are the parameter to get the appropriate result:

1. For XML result : **`format=xml`**
2. For EARL result : **`format=earl`**
3. For HTML result : **`format=html`**

Example:  `http://localhost:8080/teamengine/rest/suites/gml32/1.26-SNAPSHOT/run?format=xml&iut=http://cite.deegree.org/deegree-webservices-3.4-RC3/services/gml321?service=WFS&request=GetFeature&Version=2.0.0&typenames=app:Autos`

**NOTE for HTML result:**

The REST API URL is bit changed for the HTML result. When we are invoking the API for HTML result the zip file is returned in response.
The zip file contains the bunch of all html files and we can see the result by opening the index.html file.

For example:

Existing URL: `http://localhost:8080/teamengine/rest/suites/wms/1.22/run`

Changed URL: `http://localhost:8080/teamengine/rest/suites/wms/1.22/html/run`

**Comment by dstenger** [comment]
Further tests/examples can be found here: https://github.com/opengeospatial/teamengine/issues/217#issuecomment-327144707 and https://github.com/opengeospatial/teamengine/issues/217#issuecomment-327148608.

Used branches are master branch of TEAM Engine and latest tags of ets-wfs20 (1.26) and ets-wms13 (1.23).
