### ISSUE TITLE
Provide team engine entry for new OSGeo website

### ISSUE THREAD

**Issue by jj0hns0n** [opengeospatial/teamengine#221]
Can someone on the project team help us add an entry for Team Engine on the new osgeo website http://osgeo.getinteractive.nl/projects/ 

Contact me via email. Thanks!

/cc @rjmartell

**Comment by dstenger** [comment]
TEAM Engine entry was created: http://osgeo.getinteractive.nl/projects/teamengine/

We will continue updating the page.

**Comment by jj0hns0n** [comment]
Thanks, closing!
