### ISSUE TITLE
Create message for users if HTML report cannot be created from CTL

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/teamengine#223]
This issue is relevant for following pull request: https://github.com/opengeospatial/teamengine/pull/211

If following update is not implemented for CTL test suites https://github.com/opengeospatial/cite/wiki/Encoding-Conformance-Classes, the generated HTML report will be empty.

In this case, a prominent message/text should appear, saying that this test suite does not support HTML reports and the old report must be used instead. A link to the old report is provided.

**Comment by dstenger** [comment]
@keshav-nangare Is this issue fixed? If this is the case, can you please create a pull request?

**Comment by keshav-nangare** [comment]
Added the message in result page.


![image](https://user-images.githubusercontent.com/14732650/30024750-dce480a6-9192-11e7-8f59-07d1d91a1fcd.png)






Fixed with this commit: 8d6698916a7fd20a1c87fb51978051a0a2eb85d5

**Comment by dstenger** [comment]
Further testing is required.

**Comment by dstenger** [comment]
Test with ets-wms13 and [1]. An alert is shown as described above and the old report can be accessed.
Test with ets-wfs20 and [2]. The alert also appears and an HTML report is present.

-> The alert should not appear when the HTML report is present.
-> Suggestion: Can the alert be replaced by a mechanism which just changes the display of the HTML report to the text currently written in the alert?
E.g. following is displayed on the result page (no alert):
```
This test suite does not support HTML reports and the old report must be used instead.

See the detailed old test report.
```

[1] http://cite.deegree.org/deegree-webservices-3.4-RC3/services/wms130?service=WMS&request=GetCapabilities
[2] http://cite.deegree.org/deegree-webservices-3.4-RC3/services/wfs200?service=WFS&request=GetCapabilities

**Comment by dstenger** [comment]
Tasks discussed in https://github.com/opengeospatial/teamengine/issues/223#issuecomment-327137702 are worked on in #230.
