### ISSUE TITLE
Update documentation of REST API

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/teamengine#224]
Documentation of REST API must be updated considering the latest development (e.g. #217).

Following documents are affected:
* http://opengeospatial.github.io/teamengine/users.html
* http://opengeospatial.github.io/teamengine/profiles-guide.html
* https://github.com/opengeospatial/teamengine/blob/master/doc/en/index.rst

**Comment by dstenger** [comment]
Changes are documented in https://github.com/opengeospatial/teamengine/issues/220#issuecomment-326260245.

**Comment by dstenger** [comment]
Also consider: https://github.com/opengeospatial/teamengine/issues/232

**Comment by keshav-nangare** [comment]
Updated documents with this commit: 0e43c64bcef559bd7b1e21724e31b47734385d52

**Comment by dstenger** [comment]
Further updates were done: https://github.com/opengeospatial/teamengine/commit/0af8dcf23c297ad30bd542f95cb2a59c5f953bea
