### ISSUE TITLE
Do testing of current master branch

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/teamengine#227]
As many changes were merged into master branch, intensive testing should be done to prevent any unknown side-effects and to grant a stable next release.

Following project can be used for testing: https://github.com/opengeospatial/teamengine-integration-testing

Current master branch is defined as master branch with merges of 2017-09-04 and 2017-09-05.

Following functionalities should be tested in detail:
* All interfaces of TEAM Engine (Web-GUI, REST, CLI).
* Generation and completeness of reports in different formats (XML, EARL, HTML).
* Handling of test suites with different technological approaches (CTL, TestNG).

**Comment by dstenger** [comment]
There are no open pull requests left. Testing can be started now.

**Comment by dstenger** [comment]
Template for result table which should be filled during testing:

Test suite | Web Browser Interface | REST + EARL fomat | REST + HTML fomat | REST + XML fomat | CLI | Comments
---|---|---|---|---|---|---
ets-wfs20 | OK | OK | OK | OK | - | -
... | - | - | - | - | - | -
... | - | - | - | - | - | -
... | - | - | - | - | - | -

**Comment by keshav-nangare** [comment]
**Test result (date: 2017-10-05)**

TEAM Engine version: 4.11-SNAPSHOT

Test suite (+ version) | Web Browser Interface | REST + EARL fomat | REST + HTML fomat | REST + XML fomat | CLI | Tested endpoint | Comments
---|---|---|---|---|---|---|---

csw202 1.16 | ok | - | - | - | - | http://demo.pycsw.org/cite/csw?service=CSW&acceptVersions=2.0.2&request=GetCapabilities
-- | -- | -- | -- | -- | -- | --
gml32 1.25 | ok | ok | ok | ok | - | https://services.interactive-instruments.de/ogc-reference/schema/XtraServerGetFeature.xml
kml22 1.22 | ok | ok | ok | ok | - | https://developers.google.com/kml/documentation/KML_Samples.kml
wms13 1.23 | - | ok | ok | ok | - | http://cite.deegree.org/deegree-webservices-3.4-RC3/services/wms130?service=WMS&request=GetCapabilities
wfs20 1.26 | ok | ok | ok | ok | - | http://cite.deegree.org/deegree-webservices-3.4-RC3/services/wfs200?service=WFS&request=GetCapabilities




... | - | - | - | - | - | - | -
