### ISSUE TITLE
HTML report is not able to display test details page outside the teamengine.

### ISSUE THREAD

**Issue by keshav-nangare** [opengeospatial/teamengine#231]
When we opened the index.html page from the html report and if we click on any test to see the detail test result it is failed to open that page.

The HTML test details result page should be accessed outside teamengine.

**Comment by keshav-nangare** [comment]
Fixed with this commit: 0fe24217628a69e334ba1640f314c05ede124f11

**Comment by dstenger** [comment]
**Test**

Retrieve zip-file:
GET http://localhost:8081/teamengine/rest/suites/wfs20/1.26/run?wfs=http://cite.deegree.org/deegree-webservices-3.4-RC3/services/wfs200?service=WFS%26request=GetCapabilities
Header: Accept: application/zip

Unpack retrieved zip-file, open index.html and navigate through tests.

**Comment by dstenger** [comment]
In general, navigation works now.

But, not all required files are available.
E.g. after executing wfs20 test suite, following files are missing:
* invokeGetFeatureById.html#invokeGetFeatureById
* describeAllStoredQueries.html#describeAllStoredQueries
* listStoredQueries.html#listStoredQueries
* plus more.

@keshav-nangare Please analyse this error and create a new issue if it is not related to this issue.

**Comment by dstenger** [comment]
Also, if Web-GUI is used, navigation through HTML pages does not work anymore.

**Comment by keshav-nangare** [comment]
The xslt failed to create the test detail page for those tests due to the same test name.

We already created this issue here:  #212

**Comment by dstenger** [comment]
Ok, so this bug is covered by #212 then.

Nevertheless, https://github.com/opengeospatial/teamengine/issues/231#issuecomment-330467173 should be solved as part of this issue.
@keshav-nangare Can you please take a look at it?

**Comment by dstenger** [comment]
Fix: https://github.com/opengeospatial/teamengine/commit/6d6d63fcb1f543a5f9e68df85c58effe5610e5d1

Execute same test as in https://github.com/opengeospatial/teamengine/issues/231#issuecomment-330465167 -> Successful
Also, issue documented in https://github.com/opengeospatial/teamengine/issues/231#issuecomment-330467173 is solved.
