### ISSUE TITLE
REST API: Format should be passed via request header

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/teamengine#232]
Following REST principles the format is set by request header.

TEAM Engine should follow this common practice and define the requested format via request header instead of KVP.

Please also see: #217

**Comment by keshav-nangare** [comment]
@dstenger 

Means we are removing the format parameter form the URL right?

And implementing as we discussed earlier in this comment: https://github.com/opengeospatial/teamengine/issues/217#issuecomment-319598810

**Comment by dstenger** [comment]
Yes, that is correct.

**Comment by dstenger** [comment]
= Further informations

* ```Accept``` header is used to define the required content type.

* Examples how to download a zip-file via REST API.
  * Use web-browser-plugins like ```Modify Headers``` or ```Modify Header Value``` to set ```Accept``` header.
  * Use tools like ```wget``` or ```curl``` to download zip-file.

**Comment by keshav-nangare** [comment]
Thank you Dirk!!!

Once done with the changes will use this tools.

**Comment by keshav-nangare** [comment]
Updated the REST api with request header and removed the format parameter from the URL.

Following are the detail to invoke REST API:

1. Default response is EARL. 
      - Add parameter into the Request Header. `Accept: application/rdf+earl`

2. XML:  
      - Request Header. `Accept: application/xml`

3. HTML zip report: 
      - Request Header. `Accept: text/html`

**Comment by keshav-nangare** [comment]
Updated with this commit: 61accd2475b2fb133a3d74ecedb04f702b6b2ba7.

**Comment by keshav-nangare** [comment]
@dstenger 

As per your comment I have tried curl command to invoke API and able to get zip file in response.

Thank you.

**Comment by dstenger** [comment]
Thank you for your work.

Can you please create a pull request for this fix?

**Comment by dstenger** [comment]
If I send following requests (TEAM Engine runs on localhost:8081) with a web browser (Firefox) I just get an empty page and following stack trace is logged.
* http://localhost:8081/teamengine/rest/suites/wfs20/1.26/run?wfs=http://cite.deegree.org/deegree-webservices-3.4-RC3/services/wfs200?service=WFS%26request=GetCapabilities
* http://localhost:8081/teamengine/rest/suites/wms/1.23/run?capabilities-url=http://cite.deegree.org/deegree-webservices-3.4-RC3/services/wms130?service=WMS%26request=GetCapabilities
```
...
Error on line 1 column 1 of file:/usr/local/tomcat/temp/testng/d33845a5-a99c-4c8f-b81d-e03023b28a41/result.zip:
  SXXP0003: Error reported by XML parser: Content is not allowed in prolog.
Sep 08, 2017 2:57:10 PM com.sun.jersey.spi.container.ContainerResponse logException
SEVERE: Mapped exception to response: 500 (Internal Server Error)
javax.ws.rs.WebApplicationException: net.sf.saxon.trans.XPathException: org.xml.sax.SAXParseException; systemId: file:/usr/local/tomcat/temp/testng/d33845a5-a99c-4c8f-b81d-e03023b28a41/result.zip; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
	at com.sun.jersey.core.impl.provider.entity.SourceProvider$SourceWriter.writeTo(SourceProvider.java:214)
	at com.sun.jersey.core.impl.provider.entity.SourceProvider$SourceWriter.writeTo(SourceProvider.java:172)
	at com.sun.jersey.spi.container.ContainerResponse.write(ContainerResponse.java:302)
...
Caused by: net.sf.saxon.trans.XPathException: org.xml.sax.SAXParseException; systemId: file:/usr/local/tomcat/temp/testng/d33845a5-a99c-4c8f-b81d-e03023b28a41/result.zip; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
	at net.sf.saxon.event.Sender.sendSAXSource(Sender.java:379)
	at net.sf.saxon.event.Sender.send(Sender.java:164)
	at net.sf.saxon.IdentityTransformer.transform(IdentityTransformer.java:29)
	at com.sun.jersey.core.impl.provider.entity.SourceProvider$SourceWriter.writeTo(SourceProvider.java:208)
	... 29 more
Caused by: org.xml.sax.SAXParseException; systemId: file:/usr/local/tomcat/temp/testng/d33845a5-a99c-4c8f-b81d-e03023b28a41/result.zip; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
	at org.apache.xerces.util.ErrorHandlerWrapper.createSAXParseException(Unknown Source)
	at org.apache.xerces.util.ErrorHandlerWrapper.fatalError(Unknown Source)
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
...
```

Expected is that EARL is returned.

**Comment by dstenger** [comment]
If I send following request with header ```Accept: application/rdf+earl``` (Client: RESTED)
* http://localhost:8081/teamengine/rest/suites/wfs20/1.26/run?wfs=http://cite.deegree.org/deegree-webservices-3.4-RC3/services/wfs200?service=WFS%26request=GetCapabilities
I get:
```
406 Not Acceptable
```

**Comment by keshav-nangare** [comment]
When we are executing the REST URI from the browser, the browser itself is sending the Accept: text/html request header by default but we have configured this type for our HTML report and whenever it's true, it is trying to return the html report.
Maybe we have to change content type for html report because whenever we execute request through the browser it's sending the "text/html".

If we changed the HTML report content-type
text/html ===> application/zip
then it will work as expected.

**Comment by keshav-nangare** [comment]
Currently the header `Accept: application/rdf+earl` is not added in REST API, that's why it's returning the `406 Not Acceptable`.

I will add this content-type in REST api then it will work fine.

**Comment by dstenger** [comment]
We discussed the content-type of HTML reports and this is our conclusion:
* As the interface returns a folder structure with HTML files, the content-type ```application/zip``` is correct.
* The content type ```text/html``` is used if just a single HTML page is returned. The header ```Accept-Encoding``` then defines if the page is zipped or not.

Do you agree with that?

So, the implementation can be done as proposed.

**Comment by keshav-nangare** [comment]
Updated REST api with content-type:

Following are the details to invoke REST API:

1. Default response is EARL. 
      - Add parameter into the Request Header. `Accept: application/rdf+xml`

2. XML:  
      - Request Header. `Accept: application/xml`

3. HTML zip report: 
      - Request Header. `Accept: application/zip`


 
        
Commit: 500b0a5531a2c1432ed2a7dae25e41845c0b8f7f

**Comment by dstenger** [comment]
**Test with ets-wfs20 and [1] (bases on TestNG)**

REST API: http://localhost:8081/teamengine/rest/suites/wfs20/1.26/run?wfs=http://cite.deegree.org/deegree-webservices-3.4-RC3/services/wfs200?service=WFS%26request=GetCapabilities

* No header:
  * EARL result is displayed.
* Header: ```Accept: application/rdf+earl```
  *  EARL result is displayed.
* Header: ```Accept: application/xml```
  * EARL result is displayed. --> **Not expected**
* Header: ```Accept: application/zip```; /html is added to path
  * Zip-file is returned but zip-file cannot be opened (error occurs during unzip). --> **Not expected**

[1] http://cite.deegree.org/deegree-webservices-3.4-RC3/services/wfs200?service=WFS&request=GetCapabilities

**Comment by dstenger** [comment]
@keshav-nangare Can you please take a look at the not expected results during testing?
