### ISSUE TITLE
REST API: Set all required request and response HTTP header

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/teamengine#235]
Following HTTP header should be taken into consideration:

* Request header
  * Accept
  * Accept-Encoding

* Response header
  * Content-Encoding
  * Content-Type

**Comment by keshav-nangare** [comment]
What Content-Encoding should we use in HTML response header  GZIP or DEFLATE?

**Comment by dstenger** [comment]
As we use ```application/zip``` as mime type now, no Content-Encoding must be set in response. Instead, the Content-Type of the response has to be set to ```application/zip```.

**Comment by dstenger** [comment]
Content type of request with not supported Accept header returns EARL document. The ```Content-Type``` of the response is ```application/xml``` but it should be ```application/rdf+xml```.

**Comment by lgoltz** [comment]
Problem described in https://github.com/opengeospatial/teamengine/issues/235#issuecomment-329454224 is fixed with PR #254. 

Correct behaviour can be tested with the new SoapUI project in https://github.com/opengeospatial/cite-private/issues/37

**Comment by dstenger** [comment]
Correct behaviour can be confirmed: https://github.com/opengeospatial/teamengine/issues/242#issuecomment-339262692
