### ISSUE TITLE
REST API: parameter encoding

### ISSUE THREAD

**Issue by jonherrmann** [opengeospatial/teamengine#236]
We have an [issue](https://github.com/inspire-eu-validation/ets-repository/issues/93) using the [REST API of the WFS 2.0 test suite](http://cite.opengeospatial.org/teamengine/rest/suites/wfs20/1.26) and the passing of an URL as ```wfs``` parameter.

The WFS 2.0 test suite expects that only the ampersands in an URL are encoded. It seems that this partially encoded URL is used by the Team Engine without modification.

The Team Engine returns an error for this [service](http://services.cuzk.cz/wfs/inspire-cp-wfs.asp?ACCEPTVERSIONS=2.0.0&REQUEST=GetCapabilities&SERVICE=wfs&VERSION=2.0.0):
```
Error executing test suite (wfs20-1.26)
```
As we have no access to the log files of the tested WFS, we are not sure if the service returns an [exception](http://services.cuzk.cz/wfs/inspire-cp-wfs.asp?ACCEPTVERSIONS=2.0.0%26REQUEST=GetCapabilities%26SERVICE=wfs%26VERSION=2.0.0) to the TEAM Engine, due to the partially encoded URL.

It would be good if the TEAM Engine REST APIs would accept URLs that are completely encoded and invoke them 'correctly':
http://cite.opengeospatial.org/teamengine/rest/suites/wfs20/1.26/run?wfs=http%3A%2F%2Fservices.cuzk.cz%2Fwfs%2Finspire-cp-wfs.asp%3FACCEPTVERSIONS%3D2.0.0%26request%3DGetCapabilities%26service%3Dwfs

Please note that this URL, with the partially encoded value:
http://cite.opengeospatial.org/teamengine/rest/suites/wfs20/1.26/run?wfs=https://msdi.data.gov.mt/geoserver/MITA_WFS_BathingSites/ows?ACCEPTVERSIONS=2.0.0%26request=GetCapabilities%26service=wfs%26VERSION=2.0.0

and this URL, with the completely encoded value:
http://cite.opengeospatial.org/teamengine/rest/suites/wfs20/1.26/run?wfs=https%3A%2F%2Fmsdi.data.gov.mt%2Fgeoserver%2FMITA_WFS_BathingSites%2Fows%3FACCEPTVERSIONS%3D2.0.0%26request%3DGetCapabilities%26service%3Dwfs%26VERSION%3D2.0.0

return different test results (does not work with the Safari Browser as it seems to canonicalize the URIs).

**Comment by lgoltz** [comment]
A test with your service and the official TEAM Engine also breaks and reports the following exception:
```
Default CRS not recognized. No transform for classification ?Krovak (North Orientated)?.
```
It seems that the configured DefaultCRS `urn:ogc:def:crs:EPSG::5514` is not supported by the ETS WFS 2.0 (or rather the used library). There is already an issue for that: https://github.com/opengeospatial/ets-wfs20/issues/66

As it is useful to get the detailed exception message also when using the REST API, I've created #237.


I've tested the problem with the different result of the test runs when using different encodings with Firefox 55.0.2 and Chromium 60.0.3112.113  and the last two URLs.

As far as I see the results of the test runs are the same:
`<testng-results skipped="96" failed="10" total="117" passed="11">`

But the order of the test methods differs. Is this the difference you found?

**Comment by jonherrmann** [comment]
You are right, I did not notice that only the order of the test results are different and my interpretation, that the TEAM Engine does not support the encoded URL seems also to be wrong.

OK, I will update our software to pass completely encoded URLs to the TE.

Thanks for checking the issue and clarification!
