### ISSUE TITLE
REST API: Enhance interface to save and manage test results

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/teamengine#238]
The current user-mechanism can be used to save and manage test results.

**Requirements:**

1. Create/run test session/suite
There is not currently a way to run and save a test session as an authenticated user via the REST interface.

2. List user test sessions
There needs to be an endpoint for fetching a list of previous test sessions by a user.

**Comment by bermud** [comment]
Let's implement first the interface to list user test sessions. Where each record returned should have:
- session number
- standard tested
- date
- result

**Comment by dstenger** [comment]
Further ideas deriving from email discussion:

To 1.:
In general I would keep the mechanism to execute a test run as an anonymous user. I don't think it is good to be able to access old logs of those anonymous runs.
Also, we should not work with sessions as this does not match RESTful principles.
Instead, we should enable authentication via basic authentication for REST interface. The credentials can be passed as HTTP request header then.
If authentication is successful, the logs are stored in the folder of the authenticated user. If authentication fails, the test run is aborted.
So, the interface is just extended by the evaluation of the Authorization header.

To 2.:
There will be an extension as described in the issue by Luis.
The interface will look like this (of course, this is just a rough draft and there can still be changes):
GET {TEAMENGINE-WEBAPP}/rest/users/{USER}
HTTP Header: Authorization: {CREDENTIALS}
If authentication is successful and if authorization for requested user is successful, all test sessions of that user are returned. If authentication or authorization fail, access to test sessions is denied.

Also, 2. just lists all past test sessions and gives meta informations but it is not possible to view results of old test sessions via this interface.

**Comment by dstenger** [comment]
1. is also covered by #66.

**Comment by cmheazel** [comment]
re: "we should not work with sessions as this does not match RESTful principles."  This is a different use of the term session.  A TeamEngine session is (should be) a single resource which captures all of the information about a single test run.  For example, the path TE_BASE/users/<userid>/<UUID>/ would identify a resource which consists of all of the information associated with the <UUID> test run.

When Fielding talks about sessions he is referring to session-oriented network protocols.

**Comment by ghobona** [comment]
This issue has been overtaken by events.
