### ISSUE TITLE
REST API: remove 'html' from path to request resource in html format

### ISSUE THREAD

**Issue by lgoltz** [opengeospatial/teamengine#239]

**Comment by lgoltz** [comment]
Local branch: https://github.com/lat-lon/teamengine/tree/removeHtmlFromRestPath-239

Fixed my moving handleHtmlGet() from TestResultLog to TestResource and specifying @Produces per REST method.

Commit: https://github.com/lat-lon/teamengine/commit/2b22d740116402e4b3c647f7986d4bd0a28d7fdb

**Comment by lgoltz** [comment]
Local branch: https://github.com/lat-lon/teamengine/tree/removeHtmlFromRestPath-239

Fixed my moving handleHtmlGet() from TestResultLog to TestResource and specifying @Produces per REST method.

Commit: https://github.com/lat-lon/teamengine/commit/2b22d740116402e4b3c647f7986d4bd0a28d7fdb

**Comment by lgoltz** [comment]
Local branch: https://github.com/lat-lon/teamengine/tree/removeHtmlFromRestPath-239

Fixed my moving handleHtmlGet() from TestResultLog to TestResource and specifying @Produces per REST method.

Commit: https://github.com/lat-lon/teamengine/commit/2b22d740116402e4b3c647f7986d4bd0a28d7fdb

**Comment by dstenger** [comment]
**Test with ets-wfs20 and [1] (bases on TestNG)**

Endpoint: http://localhost:8081/teamengine/rest/suites/wfs20/1.26/run?wfs=http://cite.deegree.org/deegree-webservices-3.4-RC3/services/wfs200?service=WFS%26request=GetCapabilities

* No header
  * EARL result is displayed.
* Header: ```Accept: application/rdf+earl```
  *  EARL result is displayed.
* Header: ```Accept: application/xml```
  * XML (TestNG) result is displayed.
* Header: ```Accept: application/zip```
  * Zip-file with HTML result is returned and zip-file can be unzipped. HTML pages are present and can be opened.

[1] http://cite.deegree.org/deegree-webservices-3.4-RC3/services/wfs200?service=WFS&request=GetCapabilities

**Comment by dstenger** [comment]
**Test with ets-wfs20 and [1] (bases on TestNG)**

Endpoint: http://localhost:8081/teamengine/rest/suites/wfs20/1.26/run?wfs=http://cite.deegree.org/deegree-webservices-3.4-RC3/services/wfs200?service=WFS%26request=GetCapabilities

* No header
  * EARL result is displayed.
* Header: ```Accept: application/rdf+earl```
  *  EARL result is displayed.
* Header: ```Accept: application/xml```
  * XML (TestNG) result is displayed.
* Header: ```Accept: application/zip```
  * Zip-file with HTML result is returned and zip-file can be unzipped. HTML pages are present and can be opened.

[1] http://cite.deegree.org/deegree-webservices-3.4-RC3/services/wfs200?service=WFS&request=GetCapabilities
