### ISSUE TITLE
REST API: Setting of multiple content types in request header leads to unexpected behaviour

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/teamengine#242]
If following request header is set:
```Accept: text/html,application/xhtml+xml,application/xml```
EARL is returned and the Content-Type of response is application/xml;charset='utf-8'.

If following request header is set:
```Accept: text/html,application/xhtml+xml```
status code 406 is returned.

How can this behaviour be explained?

In addition, content type ```application/rdf+earl``` should not be accepted as it is replaced by ```application/rdf+xml```.

For further information please see: https://www.rfc-editor.org/rfc/rfc7231.txt

**Comment by bermud** [comment]
EARL should be returned by default. If we like XML, then request header should be application/rdf+xml.

**Comment by dstenger** [comment]
We should define the meaning of "default".
When no Accept header is passed, the software assumes that all mime types are accepted. --> EARL is returned.
If a not supported mime type is passed (e.g. text/html), an error is returned. --> HTTP status code 406.

For example, the default Firefox HTTP Accept header is:
```
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
```
In this case ```application/xml``` is chosen as this is the supported mime type with the highest weighting.
Thus, XML format should be returned per default when Firefox is used to request the REST API.

**Comment by dstenger** [comment]
If different supported media types are passed via Accept header and all of the have the same weight, ```application/rdf+xml``` should be picked first.

Example header:
```
Accept: application/xml,application/zip,application/rdf+xml
```
--> EARL (application/rdf+xml) is returned.

@bermud What do you think about my suggestions?

**Comment by dstenger** [comment]
**Conclusion after discussion:**
* If no Accept header is passed: return ```application/rdf+xml```
* If any Accept header is passed: evaluate the header and return content-type as defined by specification.

**Comment by keshav-nangare** [comment]
I have updated the REST API for multiple content-type is set in header and then return appropriate result in response.

The changes are tested with the wfs20 test. Following are the details of expected result:
 

Browser | URL | Request Header | Expected Output
-- | -- | -- | --
  |   |   |  
Mozilla Firefox | http://localhost:8080/teamengine/rest/suites/wfs20/1.26/run?wfs=https://services.interactive-instruments.de/ogc-reference/simple/wfs?request=getcapabilities%26service=wfs | text/html, application/xhtml+xml, application/xml; q=0.9, */*; q=0.8 | retuned XML
Chrome | http://localhost:8080/teamengine/rest/suites/wfs20/1.26/run?wfs=https://services.interactive-instruments.de/ogc-reference/simple/wfs?request=getcapabilities%26service=wfs | text/html, application/xhtml+xml, image/webp, image/apng, application/xml; q=0.9, */*; q=0.8 | returned XML




**`Tested REST API through Command Line with different combination of content type.`**
 

Content-Type | Expected output | Output
-- | -- | --
application/zip | Success |  
application/xml | Success |  
application/rdf+xml | Success |  
application/zip, application/xml, application/rdf+xml | Success | EARL
text/html | Failed | returned 406



**`Tested through REST Client`**

No Cotnent-type is provided in Request Header | Success | returned EARL report
-- | -- | --

**Comment by keshav-nangare** [comment]
Fixed with this commit: e70075f108829c7c51d920982246f98c7fa46c91

**Comment by lgoltz** [comment]
Code was improved by removing the method getPreferredMediaType() and using the JAXRS/Jersey mechanims instead: https://github.com/opengeospatial/teamengine/pull/254/commits/bf03c62bced8f37beec73946eff2c9e36619352b 

Already tested with the SoapUI project from https://github.com/opengeospatial/cite-private/issues/37#issuecomment-337609607 (not public, yet).

One test is failing: the request with Accept `application/zip;q=0.1,application/xml,application/rdf+xml;q=0.9` return RDF/EARL instead of the expected XML. This could be a problem with an outdated JAX-RS/Jersey version.
But the tests with `application/xml,application/zip,application/rdf+xml` and without Accept header work as expected now.

**Comment by dstenger** [comment]
Tested successfully with internal SoapUI project. Will be made available to public soon: https://github.com/opengeospatial/teamengine/wiki/Tests-for-TEAM-Engine
