### ISSUE TITLE
Failed to create testdetail html page of particular test

### ISSUE THREAD

**Issue by keshav-nangare** [opengeospatial/teamengine#245]
If the test-suite is having the multiple tests with the same name the xslt is failing to create the testdetail html page.

This issue is related to #212

**Comment by keshav-nangare** [comment]
Fixed with this commit: f41714e1cdcc36280e3d53e3701cb01180a89c2e

**Comment by dstenger** [comment]
**Test with ets-wfs20 and Web Browser Interface**

Test run with reference implementation [1].
The statistics of the HTML result page are correct.

[1] http://cite.deegree.org/deegree-webservices-3.4-RC3/services/wfs200?service=WFS&request=GetCapabilities
