### ISSUE TITLE
HTML report via Web Browser Interface: Buttons for old test report and session list navigate to wrong pages in some cases

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/teamengine#257]
Can be reproduced by executing following steps:
* Execute ets-wfs20 with service [1] via Web Browser Interface.
* Click on any test to view detailed result.
* Go back via browser functionality.
* Click on ```See the detailed old test report.``` or ```Sessions list```.
* Browser navigates to detailed test result again.
  * **Expected behaviour:** Should navigate to old test report or session list instead.

[1] http://cite.deegree.org/deegree-webservices-3.4-RC3/services/wfs200?service=WFS&request=GetCapabilities

**Comment by keshav-nangare** [comment]
@dstenger 

I have tested with the Google Chrome and its working fine. This issue is occurred in the Mozilla Firefox browser.

**Comment by keshav-nangare** [comment]
Issue is fixed with this commit: b4576299f66c31c9ea95f2fad7a99f225fe9d173

**Comment by dstenger** [comment]
Manual test confirms that navigation works correct, now.
WFS 2.0 test suite was used and reproducer steps of description executed (with Firefox).
