### ISSUE TITLE
Outdated ETS available via REST API if deployed in original and as dependency

### ISSUE THREAD

**Issue by lgoltz** [opengeospatial/teamengine#258]
Behaviour on Beta if WFS ETS 1.26 and NSG WFS ETS 0.2 is deployed:
 
 * http://cite.opengeospatial.org/te2/about/wfs/2.0.0/site/ says version 1.26
 * http://cite.opengeospatial.org/te2/rest/suites and click on WFS 2.0 
  * opens http://cite.opengeospatial.org/te2/rest/suites/wfs20/1.25/
 * http://cite.opengeospatial.org/te2/rest/suites/wfs20/1.26/run is not working

This seems to be an problem with the dependencies. The WFS ETS in version 1.25 is a transitive dependency of the NSG WFS ETS:

NSG WFS ETS includes the DGIWG WFS ETS includes the WFS ETS (version 1.25)

Upgrading the dependency of the DGIWG WFS ETS would solve the problem for now, but if the versions diverge later the problem will occur again. 

Furthermore the DGIWG WFS ETS is available via REST but not via the Web GUI.

**Comment by bermud** [comment]
Maybe there are repeated jars in the lib folder.

**Comment by keshav-nangare** [comment]
This issue is quite older as REST interface has been updated and removed the version parameter from the REST path.
