### ISSUE TITLE
REST API: Create path for latest version of each test suite

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/teamengine#261]
Currently, if REST API is used, the version of each test suite is part of the path.

There should be a path always matching the latest version of a test suite.

First, it has to be evaluated if this requirement does not oppose any REST principle.

**Comment by dstenger** [comment]
Problem: How does TEAM Engine identify the latest version of a test suite? Instead, an additional config folder could be added to TE_BASE containing the latest installation and version is ```latest```. Disadvantage of this approach: This version will also appear on overview page of Web Browser Interface.

**Comment by lgoltz** [comment]
@dstenger Why do you think it is problem to identify the latest version of a test suite?

Is it required to support multiple versions of a ETS?

**Comment by dstenger** [comment]
Then we need a complete specification of the version pattern. For example, following patterns are currently existing: 1.1.1; 1.1; r11, 1.1-rc, 1.1-beta1

The current architecture allows to support multiple versions of ETS. I don't think we should change this.
In my opinion, the "latest" path should be an additional path.

**Comment by dstenger** [comment]
> Is it required to support multiple versions of a ETS?

However, I agree that multiple versions of a test suite shall never be deployed in a single TEAM Engine. This can, for example, lead to dependency problems.

Thus, the version problem is just minor and is not an important part of solution.

@keshav-nangare Can you please remove the version parameter from REST paths?

**Comment by lgoltz** [comment]
I've updated the code that the version is requested from the TestSuiteController, this makes changes on the test suites (as described in https://github.com/opengeospatial/teamengine/issues/261#issuecomment-442463511) unneeded: https://github.com/opengeospatial/teamengine/commit/6bf75a61f959fb71322a008d958d6fa96395a593

**Comment by dstenger** [comment]
@lgoltz Shouldn't we allow both patterns (with and without version) to ensure backwards compatibility?

**Comment by dstenger** [comment]
Also, documentation must be updated.

**Comment by lgoltz** [comment]
> @lgoltz Shouldn't we allow both patterns (with and without version) to ensure backwards compatibility?

As backward compatibility is already broken if the version of the ets changes I think it is not necessary.  
We should think about this if it should be possible to run the same ets in multiple versions in one TEAM Engine instance. But this is currently not possible.

**Comment by dstenger** [comment]
I totally agree. Thus, it is not mandatory to keep the old behaviour.

Also, updated documentation.

**Comment by dstenger** [comment]
Pull request was successfully tested with WFS 2.0 test suite.
