### ISSUE TITLE
Warning in viewlog.xsl

### ISSUE THREAD

**Issue by lgoltz** [opengeospatial/teamengine#265]
During the execution of the ETS WFS 1.1 (1.32-SNAPSHOT) with TEAM Engine 5.1-SNAPSHOT on the docker environment, the following warning is logged:

```
Warning: at xsl:variable on line 83 of file:/usr/local/tomcat/webapps/teamengine/WEB-INF/classes/com/occamlab/te/web/viewlog.xsl:
  SXWN9001: A variable with no following sibling instructions has no effect
```

The xsl file [1] contains a lot of commented code. Maybe a clean up makes sense.

[1] https://github.com/opengeospatial/teamengine/blob/master/teamengine-web/src/main/resources/com/occamlab/te/web/viewlog.xsl

**Comment by keshav-nangare** [comment]
Removed warning message by commenting unused variables from xsl.

Fixed with this commit: 651c1c868f371856dc69b2e10aa7160295089f0f  [ PR: #291].
