### ISSUE TITLE
No way to re-run a single test from a Java IDE

### ISSUE THREAD

**Issue by aaime** [opengeospatial/teamengine#271]
The old CITE engine allowed to re-run a failing test at the tester command to check variations in the software being tested. The current engine UI does not seem to offer a similar ability.

I also could not find documentation on how to do so from TestNG code, assuming one has the source code available (the documentation only covers running the entire suite)

**Comment by dstenger** [comment]
Thank you for reporting. We will do further investigation.

**Comment by dstenger** [comment]
@aaime 
Can you please describe the isse more in detail?

Are you referencing the button "Execute this test again"?
E.g.:

![img_22112017_150213_0](https://user-images.githubusercontent.com/2989166/33120713-3f288bfe-cf73-11e7-8213-449f3fc8e88a.png)

This button is not integrated into the new UI. Nevertheless, you can still view the old report where this button is still existent.
TestNG test reports never provided this button.

**Comment by aaime** [comment]
I was actually reporting it for the new UI.
That said, it would also be nice if it could be possible to run a single test from a Java IDE (like with a normal test suite) instead of re-running the whole suite with a breakpoint

**Comment by keshav-nangare** [comment]
This feature is only for the CTL based test not for the TestNG test.
Existing way of "Execute this test again" button in old test result as follows:

1. When we click on this button it passes the test mode=retest with path of the previous test run.
2. It will set the required parameter to run the selected test and will start the test execution.
3. After successful execution it will update the test result and we can see the change in detailed old test report.


If we want to add this feature in new HTML report then following changes required.

1. Currently in new HTML report we don't have the test path so we need to add that path from earl.rdf to HTML report then only we can retest.
2. Then we have to use this test path to execute selected test again.
3. When the test executed again it should update the earl.rdf result with new result.
4. If the earl.rdf is updated then we need to update the new HTML report accordingly.

**Comment by dstenger** [comment]
@keshav-nangare Can you please document your findings regarding running a single TestNG test via IDE?

**Comment by keshav-nangare** [comment]
@dstenger 

Following are the finding to run the single/selected tests using IDE:

1. Add new listener in test suite to filter the selected test case
2. We can provide either single or multiple test case names with comma-separated values.
3. Also, we need to define the new TestRunArgument(e.g. IUT, ICS) to accept the selected test to run.
4. We can add a new argument into test-run-props.xml file and we can run the test suite in IDE.

Let me know your thought on this approach?

**Comment by dstenger** [comment]
@keshav-nangare Can you please check if it is possible to create a new TestNGController and the testng.xml file must not be adjusted? Maybe, the new Controller can add the new Listener manually to the TestNG configuration?

**Comment by keshav-nangare** [comment]
@dstenger 

I have created the new TestNGCustomController for TestNG based test suite which can be used to run a single test or multiple tests with a comma-separated list. Also, I have added listener to filter the tests from the given list in test-run-props.xml file with key attribute `includeTestMethods` and it will execute only selected tests. I have tried this workaround with `ets-kml22` so I am pushing these changes in the corresponding repository. Changes are here in-branch: https://github.com/opengeospatial/ets-kml22/tree/run_single_test

Steps to run test suite:

Goto -> Run -> RunConfiguration -> JavaApplication (Create new configuration for ets-kml22)
              Main->     Main Class: `org.opengis.cite.kml22.TestNGCustomController`
              Argument -> Program argument: `~/--path--/--to--/test-run-props.xml`



---test-run-props.xml----
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE properties SYSTEM "http://java.sun.com/dtd/properties.dtd">
<properties version="1.0">
    <comment>Sample test run arguments</comment>
    <entry key="iut">https://developers.google.com/kml/documentation/KML_Samples.kml</entry>
    <entry key="ics">3</entry>
    <entry key="includeTestMethods">verifyViewVolumeContent,verifyEmptyObjectHasId,verifyGeometryExtrude</entry>
</properties>
```

**Comment by keshav-nangare** [comment]
@dstenger 

I have created the separate test-run-props file for the single test executor. Created the new property file name with `single-test-run-props.xml` and changes are pushed into the same branch. https://github.com/opengeospatial/ets-kml22/tree/run_single_test

**Comment by dstenger** [comment]
@aaime 
IntelliJ IDEA has the capability to run single tests with the TestNG plugin. You can start the tests via testng.xml and afterwards it is possible to run single tests individually.

However, most TestNG test suites use complex dependency structures between the tests. So, most tests will not work individually as the preconditions are not fulfilled.

This is the reason why we do not consider implementing a generic approach in TEAM Engine to re-run single TestNG tests.

**Comment by dstenger** [comment]
So, if there are not objections, I propose to close this issue.
