### ISSUE TITLE
Failing tests do not report performed requests

### ISSUE THREAD

**Issue by aaime** [opengeospatial/teamengine#272]
A failing test does not provide, in the report, the request that has been performed against the server.

![selezione_021](https://user-images.githubusercontent.com/325433/33078866-420e16c6-ced4-11e7-82ce-b85ec293a10b.png)

**Comment by dstenger** [comment]
Thank you for reporting. We will do further investigation.

**Comment by keshav-nangare** [comment]
The request URI is missing in above Report.

I have fixed this issue now the request URI will appear in the testDetail report.

![localhost 8080 teamengine reports ogctest s0150 result describeunknownfeaturetype78 html describeunknownfeaturetype78](https://user-images.githubusercontent.com/14732650/33174983-234f8ec4-d080-11e7-9ca3-1310290499d2.png)

**Comment by keshav-nangare** [comment]
Fixed with this commit: 116c2f08668a4e49f0d866c02f090e93c6790a51

**Comment by aaime** [comment]
Would be nice to have both the URI being posted to, and the body. 
That said, the body is the non obvious part that cannot be figured out, but who knows, one might have an implementation that behaves in a different way depending on the URL being posted to.

**Comment by keshav-nangare** [comment]
I have updated the testdetails page with URL.

![image](https://user-images.githubusercontent.com/14732650/33259615-73f0a272-d383-11e7-8707-0c8ba3e54afd.png)

**Comment by keshav-nangare** [comment]
Fixed with this commit: e31c7f1dbfa3b9faaa6fd323dd9ab6ae0488b76e

**Comment by lgoltz** [comment]
## Testing of the fix

* Build teamengine locally
*  Test environment with Docker started (https://github.com/opengeospatial/teamengine-docker)
   * with local TEAM Engine build (5.1-SNAPSHOT) and
   * ETS WFS 2.0
* Test run with [1]
* Details of failing test "invalid Geometry Operand" contains request and response

=> **Test was successful**

[1] http://cite.deegree.org/deegree-webservices-3.4-RC3/services/wfs200?service=WFS&request=GetCapabilities
