### ISSUE TITLE
HTML report: Report has additional empty column if test is skipped

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/teamengine#273]
New HTML report has additional empty column if test is skipped. This column is located on the right and thin as it is empty.

See following screenshot:
![grafik](https://user-images.githubusercontent.com/2989166/33207153-f5604188-d10c-11e7-9213-5d9463511984.png)

The additional empty column should be removed.

**Comment by keshav-nangare** [comment]
@dstenger 

I am not able reproduce this issue on my local environment.

On which environment you have tested?

**Comment by dstenger** [comment]
@keshav-nangare 

The issue occurs on current master branch (5.1-SNAPSHOT).

It is already present in the screenshot posted by you in https://github.com/opengeospatial/teamengine/issues/268#issuecomment-345206544.

**Comment by keshav-nangare** [comment]
Removed empty column from the HTML report.  da1c1b4

**Comment by lgoltz** [comment]
Successful tested with local docker environment (ETS WFS 2.0).
