### ISSUE TITLE
Enhance impementation of SOAP request to be able to handle elements in CDATA

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/teamengine#276]
Reported by https://github.com/opengeospatial/ets-wcs20/issues/24.

**Comment by keshav-nangare** [comment]
Updated the teamengine soap-builder and converted the text node to element node.

Fixed with this commit: 8517abe40a184df6ddc00917943a622985b5f6db

**Comment by lgoltz** [comment]
Successfully tested with local docker environment and requests encapsulated in CDATA and not encapsulated.
