### ISSUE TITLE
Incomplete test result (new html report) with ETS NSG WMTS 1.0

### ISSUE THREAD

**Issue by lgoltz** [opengeospatial/teamengine#277]
Tested on Beta http://cite.opengeospatial.org/te2/ with 
 * TEAM Engine 5.1
 * ETS WMTS 1.0 NSG 0.1
 * SUT: http://ips.terrapixel.com/terrapixel/cubeserv.cgi?SERVICE=WMTS&REQUEST=GetCapabilities

The test result (new html report) is incomplete, it stops after the fourth conformance class ("NSG Test A.3 - Server Test Module; Service Metadata Content Test (Requirements 4,7)") and does not contain the buttons to navigate to the old report or download the session. From the console log the result looks fine, all conformance classes are listed with a result. 

In the tomcat log the warning described in #265 is logged, the teamengine log is empty.

Problem can be reproduced with  a local docker environment (ETS WMTS 1.0 NSG 0.2-SNAPSHOT).

**Comment by dstenger** [comment]
@keshav-nangare 
Can you please analyse why the described behaviour is occurring?

**Comment by keshav-nangare** [comment]
Yes, I will investigate this issue.

**Comment by keshav-nangare** [comment]
Investigated this issue and found the problem in the xslt with xml special characters.

Fixed with this commit: e0b0ca10c0a662cec1cfc1a08afe712703f3c136

**Comment by dstenger** [comment]
If you use ```view-source:``` in Firefox, the bug can be identified:
```
            <tr bgcolor="#FFB2B2">
               <td><a href="wmtsCapabilitiesLayerStyleLegends84.html#wmtsCapabilitiesLayerStyleLegends84"
                     class="testDetailsLink"
                     id="wmtsCapabilitiesLayerStyleLegends84.html#wmtsCapabilitiesLayerStyleLegends84">wmts Capabilities Layer Style Legends </a></td>
               <td>
                  <p> The following asserts failed:
                     	<Layer>: Airports.Airports does not have a minScaleDenominator for <Style>: default for a Legend 
```

The ```Layer```and ```Style``` elements are treated as HTML elements.

In general, there are several other syntax errors in the HTML. These are corrected by Firefox automatically.

**Comment by lgoltz** [comment]
Successfully tested with local docker environment.
