### ISSUE TITLE
Fortify Issue: Path Manipulation

### ISSUE THREAD

**Issue by cmheazel** [opengeospatial/teamengine#294]
A Fortify scan of the December 28, 2017 source tree has identified 80 Path Manipulation vulnerabilities.  A path manipulation vulnerability is a situation where a user may be able to use TeamEngine to access or modify files which they should not have access to.  One approach to dealing with this vulnerability is to introduce a "ValidPath" class for managing all file system paths.  I have written such a class and integrated it into a branch of TeamEngine.  However, the criteria for which paths are valid is not clear.
1) Is this the best approach for addressing this issue?
2) How do we distinguish between valid and invalid paths?

**Comment by cmheazel** [comment]
Please review and comment on branch Fortify-Issue-307.  The changes in this branch have impacts throughout the code.  I would rather catch them earlier than latter.  Major changes are:
1) RuntimeOptions now validates arguments on all "set" operations (returning a boolean) and initializes all properties (no more null responses to a "get" operation).
2) RuntimeOptions properties are now private.  They can only be accessed through "get" and "set".
3) SetupOptions implements the same changes as were done in RuntimeOptions.
4) TEPath is used to validate file system paths.  The comments in TEPath.java file describe the rules for a valid path. 
In addition, dead code has been isolated (usually by making public operations private), and misc. other potential problems have been repaired.

**Comment by cmheazel** [comment]
This issue was briefed to the CITE Sub Committee membership at the March 2018 TC meetings.  The consensus was that it should be sufficient to run TeamEngine in a VM.  This leaves us with two actions:
1) Add a security issues section to the documentation including a discussion of path manipulation and how to counter it.
2) Complete the code modifications so that if plan A is not sufficient we will still have the code mods to fall back on.  Note that this is dependent on merging pull request 317.

**Comment by namrata-12345** [comment]
Hey can you pleases  help me on the path Manipulation issue  how to fix this issue..?

**Comment by namrata-12345** [comment]
Can you please  help me how can i fix the path manipulation  issue?

**Comment by dstenger** [comment]
@bpross-52n Can you please check if this issue is solved by https://github.com/opengeospatial/teamengine/pull/515?

**Comment by bpross-52n** [comment]
Yes, this is solved by #515.
