### ISSUE TITLE
unable to execute wcs 1.1.1 compliance test

### ISSUE THREAD

**Issue by greatzzk** [opengeospatial/teamengine#306]
Sample 1.1.1 wcs on my server:
https://ogc.webgistesting.net/server/services/wcs111/ImageServer/WCSServer?request=GetCapabilities&service=WCS&version=1.1.1

When running it against team engine production harness, I get this:
![image](https://user-images.githubusercontent.com/11200872/34899581-ad4be078-f7ae-11e7-9e55-5c88e98c461b.png)

the very first failure is to test getcapabilities request, it returns:
Test wcs:GetCapabilities_MinimalRequest type Mandatory default result Passed (s0058/d1e356_1/d1e679_1)

Assertion: Verify that when a GetCapabilities request with only mandatory
           parameters is submitted, the response is valid XML that validates
           against the WCS 1.1.1 GetCapabilities schema.

Message d1e2820_1:
   Using KVP encoding.

Request d1e2844_1:
   Method: GET
   URL: service=WCS&request=GetCapabilities&version=1.1.1
Error in call to extension function {public org.w3c.dom.NodeList com.occamlab.te.TECore.request(org.w3c.dom.Document,java.lang.String) throws java.lang.Throwable}: Exception in extension function java.net.MalformedURLException: no protocol: ?service=WCS&request=GetCapabilities&version=1.1.1
Result: Failed

The URL in log looks like having problems. My service should be good... at least for the getCapabilities request.

**Comment by lgoltz** [comment]
@greatzzk Please check your capabilities. The target namespace of the WCS 1.1.1 schema is http://www.opengis.net/wcs/1.1. That's why you have to set the default  namespace to this namespace,  not http://www.opengis.net/wcs/1.1.1 as in you capabilities.

That should be the reason why the URL as well as other detail cannot be parsed from the capabilities as you can see in the test details of `wcs:GetCapabilities-main`.

**Comment by greatzzk** [comment]
@lgoltz , thanks for the reply.
We referred to doc: 07-067r2_Web_Coverage_Service_WCS_version_1.1.1.pdf when doing the development.
There is an getCapabilities operation example at page 20, section 8.4:
![image](https://user-images.githubusercontent.com/11200872/35069928-7d50f71a-fb90-11e7-90d2-62ecaa9499b9.png)
According to the picture above, it uses http://www.opengis.net/wcs/1.1.1 rather than http://www.opengis.net/wcs/1.1

**Comment by lgoltz** [comment]
@greatzzk I've moved this issue to the tracker of the ETS WCS 1.1: https://github.com/opengeospatial/ets-wcs11/issues/36
