### ISSUE TITLE
Status color of tests in left frame

### ISSUE THREAD

**Issue by heidivanparys** [opengeospatial/teamengine#308]
There seems to be an issue with the color of the squares when there are no failed tests (apart from some tests where status="FAIL" and is-config="true"), see screenshot below.
 
![image](https://user-images.githubusercontent.com/11427611/35146655-ee535efe-fd0b-11e7-896e-ac8052836581.png)

The test suite executed was the GML 3.2 (ISO 19136:2007) Conformance Test Suite, on TEAM Engine 4.10, with the following results: [testng-results.txt](https://github.com/opengeospatial/teamengine/files/1646165/testng-results.txt)

Note that there is also a minor display issue when no are no failed tests: instead of 

> Failed (0%)

 it says 

> Failed (%)

**Comment by keshav-nangare** [comment]
This issue is related to #266 and Fixed in  Teamengine 5.1.

**Comment by keshav-nangare** [comment]
> Note that there is also a minor display issue when no are no failed tests: instead of

> Failed (0%)
> it says
> Failed (%)


This issue(%) is not fixed, so I will look into it.

**Comment by keshav-nangare** [comment]
Fixed with this commit: d9bdf76e411bd98d376a195d2f4cd6acadc78d16. [PR: #311]

**Comment by dstenger** [comment]
**Test**

Test with Docker environment [1].

Test GML 3.2 [1] with TEAM Engine.

Navigation to old TestNG report.

All % fields contain a digit.

-> Test successful.

[1] https://github.com/opengeospatial/teamengine-docker
[2] http://cite.deegree.org/deegree-webservices-3.4-RC3/services/gml321?service=WFS&request=GetFeature&Version=2.0.0&typenames=app:Autos
