### ISSUE TITLE
SunCertPathBuilderException

### ISSUE THREAD

**Issue by heidivanparys** [opengeospatial/teamengine#312]
When testing [GetCapabilities.txt](https://github.com/opengeospatial/teamengine/files/1681596/GetCapabilities.txt) against the WFS 2.0 (ISO 19142:2010) Conformance Test Suite, the following exception occurs in the preconditions, causing all tests to fail/be skipped: `javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target`

The service endpoint is located at https://services.kortforsyningen.dk/ .

![image](https://user-images.githubusercontent.com/11427611/35622370-edf769f2-0687-11e8-95b9-0dcb9b825211.png)

![image](https://user-images.githubusercontent.com/11427611/35622385-fc3dd532-0687-11e8-8001-c7fe90c6743f.png)

**Comment by lgoltz** [comment]
@heidivanparys Thank you for reporting. This is one of the topic we are currently working on (s. #255).

Can you provide the capabilities URL of the service you tested? Furthermore it would be good to know if you tested locally on production or beta.

**Comment by heidivanparys** [comment]
The capabilities URL is http://services.kortforsyningen.dk/ps_inspire_gml321?REQUEST=GetCapabilities&SERVICE=WFS

I tested on http://cite.opengeospatial.org/teamengine/

**Comment by lgoltz** [comment]
I've tested with http://services.kortforsyningen.dk/ps_inspire_gml321?REQUEST=GetCapabilities&SERVICE=WFS but the test fails due to an unexpected CRS syntax (as described in https://github.com/opengeospatial/ets-wfs20/issues/96).

**Comment by heidivanparys** [comment]
Yes that's true. I modified the Capabilities file to have a correct CRS syntax and tested with [that one](https://github.com/opengeospatial/teamengine/files/1681596/GetCapabilities.txt) (see the also first comment in this issue: ), so I could test while waiting for the service to be updated.

**Comment by lgoltz** [comment]
Ok, sorry, I've read this over...

Now I'm able to reproduce the problem on [production](http://cite.opengeospatial.org/teamengine/) as well as [beta](http://cite.opengeospatial.org/te2/). 
I've also tested in a local setup (docker environment) with the same versions as on production (ETS WFS 2.0 1.26 and TEAM Engine 4.10) and the failure does not occur. As the DescribeFeatureType request is secured the following error occurred: 
```
Server returned HTTP response code: 500 for URL: https://services.kortforsyningen.dk/ps_inspire_gml321?service=WFS&version=2.0.0&request=DescribeFeatureType
```

**Comment by heidivanparys** [comment]
There is user authentication on the service, see also https://kortforsyningen.dk/indhold/login-https-og-ssl, which explains errors when calling anything else then GetCapabilities.

**Comment by dstenger** [comment]
@heidivanparys 
I tested your provided resource [1] against TEAM Engine on production [2] and no SSL error occurs any more.
Did you update the SSL configuration on your server?
Can you please confirm if the reported bug is solved? If this is the case, the issue can be closed.

[1] https://github.com/opengeospatial/teamengine/files/1681596/GetCapabilities.txt
[2] http://cite.opengeospatial.org/teamengine/

**Comment by dstenger** [comment]
@heidivanparys Are there any open questions left? Otherwise, we can close this issue.

**Comment by heidivanparys** [comment]
Hi, as far as know the SSL configuration has not been changed. The issue seems to be solved, I also tested again, so yes, the issue can be closed.
