### ISSUE TITLE
Circular dependencies

### ISSUE THREAD

**Issue by cmheazel** [opengeospatial/teamengine#315]
CtlEarlReporter.java imports com.occamlab.te.spi.vocabulary.  So the pom for teamengine-core has a dependency on teamengine-spi.  As a result, classes within teamengine-spi cannot use classes from teamengine-core since that would set up a circular dependency (spi is dependent on core which is dependent on spi).  As a mater of principle (and good coding practice) I would think that core classes should be available to all packages.

Immediate issue, I cannot re-use the TEPath class from core to validate paths in spi classes.  

Thoughts?  Solutions?

**Comment by dstenger** [comment]
I agree, teamengine-spi can have a dependency to teamengine-core. But, teamengine-core should never have a dependency to teamengine-spi.

So, the code has to be refactored.

**Comment by cmheazel** [comment]
Created branch Fortify-Issue-315.
CtlEarlReporter.java (in core) imports terms from com.occamlab.te.spi.vocabulary.  The vocabulary package does not import any spi classes.  Therefore, this branch will move the vocabulary package from spi to core.  That will remove the core dependency on spi.

**Comment by dstenger** [comment]
Branch has already been merged to master.
