### ISSUE TITLE
OpenAPI

### ISSUE THREAD

**Issue by cmheazel** [opengeospatial/teamengine#316]
Created the OpenAPI-Experiment branch.
One approach to compliance testing for WFS 3.0 is to drive the test using the OpenAPI description of the service.  This branch will be used to explore the use of TeamEngine to perform those tests.

**Comment by dstenger** [comment]
@cmheazel This issue should be outdated as https://github.com/opengeospatial/ets-ogcapi-features10 exists? If you agree, please close the issue.

**Comment by cmheazel** [comment]
Agreed.  Closing.
