### ISSUE TITLE
Add capability for frequent testing

### ISSUE THREAD

**Issue by bermud** [opengeospatial/teamengine#321]
If want to allow testing of services (software instantiations) - we might need to add the capability to test the server in a frequent basis. It should be random. For example test in window of every 15-30 days.

**Comment by cmheazel** [comment]
Isn't that GeoHealthCheck?

**Comment by dstenger** [comment]
Yes, GeoHealthCheck is one option.
Also, those two issues cover this topic:
* https://github.com/opengeospatial/teamengine/issues/318
* https://github.com/opengeospatial/teamengine-integration-testing/issues/24

However, this issue should clarify what part/functionality of TEAM Engine shall be tested frequently:
* TEAM Engine REST interface
* TEAM Engine Web Browser Interface (then, different types of web browsers are important)
* Test suites itself
* ...

#318 should cover all of those cases.

Thus, I propose to close this issue.

**Comment by ghobona** [comment]
2021-02-01 team meeting

Frequent testing of software instances is out of scope of the Compliance Program at the moment. However, it could be an area for future offerings/services. It would therefore be useful to review   [GeoHealthCheck](https://github.com/geopython/GeoHealthCheck) and the related [teamengine-monitor](https://github.com/opengeospatial/teamengine-monitor).

@dstenger Demonstrated regular testing of team engine and test suites through Jenkins.

TODO @ghobona to review [GeoHealthCheck](https://github.com/geopython/GeoHealthCheck) and the related [teamengine-monitor](https://github.com/opengeospatial/teamengine-monitor).

**Comment by ghobona** [comment]
Having reviewed GeoHealthCheck and the related teamengine-monitor, they are of scope of current priorities.

This issue is therefore closed.
