### ISSUE TITLE
TEAM Engine code sprint at OSGeo Code Sprint in Bonn, Germany (2018-03-20)

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/teamengine#322]
Hi all,

We would like to invite you to a TEAM Engine code sprint at OSGeo Code Sprint in Bonn, Germany on 20th of March 2018.

Everyone interested in TEAM Engine (from user to developer) is invited to participate. This will be a great opportunity for you to get involved and improve TEAM Engine and to get to know this tool better.

We plan to work on a selection of following topics:
- Improve testing strategies for TEAM Engine and/or test suites (https://github.com/opengeospatial/teamengine/issues/318).
- Implement display of hierarchies in new HTML report of TEAM Engine (https://github.com/opengeospatial/teamengine/issues/319).
- Introduction of teamengine-statistics project (https://github.com/opengeospatial/teamengine-statistics/issues/11).

Also, you are welcome to bring in your own ideas.

The referenced issues can be used to have discussions about single topics prior to the code sprint.

Instructions about how to get there and how to register can be found here: https://wiki.osgeo.org/wiki/OSGeo_Code_Sprint_2018

If you would like to participate, please write me an short email. By that, it is easier to find each other and to organize workplaces for everyone.
Of course, it is also possible to participate spontaneously. Just look for us in Basecamp then.

We are looking forward to improve TEAM Engine with you together!
Dirk

**Comment by lgoltz** [comment]
## Summary

We discussed the test strategies for test suites (described in https://github.com/opengeospatial/teamengine/issues/318#issuecomment-374566241) and  enhanced the existing tests for  ETS WFS 2.0.

Furthermore we worked on issue https://github.com/opengeospatial/teamengine/issues/319 and enhanced the transformation from the CTL log to the EARL report by mapping undefined hierarchies. In addition some bugs was fixes in the transformation. See https://github.com/opengeospatial/teamengine/issues/319#issuecomment-375204556

Some interesting conversations gave some new ideas for enhancements:
 * Signation of test results to make the validation result more official
 * Logging via SSH key to ensure that only authorized 'workers' can execute a validation.
In general TEAM Engine could be interested for data provider who wants to validate the generated data before providing or using them. The step of validation is usually not done by a person in this case.
