### ISSUE TITLE
New HTML report of CTL test suites: Inherited failures are not marked but counted as usual failures

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/teamengine#331]
Inherited failures are not marked but counted as usual failures.

Extracted from: https://github.com/opengeospatial/teamengine/issues/319#issuecomment-377217091

**Comment by dstenger** [comment]
Proposal shall be implemented.

**Comment by keshav-nangare** [comment]
Updated the new HTML report and ignored the inheritedFailure test counting from the failure. Also changed the background color of the `INHERITEDFAILURE` test. We can see in screenshot the gray color represents the inherited failure tests.

![image](https://user-images.githubusercontent.com/14732650/43205548-3f964a92-9041-11e8-8346-491b520c3101.png)

**Comment by dstenger** [comment]
I propose following changes:
* Mark inherited failures with bright red.
* If there are any inherited failures add following column to report (right below name of conformance class and to the right of "Fail" column).
  * ```Inherited fail:```
  * This new column contains count of all inherited failures.
  * Color of new column is also bright red.
  * Column shall just appear if there are any inherited failures.
  * "Total tests" must be a sum of Pass + Fail + Inherited fail + Skip.

**Comment by keshav-nangare** [comment]
Updated the new HTML report according to the proposal.

![inheritedfail_new_column](https://user-images.githubusercontent.com/14732650/43837134-396a7874-9b35-11e8-8033-e5e170fb30dd.png)
![newhtmlreport](https://user-images.githubusercontent.com/14732650/43837135-39d38544-9b35-11e8-8205-d2d810d02361.png)


@dstenger 

Can you please review this changes?
