### ISSUE TITLE
The wms-client13 test shows the one test failure in table even all the tests are passed.

### ISSUE THREAD

**Issue by keshav-nangare** [opengeospatial/teamengine#344]
This issue is originally reported in the https://github.com/opengeospatial/ets-wms-client13/issues/38.

There are some coverage files is present in the `teamengine-web/resources` module which is used by the ets-wms-client13. These file cotains the layer `cite:Terrain` i.e. the reson of this in correct count of failure test. By removing this layer then issue will resolve.

**Comment by keshav-nangare** [comment]
Fixed with commit: 9e14c997f7086fd62c3dc4981d89aeed50b3c045 [PR: #345 ].

**Comment by keshav-nangare** [comment]
@dstenger 

Can you please verify this changes?

**Comment by dstenger** [comment]
# Functional test

Started test suite with Docker and used QGIS 3.2 to execute all tests.

The result shows just passed tests.
