### ISSUE TITLE
Refactor folder structure of Maven project

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/teamengine#346]
Following can be improved:
* Remove/move obsolete folder and files (e.g. build/ and doc/).
* Parent-pom should not contain src folder plus modules but just modules.
* Check if directory structure of modules matches conventions.

Hints:
* https://maven.apache.org/guides/introduction/introduction-to-the-standard-directory-layout.html

**Comment by dstenger** [comment]
**Remove/move obsolete folder and files (e.g. build/ and doc/).**

doc folder might be moved to other repository or integrated into site documentation.

build folder might be moved to other repository (e.g. teamengine-builder) or removed completely.

@bermud What are your thoughts about this?

**Parent-pom should not contain src folder plus modules but just modules.**

src folder is used for site documentation and integration tests. So far, this usage is fine for me and must not be refactored to a sub module.

**Check if directory structure of modules matches conventions.**

All directory structures look fine.

**Comment by ghobona** [comment]
I agree to remove the 'build' folder.

We should keep the 'doc' folder in the teamengine repository because it provides a useful step-by-step guide for new users and developers of TEAM Engine.

**Comment by dstenger** [comment]
However, the content of the 'doc' folder seems to be a duplicate to other documentation (e.g. in 'src/site' folder): https://opengeospatial.github.io/teamengine/installation.html
I think the content of those documents shall be merged or at least put to a central location.
