### ISSUE TITLE
Teamengine failed to generate new HTML report if the testInputs are empty.

### ISSUE THREAD

**Issue by keshav-nangare** [opengeospatial/teamengine#348]
This issue originally reported in ets-wms-client13 here: https://github.com/opengeospatial/ets-wms-client13/issues/23

If the test-inputs is not passed then it should be set to empty and teamengine should generate the new HTML report.

**Comment by keshav-nangare** [comment]
@dstenger 

Can you please provide your thought on this?

**Comment by dstenger** [comment]
Configuration of CCs must still be done.

**Comment by dstenger** [comment]
Can be verified when https://github.com/opengeospatial/ets-wms-client13/issues/23 is done.
