### ISSUE TITLE
Add ETS form validation

### ISSUE THREAD

**Issue by keshavnangare** [opengeospatial/teamengine#354]
Reference from: https://github.com/opengeospatial/ets-kml22/issues/11#issuecomment-416521111

**Comment by keshav-nangare** [comment]
Fixed with this commit: 3b1de37e5433a86b52cece64676e660b7ba60d79

**Comment by dstenger** [comment]
Please review the comment in the PR.

**Comment by keshav-nangare** [comment]
Updated the PR with suggested changes.
