### ISSUE TITLE
WCS test is slow due to repeated schema loading

### ISSUE THREAD

**Issue by dgtombs** [opengeospatial/teamengine#357]
Running the WCS test (and perhaps others) using TEAM Engine is slow because XMLValidatingParser repeatedly loads the same schemas. I am filing the bug against TEAM Engine instead of the WCS test suite because I don't think the latter could do anything about it.

I am trying to test a private WCS that offers quite a few coverages. I canceled this test after an hour of just verifying the first requirement. It probably would have run for multiple more hours.

### Steps to reproduce:

1. Run the WCS 2.0.1 test against http://ows.eox.at/cite/mapserver.

### Actual Result

The test takes over 20 minutes to run. Using a local TEAM Engine instance, I was able to determine that the vast majority of this time was spent in the `SF.newSchema()` call in `XMLValidatingParser.validateAgainstXMLSchemaList()`. XMLValidatingParser ended up loading the same set of schemas 69 times, with each time taking about 19 seconds.

**Comment by lgoltz** [comment]
Thank you for reporting. As far as I see this issue is related to ets-wcs20 and not the teamengine. As far as I see the issue https://github.com/opengeospatial/ets-wcs20/issues/35 handles the same problem.
I think we can close this issue as duplicate.

**Comment by dgtombs** [comment]
Ah, I see that is the same issue.

The proposed solution in opengeospatial/ets-wcs20#35 seems more like a workaround, though. I was thinking that XMLValidatingParser could be improved to cache the Schema object somehow.

**Comment by dgtombs** [comment]
FYI, I was able to prototype a schema caching solution that brought the http://ows.eox.at/cite/mapserver test execution time down to about 30 seconds!

Would you be interested in incorporating a caching solution like this? I could talk to my management about implementing it cleanly and contributing it.

**Comment by dgtombs** [comment]
By the way, I found that [w3.org artificially delays requests for schemas](https://www.w3.org/Help/Webmaster#slowdtd). This probably "causes" much of the current slowness--but as they say, the fix is caching.

**Comment by dstenger** [comment]
Fix was successfully tested with http://ows.eox.at/cite/mapserver?service=WCS&version=2.0.1&request=GetCapabilities (all CCs were selected).
