### ISSUE TITLE
The WMS client test on production does not detect requests

### ISSUE THREAD

**Issue by robinhoutmeyers** [opengeospatial/teamengine#361]
Scenario:
- log in on http://cite.opengeospatial.org/teamengine/viewSessions.jsp and create a new session for the WMS client
- start the WMS client test
=> keeps endlessly saying "Executing tests... " without ever asking to start a client and providing a WMS URL

**Comment by lgoltz** [comment]
@robinhoutmeyers This failure is already described in #301 and not solved by now.

Unfortunately I'm not able to restart the application container right now. I will do this as soon as possible and let you know.

**Comment by lgoltz** [comment]
Application server restarted.

@robinhoutmeyers Can you test if the WMS client tests works and close this issue?

**Comment by robinhoutmeyers** [comment]
The WMS client test now proceeds with the page that lists the WMS URL and requests to be executed, but none of my requests are recorded; it doesn't detect my GetCapabilities, GetMap and GetFeatureInfo requests, although I can access and visualize the data in my client.

**Comment by lgoltz** [comment]
> The WMS client test now proceeds with the page that lists the WMS URL and requests to be executed, but none of my requests are recorded; it doesn't detect my GetCapabilities, GetMap and GetFeatureInfo requests, although I can access and visualize the data in my client.

Same behaviour with QGIS on production.

@robinhoutmeyers Can you use the [beta environment](http://cite.opengeospatial.org/te2)  until thi is fixed?

**Comment by robinhoutmeyers** [comment]
@lgoltz  OK - it now works but the test engine requires to execute a map request for a terrain layer, which is not present in the WMS capabilities. Probably a test issue?

**Comment by lgoltz** [comment]
>OK - it now works 

On production or beta?

> but the test engine requires to execute a map request for a terrain layer, which is not present in the WMS capabilities. Probably a test issue?

This is already described in https://github.com/opengeospatial/ets-wms-client13/issues/32 and fixed in version 1.4 of the test suite (which is not deployed yet).

**Comment by dstenger** [comment]
@robinhoutmeyers Are there still any open questions?

**Comment by robinhoutmeyers** [comment]
Hi, not from my side; thank you for the follow-up!

Kind regards,
Robin
