### ISSUE TITLE
Downloaded session contains full path

### ISSUE THREAD

**Issue by lgoltz** [opengeospatial/teamengine#380]
Currently a session downloaded from the TEAM Engine Web GUI contains the full path of the server: 

```
lyn@lyn:/tmp/s0001$ tree -d
.
└── root
    └── te_base
        └── users
            └── lyn
                └── s0001
```

Expected is that the zip file starts at the directory containing the session:
```
lyn@lyn:/tmp/s0001$ tree -d
.
└── s0001
```

**Comment by keshav-nangare** [comment]
Fixed with this PR: #384.

**Comment by lgoltz** [comment]
Implementation looks fine. I've added the session folder in the zip archive. 
@keshav-nangare  Can you recheck?

**Comment by keshav-nangare** [comment]
Changes tested successfully with a local docker environment.
