### ISSUE TITLE
Provide instructions about how to integrate tests with an IDE

### ISSUE THREAD

**Issue by bermud** [opengeospatial/teamengine#392]
Review these instructions 
https://github.com/opengeospatial/ets-wfs30/blob/master/src/site/asciidoc/how-to-run-the-tests.adoc

and port to here:

https://github.com/opengeospatial/teamengine/blob/master/src/site/markdown/integration-ide.md

**Comment by keshav-nangare** [comment]
Fixed with this commit: 0793f9a314cc09d03e6bf816fce8479f8e6f53d7
