### ISSUE TITLE
Replace OSGEO logo

### ISSUE THREAD

**Issue by bermud** [opengeospatial/teamengine#394]
We should use this logo https://github.com/OSGeo/osgeo/tree/master/incubation/community

**Comment by dstenger** [comment]
Task: Detect where and if an OSGeo logo is used.

**Comment by keshav-nangare** [comment]
@dstenger 

I can find some reference OSGEO logo in teamengine site document.
We can find the logo in site directory and sit.xml file as below:
https://github.com/opengeospatial/teamengine/blob/0793f9a314cc09d03e6bf816fce8479f8e6f53d7/src/site/site.xml#L25-L29
https://github.com/opengeospatial/teamengine/tree/master/src/site/resources/images

Also, we can see this logo in teamenigne github.io page:
http://opengeospatial.github.io/teamengine/

**Comment by dstenger** [comment]
@keshav-nangare Can you please replace this file with the new logo?
https://github.com/OSGeo/osgeo/blob/master/incubation/community/OSGeo_community.png

**Comment by keshav-nangare** [comment]
Fix with #427 PR.
