### ISSUE TITLE
OSGeo Graduation: Create documentation providing sufficient detail for an experience programmer to contribute patches or a new module in accordance with the project’s programming conventions

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/teamengine#407]
Please also see #393.

**Comment by dstenger** [comment]
Pull requests are the common way to contribute code to project.

TODO: Create wiki page.

**Comment by jodygarnett** [comment]
A CONTRIBUTING.md file is the usual GitHub convention to communicate how to contribute a patch, this has the advantage of being shown to potential contributors when they make a pull request.

This is a good place to document or link to your expectations on matters such:

- as code formatting
- any documentation or quality assurance expectations
- communicate that the work being contributed will be distributed by the OGC using an open source license (this is annoying enough that many projects end up with a contributor license agreement just to be sure).

Examples from a few OSGeo projects:

- [GeoServer CONTRIBUTING.md](https://github.com/geoserver/geoserver/blob/master/CONTRIBUTING.md)
- [PROJ CONTRIBUTING.md](https://github.com/OSGeo/PROJ/blob/master/CONTRIBUTING.md)

**Comment by ghobona** [comment]
2020-11-17 OSGeo Sprint

The page describing how to contribute to the project has been created at https://github.com/opengeospatial/teamengine/blob/master/CONTRIBUTING.md
