### ISSUE TITLE
testng-report.xsl - Fail Icons

### ISSUE THREAD

**Issue by bermud** [opengeospatial/teamengine#41]
scr -> teamengine / teamengine-spi / src / main / resources / testng-report.xsl

Paul D. reported this issue on June 24 2014

        
        <xsl:variable name="notSigHasFailCount" select="count(./class/test-method[@status='FAIL' and not(starts-with(@signature,'has'))])"/>
        
        <div class="{if ($notSigHasFailCount > 0)
          then 'testCaseFail'
          else if (($notSigHasFailCount = 0) and (count(./class/test-method[@status='PASS']) > 0))
          then 'testCasePass'
          else 'testCaseSkip'}">

**Comment by keshav-nangare** [comment]
I have tested and tried to reproduce this issue with teamengine[4.6] and GML32[1.23], but it is not reproduced.
