### ISSUE TITLE
Unable to build behind corporate proxy

### ISSUE THREAD

**Issue by dgjbge** [opengeospatial/teamengine#416]
This project does not build when run behind a corporate proxy because the core tests `validateWithMismatchedDTDList` and `parseWithSchemaListAndDifferentLocation` in `com.occamlab.te.parsers.XMLValidatingParserTest` make external HTTP calls (e.g. validateWithMismatchedDTDList make a request to schemas.opengis.net).

Would it be possible to either not make external HTTP requests (ie keep schemas local, which would allow tests to be run offline) or allow proxy settings to be sent to surefile via argline, e.g. https://stackoverflow.com/a/32294928/228971 ?

This would allow the project to be built inside corporate IT environments where developers might be unlucky enough to have to deal with proxies :-(

**Comment by dstenger** [comment]
Thank you for reporting.

Does the build work behind a corporate proxy if you are skipping the tests (`-DskipTests`)?
I agree that the test resources shouldn't come from a remote location.

**Comment by dgjbge** [comment]
Yes, skipping tests works

**Comment by dstenger** [comment]
@keshav-nangare Can you please try to remove the external references in unit tests? Instead, the resources shall be added to the repository.
