### ISSUE TITLE
Add hint to legal terms when registering to TEAM Engine

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/teamengine#420]
Hint shall appear on following page: http://cite.opengeospatial.org/te2/register.jsp

Hint shall be placed below registration fields (last field Organization).

Text for hint: "I agree to the terms of the OGC Privacy Policy at https://www.opengeospatial.org/ogc/policies/privacy"

Also, please add a check box which must be checked. Otherwise, registration cannot be completed.

**Comment by keshav-nangare** [comment]
Added hint to legal terms in Teamengine.
