### ISSUE TITLE
Documentation refers to Oracle 8 JDK that is not available

### ISSUE THREAD

**Issue by jratike80** [opengeospatial/teamengine#426]
It is not possible to get Java 8 SDK from Oracle any more and documentation in http://opengeospatial.github.io/teamengine/installation.html and https://github.com/opengeospatial/teamengine/blob/master/doc/en/index.rst#configure-java is outdated.
Documentation should point to other alternatives for getting JDK 8: Amazon Corretto, Azul Zulu, AdoptOpenJDK, Redhat OpenJDK.

I tried Corretto 8 JDK on Windows 64 and I succeeded to build Teamengine with it just fine.

**Comment by dstenger** [comment]
Thank you for reporting.
We will discuss the recommendations for JDKs.

**Comment by ghobona** [comment]
Fixed by https://github.com/opengeospatial/teamengine/pull/452
