### ISSUE TITLE
OSGeo Graduation: Code of conduct

### ISSUE THREAD

**Issue by jodygarnett** [opengeospatial/teamengine#432]
An additional requirement has been added to the checklist since the team engine first started. The OSGeo  has been very focused on diversity and wishing to ensure that open source projects provide a safe space for collaboration.

As such we ask projects adopt a code-of-conduct, which is a trend being seen industry wide. Indeed many projects have adopted a shared code of conduct (in true open source fashion this leverages the passion of a few well informed folks).

The OSGeo page on this is here: https://www.osgeo.org/code_of_conduct/

It contains the example for open source projects:

> Contributors to <project> are expected to act respectfully toward others in accordance with the https://www.contributor-covenant.org/ for open source projects.

(Where the contributor-covenant.org is one example of an established open source code of conduct)

When the team has though about this, the results of your discussion are expected to be in a CODE_OF_CONDUCT.md file. See GitHub community checklist [here](https://github.com/opengeospatial/teamengine/community) for your project.

**Comment by ghobona** [comment]
2020-11-17

@ghobona and @dstenger reviewed the Codes of Conduct and agreed to base the TEAM Engine code of conduct on the OGC's one https://www.ogc.org/ogc/policies/conduct

**Comment by dstenger** [comment]
Code of conduct file was added to the project: https://github.com/opengeospatial/teamengine/commit/64f46174eed26d8bc77fbd98aec4282bc06c9da5

GitHub community checklist recognizes the code of conduct: https://github.com/opengeospatial/teamengine/community
