### ISSUE TITLE
'Test INPUT' in HTML report displays wrong information

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/teamengine#435]
This occurs with following test suites (Beta and Production):
* WCS 2.0
* Sensor ML 1.0

A wrong service is referenced in the report.

@keshav-nangare Can you please try to reproduce this behavior and propose a solution how to solve it?
Can you also check if this behavior occurs with other test suites as well?

**Comment by keshav-nangare** [comment]
@dstenger 

I have debugged the issue and found the problem with the static `userInputs` variable which was persisting its value. So I have removed the static keyword which will initialize `userInputs` variable with null value for each TECore object. Please find the changes in #436 PR.
