### ISSUE TITLE
TestSuite version on API

### ISSUE THREAD

**Issue by carlospzurita** [opengeospatial/teamengine#447]
As part of the ETF testing framework, that we are using in the INSPIRE Reference Validator, a dependency on the TEAM engine WFS 2.0 TestSuite is used on its own Download Service ExecutableTestSuite. This dependency is managed using the endpoint https://cite.opengeospatial.org/teamengine/rest/suites, and the ETS is assigned the version of the current TestSuite.

We were previously able to obtain the version number directly from the URL of the TestSuite (for example https://cite.opengeospatial.org/teamengine/rest/suites/wfs20/1.34/run). But now the version is gone from this endpoint, and we encountered some errors in the initialization of the TestDriver for this ETS.

What is the easiest way to get the version number for the TestSuite now, using only the REST API?

**Comment by dstenger** [comment]
The easiest way to get the version number of the test suites is to check following site: https://cite.opengeospatial.org/teamengine/

However, we could think of providing the version numbers of the test suites via the REST interface itself. Would that help you?

CC @ghobona

**Comment by carlospzurita** [comment]
We are aware of the versioning present in the landing page on https://cite.opengeospatial.org/teamengine/, and we have used it to temporarily set it as a static value on the ETF. However, it would very useful is this could be obtained directly from the REST API, to set it automatically.

**Comment by dstenger** [comment]
I agree that it could be useful to provide this information directly via the REST API.

We will discuss this in the CITE TEAM.

**Comment by keshav-nangare** [comment]
@dstenger 

I think we have covered this in the issue https://github.com/opengeospatial/teamengine/issues/397#issuecomment-652276858. The PR for the above issue will be used to get the `Available test suites` information in the XML/JSON format which contains information about the version of the test suite.

**Comment by ghobona** [comment]
@dstenger Can we add PR https://github.com/opengeospatial/teamengine/pull/434 , which fixes Issue https://github.com/opengeospatial/teamengine/issues/397#issuecomment-652276858 , to the Team Engine 5.5 milestone?

**Comment by dstenger** [comment]
Sure, #397 was added to 5.5 milestone. This will be the next release of TEAM Engine.

**Comment by dstenger** [comment]
@carlospzurita Does the solution of #397 cover your requirements? If that is the case, I propose to close this issue.

**Comment by carlospzurita** [comment]
Dear @dstenger 

Thank you for your response. I think that this change can be useful for us, we can retrieve the TestSuite info when setting up the validator.

This PR can close this issue.

**Comment by dstenger** [comment]
We will update TEAM Engine on Production in summer 2021.

**Comment by ghobona** [comment]
2021-01-13 discussion

We are planning to add this to a v5.4.1 release of TEAM Engine on Beta. This will likely be in Q1 of 2021.
