### ISSUE TITLE
Re-executing session test sometimes does not update results

### ISSUE THREAD

**Issue by jerstlouis** [opengeospatial/teamengine#449]
A few times, while trying to re-execute the tests (instead of deleting and re-creating new session), the results don't seem to get updated (the test seems to takes time to execute, but the timestamp and results appear to be from a previous run).

**Comment by dstenger** [comment]
Thank you for reporting.

@keshav-nangare Can you please analyze the reported behavior?

**Comment by keshav-nangare** [comment]
I have added code to delete to result and testng directory for re-execution of the session. Please find the changes in #454 PR.
