### ISSUE TITLE
TE Log.xml need to clearly report conformance classes

### ISSUE THREAD

**Issue by bermud** [opengeospatial/teamengine#45]
Logs should explictly report the confromance classes that have been tested and
the result. Currently is not easy to extract these information.
Maybe the results in the log.xml file should look something like:

```
<endtest result=""6"">
<conformance_class name=""Simple WFS"" result=""0""/>  
<conformance_class name=""Basic WFS"" result=""1""/>  
<conformance_class name=""Transactional WFS"" result=""1""/>  
<conformance_class name=""Locking WFS"" result=""1""/>  
</endtest>  
...
```

This may also require to provide some extra documentation in the main ctl or
configuration file.
[Originally reported in the OGC CITE issue tracker: issue #851](https://portal.opengeospatial.org/services/srv_public_issues.php?call=viewIssue&issue_id=851)  

_Opened: 2013-08-08 09:43:13 Last Updated: 2014-01-07 12:00:12_

**Comment by bermud** [comment]
@upendra-sachan, Please document how are we extracting the conformance classes form CTL tests, in order to generate the new reporting.

**Comment by bermud** [comment]
@keshav-nangare,  please look at the WFS 1.1.0 and WMS 1.3 tests

**Comment by bermud** [comment]
@keshav-nangare, please let me know of any questions or required clarifications.

**Comment by bermud** [comment]
Maybe add ctl:conformance-class to explicitly designated what test is a conformance class. I know it will require a change in the CTL tests and TE.

**Comment by bermud** [comment]
@keshav-nangare. The plan is  as follows:
 
Add three attributes to XML CTL:

- name
- isConformanceClass
- isBasic

Do changes in the WMS 1.3 and WFS 1.1 tests to represent conformance classes explicitly and bring that information to the logs.

Conformance classes for WMS 1.3 are here:
http://cite.opengeospatial.org/te2/about/wms/1.3.0/site/
- Basic X
- Queryable
- Raster ELEVATION
- Vector ELEVATION
- TIME

Conformance classes for WFS 1.1 are here:
http://cite.opengeospatial.org/te2/about/wfs/1.1.0/site/
- Basic X
- Transaction
- Locking
- XLink

Those with an X are the basic conformance classes.

**Comment by dstenger** [comment]
@bermud 
Are further actions required?
Otherwise, the issue can be closed.

**Comment by bermud** [comment]
This has been already implemented!
