### ISSUE TITLE
The test Entry Point / Sign In page is very confusing

### ISSUE THREAD

**Issue by jerstlouis** [opengeospatial/teamengine#450]
From the look of the page at https://cite.opengeospatial.org/te2/ with the smiling guy and the many blocks of text, and then the list of different standards for which you might think you can access different tests for each, it is very difficult to realize that this is actually the entry point/login page, and notice the "Sign in" button at the very bottom of the page.

**Comment by dstenger** [comment]
Thank you for the input.

We will discuss this in the OGC CITE team.

**Comment by ghobona** [comment]
@dstenger @keshav-nangare Let's move the sign-in block to the top in the next Beta release.

**Comment by jerstlouis** [comment]
@ghobona and suggestion to make it bigger, and put that big "Sign In" next to some text along the lines of "Team Engine Online Testing" (for all tests).

**Comment by ghobona** [comment]
2021-02-18 meeting

Agreed that on the viewSessions page we would remove 'sign-in' and 'create an account' from the upper-right when 'Log-in' is on the middle-left of the page.

Also agreed to make the font size of  'sign-in' and 'create an account' bigger.

Also agreed to add a line to the Registration page saying "All fields are required".

**Comment by jerstlouis** [comment]
@ghobona To clarify, my original concern was not about the View Sessions page, which only has the Login menu, but the https://cite.opengeospatial.org/te2/ page, which is confusing to the user because the top of the page looks like a big ad, and a big table of tests follows, and at the very bottom a tiny Sign in button brings you to the View Sessions page.

**Comment by ghobona** [comment]
@jerstlouis Yes, the `/te2` page has already been modified. We saw a demo of that earlier today. The modification led to the additional viewSessions issue. Hence the reference to viewSessions. 

We'll let you know when the fix has been uploaded to the Beta TEAM Engine..

**Comment by keshav-nangare** [comment]
Moved the `Sign in` and `Create an account` buttons to the top right corner. See the below screenshot:

![image](https://user-images.githubusercontent.com/14732650/109004030-30437580-76ce-11eb-953d-04edf8c671cc.png)

Please find the changes in the #458 PR.
