### ISSUE TITLE
Enable TEAM Engine to access protected resources (authentication)

### ISSUE THREAD

**Issue by bermud** [opengeospatial/teamengine#46]
Some servers are protected. And there are several scenarios.
- HTTP Authentication (requires username and password)
- certificate-based authentication (requires X.509 certificate)

**HTTP Authentication**
- Initially reported in the OGC CITE issue tracker: issue #852
  https://portal.opengeospatial.org/services/srv_public_issues.php?call=viewIssue issue_id=852
- Related to this issue:
  https://github.com/opengeospatial/ets-wms13/issues/27

**PKI Authentication**
- Reported on the CITE forum May 2016
  http://lists.opengeospatial.org/pipermail/cite-forum/2016-May/001608.html

_Opened: 2013-08-12 16:05:31 Last Updated: 2013-09-23 11:19:15_

**Comment by keshav-nangare** [comment]
If the server's are protected then we can pass the username and password in following way:   
     
1. Pass username and password through the URL:
                   E.G. https://username:password@www.example.com/ <br/>
                   Ref: https://en.wikipedia.org/wiki/Basic_access_authentication

2. We can pass username and password through the header: 
               -  Following is the code snippet that will show how we can set the header-
                      
			URL url = new URL("https://192.168.2.51:8181/ogc_auth/ProtectedSites-1.xml");
			String loginPassword = "username:password";
			System.out.println("Protocol: "+ url.getProtocol());
			BASE64Encoder enc = new sun.misc.BASE64Encoder();
			String encoded = enc.encode( loginPassword.getBytes() );

			URLConnection conn = url.openConnection();
			conn.setRequestProperty ("Authorization", "Basic " + encoded);

-  Created the sample webapp with the basic authentication and added one resources file into app, so we can test the test-suite using this resource URL.

This above scenario is working fine when we are passing the username and password through the header.

**Comment by bermud** [comment]
@rjmartell,  Please take a look at this issue/solution and check that it is consistent with the work done in Testbed 12.

**Comment by rjmartell** [comment]
It's very unlikely that any OGC service will accept user credentials embedded in the request URI (and in fact this is discouraged in RFC 3986). The HTTP Basic mechanism ([RFC 7617 ](https://tools.ietf.org/html/rfc7617)) is commonly supported, though. And authentication can be performed preemptively (without awaiting a challenge).

How then are user credentials submitted to teamengine for inclusion in service requests? Presumably they would be conveyed by form fields, URI parameters, etc. However, these should only be provided over a **secure connection** to teamengine (HTTP over TLS, aka `https`).
