### ISSUE TITLE
Fail to generate report because of invalid character

### ISSUE THREAD

**Issue by keshavnangare** [opengeospatial/teamengine#465]
Reference: https://github.com/opengeospatial/ets-wcs10/issues/54#issue-813846027

As per the screenshot, the report generation failed because of an invalid character present in the file.

**Comment by keshav-nangare** [comment]
If the exception is thrown while transforming like "An invalid XML char", then each line from that file will be read and send to stripped the invalid characters. If the line contains invalid characters and `<content>` element, the text in `<content>` element is placed within `<![CDATA]]>` block. Finally, it will return as a string by removing `</log>` from it and the file will be rewritten with a valid string. It will able to generate the old test report.

Please find all the changes in #466 PR.
