### ISSUE TITLE
Incorrect response on beta instance TestSuites list

### ISSUE THREAD

**Issue by carlospzurita** [opengeospatial/teamengine#469]
During integration of the beta instance on https://cite.opengeospatial.org/te2 we have detected there is an error on the response from the service. The request to rest/suites return an incorrect endpoint for the ETS.

`<testSuite><title>OGC Web Coverage Service 1.1.1 - Executable Test Suite</title><version>1.15</version><endpoint>https://cite.opengeospatial.org/te2/rest/suiteswcs11/</endpoint><etscode>wcs11</etscode></testSuite>`

The `endpoint` tag should be pointing to `https://cite.opengeospatial.org/te2/rest/suites/wcs11/`.

Also we noticed that this response is different than the one we were getting from the production instance on https://cite.opengeospatial.org/teamengine, at least with an user agent different than a browser `<li><a href="suites/wcs/" id="wcs" type="text/html">OGC Web Coverage Service 2.0.1 - Executable Test Suite</a></li>`.

Is this format going to be replaced by the te2 one on the next release?

**Comment by carlospzurita** [comment]
We see that the issue is also present in the request to https://cite.opengeospatial.org/teamengine/rest/suites

`<testSuite><title>Conformance Test Suite - OGC Web Map Service 1.3.0</title><version>1.25</version><endpoint>https://cite.opengeospatial.org/teamengine/rest/suiteswms13/</endpoint><etscode>wms13</etscode></testSuite>`

**Comment by dstenger** [comment]
Thank you for reporting.

Can you please summarize what request you submitted?
I suppose it was GET https://cite.opengeospatial.org/te2/rest/suites
with one of those headers:
* Accept: application/xhtml+xml
* Accept: application/xml
* Accept: application/json

When just requesting with a web browser there seems to be a random behavior (XHTML or XML) are returned.
I also agree that the XML site generates a wrong value for element endpoint (as described by you above). The JSON site seems to contain the same bug.

**Comment by carlospzurita** [comment]
This response can be obtained using directly cURL the headers are set automatically to the following
```
curl -v -k https://cite.opengeospatial.org/te2/rest/suites

> GET /te2/rest/suites HTTP/1.1
> Host: cite.opengeospatial.org
> User-Agent: curl/7.67.0
> Accept: */*
```
The issue was originally encountered on the INSPIRE validator, which performs the request as to the service as XML.

**Comment by dstenger** [comment]
Thank you. So, in this case the server decides which mime-type to return.
It seems that there is a random behavior here as it returns XML or JSON.
However, I would not consider this as a bug.

So, the bug described in this issue is that there is a wrong value for endpoint in XML and JSON mime-type (/ is missing).

Do you agree with that?

**Comment by carlospzurita** [comment]
Thank you for reviewing this. I agree that there is no bug on the behaviour of the service for the `Accept` header, but there is an incorrect value on the XML and JSON mime-type responses related to the endpoint of the TestSuite.

**Comment by dstenger** [comment]
Fix and pull request were created: https://github.com/opengeospatial/teamengine/pull/475

**Comment by lgoltz** [comment]
BVranch: https://github.com/opengeospatial/teamengine/commit/75e0cfa7f1af0cd91d39f4dafe6278cc57a8eb85

**Comment by carlospzurita** [comment]
We tested the situation on this issue and we see that the URI is still appearing with an error on the TEAM engine response. Do you have any news on this?

Also, we noticed that the default response format has been changed from XML to JSON. Do you intend on keeping it this way? Are there any other updates planned for the service response?

Thank you and kind regards

**Comment by dstenger** [comment]
Unfortunately, this fix has not been released yet and we are planning the next release for Q4.

No, we did not change the default format. Can you explain more in detail where the default format changed (e.g. what requests)? Which default format would you prefer?

**Comment by carlospzurita** [comment]
A week ago we have detected that the request to https://cite.opengeospatial.org/teamengine/rest/suites, without an `Accept` header set, was returning a JSON encoded response instead of XML. We now see that the response is again XML.

Is the response format fixed by default? We would be fine either with JSON or XML, but it would be good to have a default behaviour, given that right now we are not in condition to set the header to the request by ourselves.

**Comment by dstenger** [comment]
No, there have not been any changes on TEAM Engine in the last week(s). Thus, the server responds with a random behavior here (which is acceptable from a technical point of view).

Why don't you pass an `Accept` header making sure that the correct Content Type is returned for your use case?
So far, we have not defined a default behavior. It that is important for you, please create a new issue for that.
