### ISSUE TITLE
Empty Earl-report

### ISSUE THREAD

**Issue by jyrkka** [opengeospatial/teamengine#480]
Earl report shows zero count for all test result types ('testsPassed', 'testFailed' etc.) in report when running tests in ubuntu.

Root cause for the problem is the if-statement in here:
https://github.com/opengeospatial/teamengine/blob/a3a52cec199907df50223601ff52ddb19cbc26a9/teamengine-core/src/main/java/com/occamlab/te/CtlEarlReporter.java#L612

The temporary directory name is 'tmp' instead of 'temp'. When adding branch for 'tmp' everything works fine.

**Comment by jyrkka** [comment]
Just figured out a workaround. Overriding "java.io.tmpdir" system property with a directory containing "temp" solves the problem also.

**Comment by dstenger** [comment]
Thank you for reporting.
We will check if the referenced code can be improved.

**Comment by bpross-52n** [comment]
@jyrkka I am trying to reproduce the behavior. Could you tell me how you tested, so I can try out a possible fix? Thanks!

**Comment by jyrkka** [comment]
I was running tests using those "all-in-one"-jars. For example "java -jar ets-wms13-1.3-aio.jar test-run-props.xml"

Content of the props.xml is following:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<properties version="1.0">
    <comment>Test run arguments for WMS 1.3</comment>
    <entry key="acceptMediaType">application/zip</entry>
    <entry key="capabilities-url">PUT_CABABILITY_URL_HERE</entry>
    <entry key="updatesequence">auto</entry>
    <entry key="high-updatesequence">NA</entry>
    <entry key="low-updatesequence">NA</entry>
    <entry key="basic">basic</entry>
    <entry key="queryable">false</entry>
    <entry key="raster_elevation">false</entry>
    <entry key="vector_elevation">false</entry>
    <entry key="time">false</entry>
    <entry key="recommended">false</entry>
</properties>
```

With the above command, tests are run but the resulting report is empty.
But when running tests for example with command  "java -Djava.io.tmpdir=/tmp/temp_123454 -jar ets-wms13-1.3-aio.jar test-run-props.xml", report generated just fine.

And the reason is that the line which i pointed earlier, it does to parse the log files since in my system there is "tmp" folder instead of "temp" folder.
