### ISSUE TITLE
Replace previous OGC logo with the new OGC logo

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/teamengine#483]
**Is your feature request related to a problem? Please describe.**

The OGC has a new logo, so TEAM Engine should be updated with the new logo.

https://ogcapi.ogc.org/img/OGC_Logo__Blue_Horizontal.svg

**Describe the solution you'd like**

Replace previous OGC logo with the new OGC logo

**Comment by ghobona** [comment]
Landing Page

- [ ] top-left logo
- [ ] Compliance Badge

All other pages

- [ ] top-left logo

**Comment by dstenger** [comment]
There might be changes necessary in this repo https://github.com/opengeospatial/teamengine-site as well.

**Comment by ghobona** [comment]
The deployed instances obtain their site content from `TE_BASE/resources/site`.

So the logos of the deployed instances have been changed there for both Production and Beta.

The next step is to change the logos at https://github.com/opengeospatial/teamengine-site.

**Comment by ghobona** [comment]
For reference, the new logos are attached.

<img width="85" alt="logo2021" src="https://user-images.githubusercontent.com/18121038/141794886-d744da69-8566-4ab3-af33-a93cc4f2f2f0.png">

![certification-logo2021](https://user-images.githubusercontent.com/18121038/141794929-22e7ac63-c517-4a95-898c-f85a3edf06ef.gif)

**Comment by ghobona** [comment]
Created a Pull Request to update the **teamengine-site** repo https://github.com/opengeospatial/teamengine-site/pull/2

**Comment by ghobona** [comment]
@kstegemoller Please update the logos on the deployed dockerized instances.

**Comment by ghobona** [comment]
Created another Pull Request, this time to update the **teamengine** repo https://github.com/opengeospatial/teamengine/pull/484
