### ISSUE TITLE
Download log Files broken?

### ISSUE THREAD

**Issue by jerstlouis** [opengeospatial/teamengine#486]
**Describe the bug**
Download log Files results in a blank page now

**To Reproduce**
Try to Download log Files from a completed OGC API - Features test
e.g. https://cite.opengeospatial.org/teamengine/downloadLog?session=s0001 in this case

**Expected behavior**
Downloading the log files.

**Comment by dstenger** [comment]
Thank you for reporting.
I am able to reproduce your problem.
We will do further analysis.

**Comment by dstenger** [comment]
@jerstlouis Can you please check if the problem is still occurring? It might have been related to problems with the environment back then which are solved by now.

**Comment by jerstlouis** [comment]
@dstenger This issue is still happening.

Clicking https://cite.opengeospatial.org/te2/viewSessionLog.jsp?session=s0004 after being logged in returns a blank file.

**Comment by jerstlouis** [comment]
@dstenger Sorry I corrected the link in my last comment, I meant the original link in the issue still returns a blank file.
I do get this problem with all sessions (e.g. https://cite.opengeospatial.org/teamengine/downloadLog?session=s0006) even though that session does work. I don't know if such URLs are still valid now?

However I was now able to Click the "Download log Files" for my session 6 from the viewOldSessionLog URL clicking "detailed old test report". I did not try other test suites.

https://cite.opengeospatial.org/te2/viewOldSessionLog.jsp?session=s0006 also returns a 500 when not logged in instead of a 401 or 404 as it should:

> HTTP Status 500 - java.lang.NullPointerException

**Comment by ghobona** [comment]
@dstenger I was able to replicate the 500 error issue on te2. Attempting to access the **viewOldSessionLog** page returns an HTTP 500 error. This happens on all my sessions too. See the attached screenshot for the error message.

![Screenshot 2022-02-15 at 08 02 35](https://user-images.githubusercontent.com/18121038/154018734-996beea4-6df9-409a-bdb5-f82ab880d684.png)

**Comment by ghobona** [comment]
@jerstlouis Today (2022-02-21) we confirmed that the **Download Log Files** mechanism works. May we close this GitHub issue?

The **viewOldSessionLog** problems will be reported as separate issues.

**Comment by jerstlouis** [comment]
Thank you @ghobona and @dstenger . Closing the issue.

**Comment by dstenger** [comment]
I created two new issues as announced by @ghobona:
* viewOldSessionLog problem reported in https://github.com/opengeospatial/teamengine/issues/486#issuecomment-1039974992: https://github.com/opengeospatial/teamengine/issues/499
* Problem with HTTP status code reported in https://github.com/opengeospatial/teamengine/issues/486#issuecomment-1018414834: https://github.com/opengeospatial/teamengine/issues/500
