### ISSUE TITLE
Add TEAM Engine documentation to TEAM Engine landing page

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/teamengine#491]
Currently, the landing page is available here: https://cite.opengeospatial.org/teamengine/
And the documentation here: https://opengeospatial.github.io/teamengine/
Shall be similar to the documentation of the test suites: https://cite.opengeospatial.org/teamengine/about/wfs/2.0.0/site/

So, the documentation shall be provided via the TEAM Engine webapp.

**Comment by dstenger** [comment]
CITE status meeting 2022-03-24:

* Link to https://opengeospatial.github.io/teamengine/ shall be added to https://github.com/opengeospatial/teamengine-site so that a user can access the documentation from the landing page.
* Following sentence shall be added:
  * The source of the engine and the tests are available at [GitHub](https://github.com/opengeospatial/teamengine). **The documentation of the engine is available here(link).** The [CITE forum](http://cite.ogc.org/forum) provides a place to ask questions and help developers pass the tests.

**Comment by bpross-52n** [comment]
Done for the beta site: https://github.com/opengeospatial/teamengine-site/commit/0d6e18ef1a1d2cda79b49a8fd9782bf6e719c361
