### ISSUE TITLE
Current TeamEngine is very lagging and not usable

### ISSUE THREAD

**Issue by bangph** [opengeospatial/teamengine#505]
I've tried in both Firefox and Chrome browsers.

When it goes to this URL https://cite.opengeospatial.org/teamengine/test.jsp
it opens an empty pop up windows and I've tried multiple times to click on "OK" button, but it doesn't run any tests like years ago when I just had to click one time only on the button.

Please see the image: 
![image](https://user-images.githubusercontent.com/6914451/156390428-98d6ae35-05a6-45ae-9af4-c3d6d9bd55ff.png)

**Comment by bangph** [comment]
@dstenger  Please check this as I couldn't perform the test on TeamEngine https://cite.opengeospatial.org/teamengine/test.jsp

**Comment by bangph** [comment]
@dstenger  thanks for quick reply. I tested Beta on Firefox, it works fast. However, OGC WCS 2.0.1 test core has java exception. Please see full log at https://pastebin.com/nqK8BYL7

**Comment by dstenger** [comment]
Thanks for reporting back.
Can you please describe the error more in detail?
Is the StackTrace printed in the test result or is it displayed instead of a test result?

**Comment by bangph** [comment]
@dstenger After the session finished quickly, it has this repport 
![image](https://user-images.githubusercontent.com/6914451/156400366-c4cf7329-042b-40ee-af55-e92c171bc1fb.png)

then, I clicked on **See the [detailed old test report](http://cite.ogc.org/te2/viewOldSessionLog.jsp?session=s0107).**. It opens a new tab on Firefox with the stack trace.

**Comment by dstenger** [comment]
Thank you for the detailed feedback.
The problem seems to be connected to the one documented in https://github.com/opengeospatial/teamengine/issues/499.

This problem, however, just occurs on Beta (te2).
Can you please re-check if a test run on Production is possible? I am able to view the detailed old test report there when using the service provided by you. I used Firefox 97.0.1 (64-Bit) for testing.
So, I am still not able to reproduce the error documented in the description of this issue (please note that there is a problem with Chrome).

**Comment by bangph** [comment]
@dstenger I tested again on the official CITE test with Firefox 97.0.1 (64 bit), this time, it runs fast. 

The log error is not useful though for me to understand why and what caused it failed. 

`
Log for test s0137

Test wcs2:main type Mandatory default result Passed (s0137)

Assertion: Prune query parameters if present.

Request d13242e33_1:
   Method: get
   URL: http://conformance.rasdaman.com/rasdaman/ows
Error in call to extension function {public org.w3c.dom.NodeList com.occamlab.te.TECore.request(org.w3c.dom.Document,java.lang.String) throws java.lang.Throwable}: Exception in extension function java.lang.RuntimeException: Parser {http://www.occamlab.com/te/parsers}XMLValidatingParser threw an exception.
Result: Failed

![image](https://user-images.githubusercontent.com/6914451/156431788-17b9a876-27a3-4af8-bdb9-b3f2ab452fb6.png)


I clicked on: [Test wcs2:main](http://cite.opengeospatial.org/teamengine/listings/_root_te_base_scripts_wcs_2.0.1_ctl_wcs2main.html#wcs2:main) ([View Details](http://cite.opengeospatial.org/teamengine/viewTestLog.jsp?test=s0137)): Failed

`

Anyway, what I wanted for this ticket is OGC CITE can be run fast, so I can check what is wrong on my endpoint.
