### ISSUE TITLE
Cannot reach validator (production)

### ISSUE THREAD

**Issue by JohannaOtt** [opengeospatial/teamengine#517]
**Describe the bug**
The page http://cite.opengeospatial.org/teamengine/ is not loading for me and eventually failing with a Bad Gateway. The same already happened yesterday but I thoght it might only be a shorttime. As it still won't load today, I am reporting this issue now.

**To Reproduce**
1. Try to reach http://cite.opengeospatial.org/teamengine/ 

**Expected behavior**
I would expect to be able to access the validator.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/34163838/164388121-07fbfea1-d39d-41cd-a267-6b966a1ab199.png)

**Comment by ghobona** [comment]
@JohannaOtt I have just tried it at 08:40 UTC+1 and it appears to be working. Please try it again.

**Comment by JohannaOtt** [comment]
Yes, I can confirm that it is working now.

**Comment by ghobona** [comment]
Reopening this issue because the server appears to down again.

We are looking into it and we'll reboot the server by 09:30am EDT today.

**Comment by ghobona** [comment]
The Production validator is working again.

There appears to be a server that is causing the validator to crash. We will update the validator to handle the issue without crashing.

In the meantime, we have set up a daily automated reboot for around 08:00am EDT. 

We will keep this Issue open until the crashing has been fixed.

**Comment by dstenger** [comment]
@JohannaOtt The root cause of the crash was fixed and we disabled the restart.
If you detect any further problem, please inform us.
