### ISSUE TITLE
Session id is not displayed correctly

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/teamengine#523]
**Describe the bug**
When current status of master branch is deployed, the session ids are not displayed correctly.
Please see screenshot at the bottom of this issue.

**To Reproduce**
1. Setup master branch of TEAM Engine.
2. Execute test session.
3. View session list (e.g. http://localhost:8081/teamengine/viewSessions.jsp).

**Expected behavior**
Session id shall be displayed as previously (see Production environment): E.g. s0001

**Screenshots**
![Bildschirmfoto vom 2022-05-10 20-51-19](https://user-images.githubusercontent.com/2989166/167701296-30f03b67-1184-4aa8-a4ee-24df8ce8fc3a.png)

**Comment by bpross-52n** [comment]
This was introduced within the code fortification effort by Chuck. I can revert the changes. Let me know if I should do it.
