### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by Rhynchocephale** [opengeospatial/teamengine#535]
I am trying to install Team Engine on a Linux Mint. The `mvn install` instruction gives the following result:

> [INFO] -------------------------------------------------------------
> [ERROR] COMPILATION ERROR : 
> [INFO] -------------------------------------------------------------
> [ERROR] /home/Rhynchocephale/Documents/teamengine/teamengine-realm/src/main/java/com/occamlab/te/realm/PasswordStorage.java:[17,22] package javax.xml.bind does not exist
> [ERROR] /home/Rhynchocephale/Documents/teamengine/teamengine-realm/src/main/java/com/occamlab/te/realm/PasswordStorage.java:[210,16] cannot find symbol
>   symbol:   variable DatatypeConverter
>   location: class com.occamlab.te.realm.PasswordStorage
> [ERROR] /home/Rhynchocephale/Documents/teamengine/teamengine-realm/src/main/java/com/occamlab/te/realm/PasswordStorage.java:[214,16] cannot find symbol
>   symbol:   variable DatatypeConverter
>   location: class com.occamlab.te.realm.PasswordStorage
> [INFO] 3 errors 
> [INFO] -------------------------------------------------------------
> [INFO] ------------------------------------------------------------------------
> [INFO] Reactor Summary for TEAM Engine 5.5-SNAPSHOT:
> [INFO] 
> [INFO] TEAM Engine ........................................ SUCCESS [  6.833 s]
> [INFO] TEAM Engine - Tomcat Realm ......................... FAILURE [  9.665 s]
> [INFO] TEAM Engine - Shared Resources ..................... SKIPPED
> [INFO] TEAM Engine - Core Module .......................... SKIPPED
> [INFO] TEAM Engine - Service Providers .................... SKIPPED
> [INFO] TEAM Engine - CTL Test Suite Providers ............. SKIPPED
> [INFO] TEAM Engine - Web Application ...................... SKIPPED
> [INFO] TEAM Engine - Console Application .................. SKIPPED
> [INFO] TEAM Engine - Virtualization ....................... SKIPPED
> [INFO] TEAM Engine - Tests ................................ SKIPPED
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time:  17.419 s
> [INFO] Finished at: 2022-06-28T08:34:33+02:00
> [INFO] ------------------------------------------------------------------------
> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.6.0:compile (default-compile) on project teamengine-realm: Compilation failure: Compilation failure: 
> [ERROR] /home/Rhynchocephale/Documents/teamengine/teamengine-realm/src/main/java/com/occamlab/te/realm/PasswordStorage.java:[17,22] package javax.xml.bind does not exist
> [ERROR] /home/Rhynchocephale/Documents/teamengine/teamengine-realm/src/main/java/com/occamlab/te/realm/PasswordStorage.java:[210,16] cannot find symbol
> [ERROR]   symbol:   variable DatatypeConverter
> [ERROR]   location: class com.occamlab.te.realm.PasswordStorage
> [ERROR] /home/Rhynchocephale/Documents/teamengine/teamengine-realm/src/main/java/com/occamlab/te/realm/PasswordStorage.java:[214,16] cannot find symbol
> [ERROR]   symbol:   variable DatatypeConverter
> [ERROR]   location: class com.occamlab.te.realm.PasswordStorage
> [ERROR] -> [Help 1]
> [ERROR] 
> [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
> [ERROR] Re-run Maven using the -X switch to enable full debug logging.
> [ERROR] 
> [ERROR] For more information about the errors and possible solutions, please read the following articles:
> [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
> [ERROR] 
> [ERROR] After correcting the problems, you can resume the build with the command
> [ERROR]   mvn <args> -rf :teamengine-realm

**Comment by ghobona** [comment]
TEAM Engine is designed to run on Java 8 and Tomcat 7.

Could you please confirm which versions of Java and Tomcat you are running?

**Comment by ghobona** [comment]
Installation instructions are at http://opengeospatial.github.io/teamengine/installation.html

**Comment by Rhynchocephale** [comment]
It was indeed the Java version. I assumed it was 8 or higher instead of just 8. Build succeeded, thank you.
