### ISSUE TITLE
Implement consideration of config.xml on classpath

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/teamengine#561]
This is especially important when a *aio.jar of a test suite is used. Then, the config.xml is taken from classpath and must not be referenced externally.

Also see https://github.com/opengeospatial/ets-wfs20/issues/230.

**Comment by dstenger** [comment]
@bpross-52n Can you please try to generate a generic config.xml which is put to TEAM Engine itself. This enables us to use the pull request with each test suite immediately without updating the test suites.

**Comment by bpross-52n** [comment]
I have added a commit to the Pull Request #562

**Comment by dstenger** [comment]
@bpross-52n Some unit tests are failing when building the branch of the pull request.
