### ISSUE TITLE
Update Maven plugins to latest versions

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/teamengine#574]
Branch: `6.0`

**Comment by dstenger** [comment]
Updated all plugins to the latest version and refactored declaration of version to main pom file: https://github.com/opengeospatial/teamengine/commit/17cb706c6fcf19c9c9a44cbd310610c20261ca4e

The maven-javadoc-plugin has not been updated so far as multiple errors occurred after update to v3.5.0.

`mvn clean install` can be executed successfully.
However, processes like creating a release or executing the SoapUI tests must be tested as well. Further adjustments might be necessary.

**Comment by vishalsingh2972** [comment]
@dstenger @ghobona  can you please review PR https://github.com/opengeospatial/teamengine/pull/583/files

**Comment by vishalsingh2972** [comment]
@dstenger @ghobona  can you please review PR https://github.com/opengeospatial/teamengine/pull/583

**Comment by vishalsingh2972** [comment]
@dstenger @ghobona can you please review PR https://github.com/opengeospatial/teamengine/pull/583

**Comment by vishalsingh2972** [comment]
@dstenger @ghobona can you please review PR https://github.com/opengeospatial/teamengine/pull/583

**Comment by dstenger** [comment]
Updated minor and patch versions of several plugins: https://github.com/opengeospatial/teamengine/commit/bee90b78a01ee1aa77f6b8a27157b146148b8454

**Comment by dstenger** [comment]
Set soapui-maven-plugin to version 5.7.2: https://github.com/opengeospatial/teamengine/commit/bc10569b432ff5d6eb47eed6dc8298a5311bb3cd
