### ISSUE TITLE
Update Maven dependencies to latest versions

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/teamengine#579]
Branch: `6.0`

**Comment by vishalsingh2972** [comment]
@dstenger can you review PR https://github.com/opengeospatial/teamengine/pull/583/files

**Comment by vishalsingh2972** [comment]
@dstenger can you please review PR https://github.com/opengeospatial/teamengine/pull/583/files

**Comment by vishalsingh2972** [comment]
@dstenger @ghobona  can you please review PR https://github.com/opengeospatial/teamengine/pull/583

**Comment by vishalsingh2972** [comment]
@dstenger @ghobona can you please review PR https://github.com/opengeospatial/teamengine/pull/583

**Comment by vishalsingh2972** [comment]
@dstenger @ghobona can you please review PR https://github.com/opengeospatial/teamengine/pull/583

**Comment by dstenger** [comment]
Updated dependencies commons-codec to version 1.16.0 and guava to version 32.1.2-jre: https://github.com/opengeospatial/teamengine/commit/2d2d8fef3bf8f844dffc31bb0008b2b9d326fba7

**Comment by dstenger** [comment]
Updated dependency jena-core to version 4.9.0: https://github.com/opengeospatial/teamengine/issues/579

**Comment by dstenger** [comment]
Refactored versions to dependencyManagement: https://github.com/opengeospatial/teamengine/commit/699c138423aff37d5b88796f4d4ce8ad581c80e7

**Comment by dstenger** [comment]
Following dependencies must still be updated to the latest versions:

    <dependency>
      <groupId>org.testng</groupId>
      <artifactId>testng</artifactId>
    </dependency>

    <dependency>
      <groupId>org.xmlmatchers</groupId>
      <artifactId>xml-matchers</artifactId>
    </dependency>

xml-matchers might be replaced.

**Comment by dstenger** [comment]
Remaining tasks were moved to separate issues:
* #598
* #599
