### ISSUE TITLE
Improve handling of passwords of REST interface

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/teamengine#588]
Branch: `6.0`

Classes to consider: `PBKDF2Realm` and `UserFilesRealm`

Current status is more a workaround. Relevant commits:
* https://github.com/opengeospatial/teamengine/commit/a4b0f731a54c85bbab17dc4775684d961f90f91a
* https://github.com/opengeospatial/teamengine/commit/a695251f865d57c4e4781f80b6528c1d97dc7cd0

Mechanism shall be improved.

**Comment by bpross-52n** [comment]
According to this [link](https://github.com/apache/tomcat/commit/cf239bb4450927fbc03d6648ea593306380725ba), the credentials should be managed by the realm, which is now the case. Here is another example in the code of Apache Tomcat: https://github.com/apache/tomcat/blob/main/java/org/apache/catalina/realm/UserDatabaseRealm.java
Imho, the solution is fine.
