### ISSUE TITLE
Mangled test names in TestNG report (acronyms not supported)

### ISSUE THREAD

**Issue by rjmartell** [opengeospatial/teamengine#63]
Some test names displayed in TestNG reports are incomprehensible. Mangled names have been observed in at least two test suites (see screenshots below).

![report-gml32](https://cloud.githubusercontent.com/assets/1653506/4649039/1e7f6234-5487-11e4-8a0a-a71aa08e9697.png)

![report-wfs20](https://cloud.githubusercontent.com/assets/1653506/4649042/279d45ca-5487-11e4-87f8-e96de0b8db80.png)

[Recent modifications](https://github.com/opengeospatial/teamengine/pull/43) to the XSLT stylesheet that generate the HTML report attempt to derive the display name from the test method name but it appears to fail in some cases.

**Comment by tanvi-shah** [comment]
Hi, Upendra has resolved the name mangled issue. We have checked it for GML and KML tests. Please see the attached screen shots.
![for kml](https://cloud.githubusercontent.com/assets/7500215/5629687/2b41b33c-95dc-11e4-86da-6c95a27ea56d.png)
![for gml](https://cloud.githubusercontent.com/assets/7500215/5629688/2bd779bc-95dc-11e4-9fb2-ce4b6ff77505.png)

**Comment by bermud** [comment]
Great !

**Comment by upendra-sachan** [comment]
Thank you Luis.


------
Upendra Sachan
Mindstix Software Labs
http://www.mindstix.com

*Email:* upendra.sachan@mindstix.com <blah@mindstix.com>
*Phone:* +91 8446253174
*Skype:* upendra.sachan1
