### ISSUE TITLE
Prohibit anonymous test execution using the REST API

### ISSUE THREAD

**Issue by rjmartell** [opengeospatial/teamengine#66]
Authenticate all agents that submit requests to execute a test suite using the REST API. Perhaps this can be done preemptively using the HTTP "basic" authentication scheme (see [RFC 7235](http://tools.ietf.org/html/rfc7235)) over TLS (i.e. `https`).

**Comment by bermud** [comment]
@rjmartell, I'm fine with your solution. I don't see a big issue with the cache problems. We do want to make the REST API secure using the same user password that the user uses for login through the web interface.

**Comment by bermud** [comment]
@rjmartell. this issue is very important. Session logs also need to be created to keep consistency with the other running methods and also to be able to generate statistic appropriately. Has this been updated based on the latest authentication related fixes?

**Comment by dstenger** [comment]
@bermud 
Should anonymous test execution via REST API be disabled?

The requirement to execute test runs with a registered user via REST API is also covered by 1. of #238.
This issue also includes authentication via Web Browser Interface.

**Comment by ghobona** [comment]
@dstenger Yes, let's disable anonymous test execution via REST API please. Users should be authenticated first, before running a test, even when using the REST API.

**Comment by dstenger** [comment]
@keshav-nangare 
Can you please prototype an implementation (seperate branch) containing a proposed solution?
Please use basic auth as authentication mechanism.

**Comment by keshav-nangare** [comment]
@dstenger @ghobona 
 
Following are my findings:
- Current authenticate mechanism
  Web app - FORM-based

- Implementing a BASIC authentication mechanism for Web app + REST API
  1. Our existing Realm-based authentication mechanism used to validate the user's credentials.
  1. The browser will cache the credentials and it can be cleared after the browser gets restarted.
  2. The `LogOut` mechanism will not work due to browser cache.

- Proposed Solution
  1. Keep the Web app authentication as it is.
  2. Implement Basic authentication for REST API.
      1. Add a new filter which will be used for URL's having pattern as `/rest/*`.
      2. If the user does not send credentials in the header, it will prompt asking for credentials. If credentials send via header validation will be done with the existing Realm-based authentication mechanism and if validation failed again prompts get opened.
      3. Valid users can access REST API until the browser gets restarted without asking for credentials as the browser will send the cached valid credentials with every request.

**Comment by ghobona** [comment]
Related to https://github.com/opengeospatial/teamengine/issues/397

**Comment by keshav-nangare** [comment]
Fixed with #433 PR.

**Comment by dstenger** [comment]
TODO: Update documentation.
