### ISSUE TITLE
Incorrect verdict reported in console output

### ISSUE THREAD

**Issue by rjmartell** [opengeospatial/teamengine#70]
When running a test suite using the console (CLI) application, the overall verdict is incorrect. For example, the following snippet is extracted from the results for the `note.ctl` suite:

            Test note:check-user Failed
        Test note:main Failed
    Suite note:note-test Failed

The actual result code shown in the test log (log.xml) for the starting test is correct: 5 (inherited failure).

**Comment by bermud** [comment]
We need to create unit tests to verify the fixes on these type of issues. See #72.

**Comment by bermud** [comment]
@upendra-sachan, can you please verify if this is related to issue #112 and if we can close this issue?

**Comment by upendra-sachan** [comment]
@bermud, I verified it, this is related to issue #112  and it was solved.
