### ISSUE TITLE
WMS Test Log file names are hardcoded in TEAM Engine 

### ISSUE THREAD

**Issue by tanvi-shah** [opengeospatial/teamengine#76]
Hardcoded in the following files:

 teamengine/teamengine-web/src/test/java/com/occamlab/te/web/CoverageMonitorTest.java
 teamengine-web/src/main/resources/coverage/
 teamengine/teamengine-resources/src/main/resources/com/occamlab/te/logstyles/result-log.xsl

**Comment by bermud** [comment]
I think this was solved in https://github.com/opengeospatial/teamengine/issues/87
@upendra-sachan, Please re-open if this is not correct. Thank you!

**Comment by upendra-sachan** [comment]
Sure Luis.


------
Upendra Sachan
Mindstix Software Labs
http://www.mindstix.com

*Email:* upendra.sachan@mindstix.com <blah@mindstix.com>
*Phone:* +91 8446253174
*Skype:* upendra.sachan1
