### ISSUE TITLE
Mismatch of test results displayed on the console and in the web page

### ISSUE THREAD

**Issue by tanvi-shah** [opengeospatial/teamengine#77]
The result of the tests obtained via console and via web are different.
This is because on console:
If the child test fails and parent test passes then the Parent test's final result is : PASS

Whereas in web:
If the child test fails and parent test passes then the Parent test's final result is : FAIL

This issue has been reproduced for the following tests (This may be reproducible for all other CTL tests as well):
CSW 2.0.2
WFS 1.1.0
WMS Client 1.3

**Comment by bermud** [comment]
@upendra-sachan, can you please verify this is no longer the case and that this was fixed with fix for issue #112?

**Comment by upendra-sachan** [comment]
Yes Luis, this issue was fixed with issue #112. I verified it.


------
Upendra Sachan
Mindstix Software Labs
http://www.mindstix.com

*Email:* upendra.sachan@mindstix.com <blah@mindstix.com>
*Phone:* +91 8446253174
*Skype:* upendra.sachan1
