### ISSUE TITLE
TEAM Engine 5.0 new report

### ISSUE THREAD

**Issue by bermud** [opengeospatial/teamengine#81]
Related to #39  and #45

The report should have at least these elements and be very simple to understand.

# Main page for report
## Summary Results
- Test Name
- Test id
- Test version
- Test date
- Basic Conformance Classes
- Test input
   - $key $value
- Result
   - Number of conformance classes tested: 
   - Passed core (can be certified) ? 
   - Number of conformance class passed?
   - Number of conformance class failed?

## Conformance Classes

For each conformance class
- Conformance Class Name
- Conformance Class Description

Summary box pass fail

The user should be able to click on a row on the table (a test) and get another page with the following information:

# Page for a particular test

- name of the test
- description about the test (assertion)
- result
- inputs (request, file , part of file)
- outputs (response provided by the implementation being tested or output file, etc)
- if it failed
   - the reason
   - possible changes

![results](https://cloud.githubusercontent.com/assets/3738898/15183739/6dbbe2da-1760-11e6-8093-fb583b7a943c.png)

# Updates required on tests
Changes are required on existing tests to support this new reporting. Details here: https://github.com/opengeospatial/cite/wiki/Encoding-Conformance-Classes

**Comment by bermud** [comment]
Solution is being discussed here:
https://github.com/opengeospatial/teamengine/wiki/Reporting-for-TEAM-Engine-5.0

**Comment by bermud** [comment]
Ideas for improvement were discussed and coded in this pull request
https://github.com/opengeospatial/teamengine/pull/78

**Comment by bermud** [comment]
Please continue looking into EARL and conversion from TestNG and CTL output to RDF and then to HTML.

**Comment by bermud** [comment]
An initial implementation of an EARL listener for TestNG should be available by the end of this week; see <https://github.com/opengeospatial/teamengine/issues/152>. 

We can use the output of this as a basis for considering what info should be included in the results.


Work to be advance:

- script to convert CTL test results to EARL RDF/XML 
- script to convert EARL RDF/XML results to HTML5 report

**Comment by bermud** [comment]
@keshav-nangare EARL Listener was implemented  in 4.7.1. We should be able to move this task forward.

**Comment by keshav-nangare** [comment]
The branch "earl_html_report" contains xslt file, which will convert the earl resut into HTML report.

Commit: 191084d3b350737692929dad9ea6b0e0705e9d9b

**Comment by keshav-nangare** [comment]
@rjmartell 

    We are trying to add the XML content in the EARL report it is added with the encoded format.
        
Example:
         XML content:
                    <values>
                        <value key="inputs">41</value>
                    </values>
       
        EARL Report:
                    <cnt:ContentAsXML>
                        <cnt:rest>&lt;?xml version="1.0" encoding="UTF-8"? &lt;values&gt;&lt;value key="inputs"&gt;41&lt;/value&gt;&lt;/values&gt;</cnt:rest>
                    </cnt:ContentAsXML>
                   
Is there any way to add these xml content in earl report as it is?

**Comment by keshav-nangare** [comment]
## CTL EARL Report: 

The branch ["earl_report"](https://github.com/opengeospatial/teamengine/tree/earl_report) contains the work that I have done up till now.


We have updated the teamengine with the following:

1. The teamengine will generate the EARL report when CTL test executed through the web
2. Moved the CtlEarlReporter class to teamengine-core module.
3. Updated the request & response. Added the isBasic attribute in earl report from CTL test context.
4. Added the isBasic attribute in TestNG test context and updated the testName with good names:
         - While adding the isBasic attribute in the TestNG test context we need to do following changes:
                    - We need to add the conformance classes into config.xml of the corresponding test.
                    
```
                   - Example: 
                               &lt;conformanceClasses&gt;
	                             &lt;conformanceClass&gt;GML Documents&lt;/conformanceClass&gt;
                               &lt;/conformanceClasses&gt;
```


5. Fixed the result issue of the viewSessionLog page.
6. Added the request and response in earl report.

**Comment by keshav-nangare** [comment]
Updated the EARL HTML Report:

Following are screenshots of CTL and TestNG tests results:

**CTL sample test result:**

Test Result:
![ctl_sample_test_result](https://cloud.githubusercontent.com/assets/14732650/24192960/a981d4e2-0f16-11e7-8686-e03b0bc60150.png)

Test Details:
![ctl_sample_testdetails_result](https://cloud.githubusercontent.com/assets/14732650/24192983/b7d01162-0f16-11e7-9d8a-a08bb4e22276.png)

**TestNG gml32 test result:**

Test Result:
![testng_gml_test_result](https://cloud.githubusercontent.com/assets/14732650/24193158/48ef390c-0f17-11e7-88b9-d7b318458bbb.png)

Test Details:
![testng_gml_testdetails_result](https://cloud.githubusercontent.com/assets/14732650/24193162/4c667e7e-0f17-11e7-95e6-bdc384189ae8.png)

@bermud 
Please review this report and suggest if any changes required.

Thank you.

**Comment by bermud** [comment]
@keshav-nangare great progress
Recommendations:
- Test with CTL test (e.g. WFS 1.1)
- Test Input should have a value
- The link to the test should be presented in one page. See the first comment on this issue.
- Main information of the test should summarize conformance classes. See the first comment on this issue.

**Comment by bermud** [comment]
From the individual test report:

- [ ] add a link to “go back to the main report”
- [ ] remove the “java.lang.Assertion>error> and other types of java errors. Just provide the text of the error
- [ ] Remove the" expected true but found false" message.
- [ ] Show colorful XML for the requests and responses if they are in XML 
- [ ] For future:  provide XML snippet and highlight where the code fails

**Comment by bermud** [comment]
- [ ] change the test name to be human readable (w.g. GML 3.2)
- [ ] add test version
- [ ] add test id 
- [ ] before test id; add “Basic Conformance Classes"
- [ ] improve the key an valued in tabular form
- [ ] update the test to include information about conformance classes
- [ ] specify in the report, which ones are the core and make sure they appear first.
- [ ] create issues on all tests github repositories that require update

**Comment by bermud** [comment]
Provided by Keshav 2017.05.23 
![test session results 2](https://cloud.githubusercontent.com/assets/3738898/26354414/74b475f6-3f92-11e7-98a0-24a7f3cb556f.png)

Comments:
The new reported addresses the points from previous comment.

We need to improve as follows:

- [ ] Conformance Clases  (in the 5th line) should be indented and presented similar to how the items of the Result are presented
- [ ] add statistics (counts) about number of tests in conformance classes. See issue #216 
- [ ] test inputs should be indented and presented similar to how the items of the Result are presented

**Comment by keshav-nangare** [comment]
Updated Report with the suggestions:

![gml32_result_with_new_earl_report](https://user-images.githubusercontent.com/14732650/27383463-b7f49a4e-56a8-11e7-930e-4232fb89c5d5.png)

**Comment by dstenger** [comment]
There are still open check boxes in previous comments. Are all tasks solved?

**Comment by dstenger** [comment]
TODO: Review this issue and add new ideas/ improvements to wiki page.

**Comment by lgoltz** [comment]
Open issue documented in #285. New ideas should be reported as new issue.
