### ISSUE TITLE
"teamengine" (war name) is hardcoded in code

### ISSUE THREAD

**Issue by upendra-sachan** [opengeospatial/teamengine#87]
The "teamengine" word, which is a war name, is hard-coded in many places. This creates an issue with deplyoing the war with different name.

Following is the example of hardcoded code : **ConfigFileBuilder.java.**

In this, it uses following lines:

public class ConfigFileBuilder {

    public static void main(String[] args) throws Exception {
        String home = "";
        String scriptsDir = "webapps/teamengine/WEB-INF/scripts";
        String workDir = "webapps/teamengine/WEB-INF/work";
        String usersDir = "webapps/teamengine/WEB-INF/users";
        String resourcesDir = null;
        String defaultRevision = (new SimpleDateFormat("yyyy-MM-dd"))
                .format(new Date());

        // Parse arguments from command-line
        for (int i = 0; i < args.length; i++) {
            if (args[i].startsWith("-home=")) {

**Comment by bermud** [comment]
Can you please fix this issue?. Im not sure the example code you provide is actually called when deploying team engine. Thank you.

**Comment by bermud** [comment]
Fixed with this commit https://github.com/opengeospatial/teamengine/commit/da03199bbe69a9f10955241c6715e76eed5816fb
